### ISSUE TITLE
Docker exec fails on ARM64 linux machine

### ISSUE THREAD

**Issue by siyangy** [docker/for-linux#105] opened 2017-09-15 23:03 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
Docker exec works, and traps into a docker previously started with run -itd.

### Actual behavior
Docker exec failed with: rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "open /proc/self/fd: no such file or directory"

### Steps to reproduce the behavior
docker run -itd <IMAGE_ID> /bin/bash
docker exec -it <CONTAINER_ID> /bin/bash

Running docker run -it <IMAGE_ID> /bin/bash works as expected.

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Wed Jul 12 01:23:30 2017
 OS/Arch:      linux/arm64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Wed Jul 12 01:23:30 2017
 OS/Arch:      linux/arm64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 27
 Running: 1
 Paused: 0
 Stopped: 26
Images: 149
Server Version: 17.05.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.38-rt49-tegra
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: aarch64
CPUs: 6
Total Memory: 6.504GiB
Name: REDACTED
ID: REDACTED
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: REDACTED
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
OS version: Ubuntu 16.04
The docker is originally built from source code docker-aarch64-17.05.0-ce.tar.gz.

**Comment by seemethere** [comment] 2017-09-15 23:08
Docker 17.05.0-ce was not originally supported for aarch64.

Can you try this with the 17.09 release?

Installation instructions:
```shell
# Executing docker install script, commit: 716f7ca
apt-get update -qq >/dev/null
apt-get install -y -qq apt-transport-https ca-certificates curl software-properties-common >/dev/null
curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | apt-key add -qq - >/dev/null
echo "deb [arch=arm64] https://download.docker.com/linux/ubuntu xenial edge" > /etc/apt/sources.list.d/docker.list
apt-get update -qq >/dev/null
apt-get install -y -qq docker-ce >/dev/null
```

**Comment by siyangy** [comment] 2017-09-15 23:33
I got the same error after upgrading docker version. The `docker version` command gives me:
```
Client:
 Version:      17.07.0-ce
 API version:  1.31
 Go version:   go1.8.3
 Git commit:   8784753
 Built:        Tue Aug 29 17:42:57 2017
 OS/Arch:      linux/arm64

Server:
 Version:      17.07.0-ce
 API version:  1.31 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   8784753
 Built:        Tue Aug 29 17:41:18 2017
 OS/Arch:      linux/arm64
 Experimental: false
```

**Comment by siyangy** [comment] 2017-09-20 19:56
Ping on this. This is currently blocking me.

**Comment by thaJeztah** [comment] 2017-10-30 09:02
Are you having this problem with any image? Can you provide the exact steps to reproduce (with an actual image, instead of `<image>`?

**Comment by chaoflow** [comment] 2017-11-28 20:05
@thaJeztah @seemethere same here with alpine image and 17.09:
```
ubuntu@nvidia:~$ uname -m
aarch64
ubuntu@nvidia:~$ docker --version
Docker version 17.09.0-ce, build afdb6d4
ubuntu@nvidia:~$ docker run --detach --name alpine -ti alpine  sh
bf1d379b35e99b3789d770ee1e077f410d68918eb0c08c19c25cd3de20bfd039
ubuntu@nvidia:~$ docker ps |grep alpine
bf1d379b35e9        alpine                                          "sh"                     8 seconds ago       Up 7 seconds                                 alpine
ubuntu@nvidia:~$ docker exec -ti alpine sh
oci runtime error: exec failed: container_linux.go:265: starting container process caused "open /proc/self/fd: no such file or directory"              
```

**Comment by seemethere** [comment] 2017-11-28 20:24
@chaoflow not entirely sure what could be going on

I ran that exact workflow on an arm64 machine that we have and got this:

```
root@pkt-04:~# docker version
Client:
 Version:      17.11.0-ce
 API version:  1.34
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:33:07 2017
 OS/Arch:      linux/arm64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:31:16 2017
 OS/Arch:      linux/arm64
 Experimental: false
root@pkt-04:~# docker run --detach --name alpine -ti alpine  sh
09f3e729fd87ad9149c4c62ffbaf844285ae658e7c900ce6c489d667c2ca7e6e
root@pkt-04:~# docker ps |grep alpine
09f3e729fd87        alpine              "sh"                8 seconds ago       Up 7 seconds                            alpine
root@pkt-04:~# docker exec -ti alpine sh
/ # exit
root@pkt-04:~#
```

**Comment by chaoflow** [comment] 2017-11-28 20:32
@seemethere thanks for the fast response! Now as well on 17.11, but same problem:
```
ubuntu@nvidia:~$ docker version
Client:
 Version:      17.11.0-ce
 API version:  1.34
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:33:07 2017
 OS/Arch:      linux/arm64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:31:16 2017
 OS/Arch:      linux/arm64
 Experimental: false
ubuntu@nvidia:~$ docker rm --force alpine
alpine
ubuntu@nvidia:~$ docker run --detach --name alpine -ti alpine  sh
b2aee24a0886fefbd1ef8c50e8d3d9164500a4d1661b116615e5bc678f19429c
ubuntu@nvidia:~$ docker ps |grep alpine
b2aee24a0886        alpine              "sh"                     6 seconds ago        Up 5 seconds                            alpine
ubuntu@nvidia:~$ docker exec -ti alpine sh
OCI runtime exec failed: exec failed: container_linux.go:295: starting container process caused "open /proc/self/fd: no such file or directory": unknown
ubuntu@nvidia:~$ 
```

**Comment by seemethere** [comment] 2017-11-28 21:00
@chaoflow can you try to do a `docker pull alpine` before running the container? 

I'm thinking you may have an outdated alpine image on that particular node.

**Comment by chaoflow** [comment] 2017-11-29 07:37
@seemethere The alpine image is up-to-date; pull did not result in a newer image.

**Comment by chaoflow** [comment] 2017-11-29 15:56
More testing:

```shell
$ docker run --privileged --name df-docker -d docker:17.11.0-dind 
$ docker run --rm -it --link df-docker:docker docker:17.11.0 sh

# In docker container shell
$ docker run --detach --rm --name alpine -ti alpine sh
$ docker exec -ti alpine sh
OCI runtime exec failed: exec failed: container_linux.go:295: starting container process caused "open /proc/self/fd: no such file or directory": unknown
```

dockerd log for failing exec command:
```
Nov 29 07:19:34 nvidia dockerd[1659]: time="2017-11-29T07:19:34.777281520-08:00" level=debug msg="Calling GET /_ping"
Nov 29 07:19:34 nvidia dockerd[1659]: time="2017-11-29T07:19:34.778294887-08:00" level=debug msg="Calling GET /v1.34/containers/alpine/json"
Nov 29 07:19:34 nvidia dockerd[1659]: time="2017-11-29T07:19:34.783215345-08:00" level=debug msg="Calling POST /v1.34/containers/alpine/exec"
Nov 29 07:19:34 nvidia dockerd[1659]: time="2017-11-29T07:19:34.783482431-08:00" level=debug msg="form data: {\"AttachStderr\":true,\"AttachStdin\":true,\"AttachStdout\":true,\"Cmd\":[\"sh\"],\"Detach\":false,\"DetachKeys\":\"\",\"Env\":null,\"Privileged\":false,\"Tty\":true,\"User\":\"\"}"
Nov 29 07:19:34 nvidia dockerd[1659]: time="2017-11-29T07:19:34.784980848-08:00" level=debug msg="Calling POST /v1.34/exec/b6f6fd35a6035ac88c0a3b33ffa994298887320f04edc164e7019bdb39f5845a/start"
Nov 29 07:19:34 nvidia dockerd[1659]: time="2017-11-29T07:19:34.785160538-08:00" level=debug msg="form data: {\"Detach\":false,\"Tty\":true}"
Nov 29 07:19:34 nvidia dockerd[1659]: time="2017-11-29T07:19:34.785411976-08:00" level=debug msg="starting exec command b6f6fd35a6035ac88c0a3b33ffa994298887320f04edc164e7019bdb39f5845a in container 191446388f9ffd306a274bcb5cb46a8455d58862cc1b18c1aa34ebd92c5b5ba6"
Nov 29 07:19:34 nvidia dockerd[1659]: time="2017-11-29T07:19:34.785691543-08:00" level=debug msg="attach: stdout: begin"
Nov 29 07:19:34 nvidia dockerd[1659]: time="2017-11-29T07:19:34.785745370-08:00" level=debug msg="attach: stdin: begin"
Nov 29 07:19:34 nvidia dockerd[1659]: time="2017-11-29T07:19:34.786203603-08:00" level=debug msg="Calling POST /v1.34/exec/b6f6fd35a6035ac88c0a3b33ffa994298887320f04edc164e7019bdb39f5845a/resize?h=60&w=106"
Nov 29 07:19:34 nvidia dockerd[1659]: time="2017-11-29T07:19:34-08:00" level=debug msg="event published" module="containerd/events" ns=moby topic="/tasks/exec-added" type=containerd.services.events.v1.TaskExecAdded
Nov 29 07:19:34 nvidia dockerd[1659]: time="2017-11-29T07:19:34.788916454-08:00" level=debug msg=event module=libcontainerd namespace=moby topic=/tasks/exec-added
Nov 29 07:19:34 nvidia dockerd[1659]: time="2017-11-29T07:19:34.860321215-08:00" level=error msg="stream copy error: reading from a closed fifo"
Nov 29 07:19:34 nvidia dockerd[1659]: time="2017-11-29T07:19:34.860702292-08:00" level=debug msg="attach: stdout: end"
Nov 29 07:19:34 nvidia dockerd[1659]: time="2017-11-29T07:19:34.860782456-08:00" level=debug msg="attach: stdin: end"
Nov 29 07:19:34 nvidia dockerd[1659]: time="2017-11-29T07:19:34.887014500-08:00" level=error msg="Error running exec b6f6fd35a6035ac88c0a3b33ffa994298887320f04edc164e7019bdb39f5845a in container: OCI runtime exec failed: exec failed: container_linux.go:295: starting container process caused \"open /proc/self/fd: no such file or directory\": unknown"
Nov 29 07:19:34 nvidia dockerd[1659]: time="2017-11-29T07:19:34.887211407-08:00" level=debug msg="Closing buffered stdin pipe"
Nov 29 07:19:34 nvidia dockerd[1659]: time="2017-11-29T07:19:34.887712042-08:00" level=debug msg="Calling GET /v1.34/exec/b6f6fd

**Comment by thaJeztah** [comment] 2017-11-29 17:17
@chaoflow just to check there's nothing special configured on your machine; I see `nvidia` as hostname; you don't happen to be running the nvidia-docker runtime? Any other specific configurations? (perhaps you can add the output of `docker info` as well?

**Comment by chaoflow** [comment] 2017-11-29 18:43
@thaJeztah It's an nvidia tegra board, no nvidia runtime. Output of docker info below:
```
Containers: 19
 Running: 2
 Paused: 0
 Stopped: 17
Images: 28
Server Version: 17.11.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 992280e8e265f491f7a624ab82f3e238be086e49
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.38-rt49-tegra
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: aarch64
CPUs: 6
Total Memory: 6.504GiB
Name: nvidia
ID: REPLACED_BECAUSE_UNSURE_WHETHER_PRIVATE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 31
 Goroutines: 42
 System Time: 2017-11-29T10:40:14.349930423-08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

```
ubuntu@nvidia:~$ /usr/share/docker-ce/contrib/check-config.sh 
info: reading kernel config from /proc/config.gz ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_KEYS: enabled
- CONFIG_VETH: enabled (as module)
- CONFIG_BRIDGE: enabled (as module)
- CONFIG_BRIDGE_NETFILTER: enabled (as module)
- CONFIG_NF_NAT_IPV4: enabled
- CONFIG_IP_NF_FILTER: enabled
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled
- CONFIG_NETFILTER_XT_MATCH_IPVS: enabled
- CONFIG_IP_NF_NAT: enabled
- CONFIG_NF_NAT: enabled
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled

Optional Features:
- CONFIG_USER_NS: enabled
- CONFIG_SECCOMP: enabled
- CONFIG_CGROUP_PIDS: enabled
- CONFIG_MEMCG_SWAP: missing
- CONFIG_MEMCG_SWAP_ENABLED: missing
- CONFIG_BLK_CGROUP: enabled
- CONFIG_BLK_DEV_THROTTLING: missing
- CONFIG_IOSCHED_CFQ: enabled
- CONFIG_CFQ_GROUP_IOSCHED: missing
- CONFIG_CGROUP_PERF: missing
- CONFIG_CGROUP_HUGETLB: missing
- CONFIG_NET_CLS_CGROUP: missing
- CONFIG_CGROUP_NET_PRIO: missing
- CONFIG_CFS_BANDWIDTH: missing
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: missing
- CONFIG_IP_VS: enabled
- CONFIG_IP_VS_NFCT: missing
- CONFIG_IP_VS_RR: missing
- CONFIG_EXT4_FS: enabled
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Network Drivers:
  - "overlay":
    - CONFIG_VXLAN: missing
      Optional (for encrypted networks):
      - CONFIG_CRYPTO: enabled
      - CONFIG_CRYPTO_AEAD: enabled
      - CONFIG_CRYPTO_GCM: missing
      - CONFIG_CRYPTO_SEQIV: missing
      - CONFIG_CRYPTO_GHASH: missing
      - CONFIG_XFRM: enabled
      - CONFIG_XFRM_USER: enabled
      - CONFIG_XFRM_ALGO: enabled
      - CONFIG_INET_ESP: enabled
      - CONFIG_INET_XFRM_MODE_TRANSPORT: enabled
  - "ipvlan":
    - CONFIG_IPVLAN: missing
  - "macvlan":
    - CONFIG_MACVLAN: missing
    - CONFIG_DUMMY: missing
  - "ftp,tftp client in container":
    - CONFIG_NF_NAT_FTP: enabled
    - CONFIG_NF_CONNTRACK_FTP: enabled
    - CONFIG_NF_NAT_TFTP: enabled
    - CONFIG_NF_CONNTRACK_TFTP: enabled
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: missing
  - "btrfs":
    - CONFIG_BTRFS_FS: missing
    - CONFIG_BTRFS_FS_POSIX_ACL: missing
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled
    - CONFIG_DM_THIN_PROVISIONING: missing
  - "overlay":
    - CONFIG_OVERLAY_FS: enabled
  - "zfs":
    - /dev/zfs: missing
    - zfs command: missing
    - zpool command: missing

Limits:
- /proc/sys/kernel/keys/root_maxkeys: 1000000
```

**Comment by thaJeztah** [comment] 2017-11-29 18:56
Thanks! Nothing that stands out in that information, so no ideas at this moment 😕

**Comment by chaoflow** [comment] 2017-12-01 12:02
A workaround to enter a running container as an alternative to docker exec:
```
sudo nsenter --target \
               $(docker inspect --format {{.State.Pid}} NAME) \
               --mount --uts --ipc --net --pid /usr/sbin/chroot \
               /new_root sudo -Hu USER -- bash -li
```
- NAME: name of container
- USER: user inside the container

**Comment by seemethere** [comment] 2018-01-18 19:32
Seems to work fine now on `ubuntu-xenial` with `aarch64` and `docker-ce` 18.01.0-ce. Closing for now.

**Closed by seemethere** 2018-01-18 19:32 UTC

**Comment by jpsamper2009** [comment] 2018-02-20 21:36
@seemethere Can we reopen this? I'm still seeing this on version 18.01.0-ce:

```
$ docker version
Client:
 Version:   18.01.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    03596f5
 Built: Wed Jan 10 20:14:37 2018
 OS/Arch:   linux/arm64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:  18.01.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   03596f5
  Built:    Wed Jan 10 20:12:43 2018
  OS/Arch:  linux/arm64
  Experimental: false
```

**Comment by jpsamper2009** [comment] 2018-02-20 21:37
```
$ docker run --detach --rm --name alpine -ti alpine sh
ff4b8fb51f21058cd940719460c9d7ccafdd6a5212c5c5bc357380b933011d57
$ docker exec -ti alpine sh
OCI runtime exec failed: exec failed: container_linux.go:296: starting container process caused "open /proc/self/fd: no such file or directory": unknown
```

**Comment by siyangy** [comment] 2018-02-20 21:45
@seemethere just FYI, this issue has not been resolved from my end either.

**Comment by seemethere** [comment] 2018-02-20 21:57
Alright I will look into it and see if I can reproduce. What OS are you using?

**Comment by seemethere** [comment] 2018-02-20 22:57
Still unable to reproduce on Ubuntu 16.04:

```
root@eli-pet:~# docker version
Client:
 Version:       18.02.0-ce
 API version:   1.36
 Go version:    go1.9.3
 Git commit:    fc4de44
 Built: Wed Feb  7 21:11:48 2018
 OS/Arch:       linux/arm64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.02.0-ce
  API version:  1.36 (minimum version 1.12)
  Go version:   go1.9.3
  Git commit:   fc4de44
  Built:        Wed Feb  7 21:09:57 2018
  OS/Arch:      linux/arm64
  Experimental: false
root@eli-pet:~# docker run --detach --rm --name alpine -ti alpine sh
21d2ba7dfe1a34fb5a6e2e24154bce3c506b9a277eb8799238e5498f924ad4ed
root@eli-pet:~# docker exec -ti alpine sh
/ # exit
root@eli-pet:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Comment by jpsamper2009** [comment] 2018-02-22 04:18
@seemethere I'm running xenial:

```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

One thing worth noting is that I'm running an RT kernel.

**Comment by jpsamper2009** [comment] 2018-05-01 23:14
Unfortunately, still seeing this on version 18.03.1-ce:

```bash
$ docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:16:22 2018
 OS/Arch:      linux/arm64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:14:27 2018
  OS/Arch:      linux/arm64
  Experimental: false
$ docker run --detach --rm --name alpine -ti alpine sh
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
b78042c299ad: Already exists 
6fd45b97b6c2: Already exists 
Digest: sha256:7df6db5aa61ae9480f52f0b3a06a140ab98d427f86d8d5de0bedab9b8df6b1c0
Status: Downloaded newer image for alpine:latest
6b85bdde114ac3cee95f92779ad894893614c1bda7c8a5bc1327a30e1d49c8ed
$ docker exec -ti alpine sh
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "open /proc/self/fd: no such file or directory": unknown
```

**Comment by chaoflow** [comment] 2018-05-01 23:16
@siyangy Are you also still seeing this issue?

@seemethere Is there anything we can do to help debugging this?

**Comment by fulvi0** [comment] 2018-07-22 22:00
Hi, I'm facing the same issue with a custom image, source image `node:alpine`.

```bash
pi@srvlpi01:~ $ docker run -it fulvi0/node-easy-notes-app_web /bin/bash
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown.
```

**Comment by seemethere** [comment] 2018-07-22 22:03
That's expected. The Alpine image doesn't contain bash by default

**Comment by fulvi0** [comment] 2018-07-22 22:31
@seemethere, with `bash`, `ash` and even without, doesn't run the container.

```bash
pi@srvlpi01:~ $ docker run -it node node:alpine /bin/ash
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"node:alpine\": executable file not found in $PATH": unknown.
pi@srvlpi01:~ $ docker run -d node node:alpine
82a280f6d5b74ac3d854611e37821f82bf13966909dca678a650b42af8e9ea38
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"node:alpine\": executable file not found in $PATH": unknown.
```

**Comment by thaJeztah** [comment] 2018-07-23 12:15
@fulvi0 looks like you made a typo; `node` shouldn't be in between there; the command you typed is;

```
docker run  -it node node:alpine  /bin/ash
```

In that line, `node` is used as image (`node:latest`), and `node:alpine /bin/ash` as command; which fails, because `node:alpine` isn't a valid command in that image.

Try either;

```
docker run -it node /bin/sh
```

or

```
docker run -it node:alpine /bin/ash
```

(or `/bin/sh`)


Note that your second example uses `-d` ("detached"); if you're using `/bin/sh` (or any shell) as your container's command, and don't have a TTY attached, the container will exit immediately after the shell is started. add `-i -t` to the list of options to make sure the container keeps running.

For example (`-dit` is shorthand for `-d -i -t`);

```
docker run -dit alpine sh
```

**Comment by fulvi0** [comment] 2018-07-23 13:17
Hi @siyangy, thank you for the suggestions, and you are right, actually, the error I want to report is the following:

`standard_init_linux.go:190: exec user process caused "exec format error"`

And this error happen in my Raspberry Pi 3 when try to run a container; in my local machine works properly, I created a custom image using `Dockerfile` and `docker-compose` and from the base image `node:alpine`; try to run the same a container from that image and keep throwing the error mentioned above.

Here is my Docker-ce version, Dockerfile and docker-compose.yml

```bash
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:19:46 2018
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:15:34 2018
  OS/Arch:          linux/arm
  Experimental:     false
```

```Dockerfile
FROM node:alpine

RUN mkdir -p /opt/app

# default to port 3000 for node, and 9229 and 9230 (tests) for debug
ARG PORT=3000
ENV PORT $PORT
EXPOSE $PORT 9229 9230

RUN npm i npm@latest -g

WORKDIR /opt
COPY package.json package-lock.json* ./
RUN npm install && npm cache clean --force
ENV PATH /opt/node_modules/.bin:$PATH

# check every 30s to ensure this service returns HTTP 200
HEALTHCHECK --interval=30s CMD node healthcheck.js

# copy in our source code last, as it changes the most
WORKDIR /opt/app
COPY . /opt/app

CMD [ "node", "server.js" ]
``` 
```yaml
version:            "2"

services:
  web:
    build:          .
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image:          mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db

volumes:
  data-volume:
```

**Comment by thaJeztah** [comment] 2018-07-23 13:51
`exec format error` generally is an indication that a binary is built for another architecture than your system (e.g. when trying to run an amd64 binary on arm). 

The `node:alpine` image on Docker Hub is multi-arch (thus pull the image with the right architecture for your machine), but it looks like it doesn't have a variant for `Armv6` or `Armv7`, only `Arm64`;

```bash
docker manifest inspect node:alpine | jq '.manifests[].platform | .os + "/" + .architecture + .variant'

"linux/amd64"
"linux/arm64v8"
"linux/386"
"linux/ppc64le"
"linux/s390x"
``` 

To verify if the image you have pulled matches the architecture you're expecting, you can `docker image inspect` the image; for example

```bash
docker image inspect --format '{{.Os}}/{{.Architecture}}'  node:alpine
```

On my machine, this outputs `linux/amd64` (as it's an amd64 machine)

**Comment by jpsamper2009** [comment] 2018-10-12 17:41
Hi @seemethere , we are still seeing the original issue (`OCI runtime exec failed:... caused "open /proc/self/fd: no such file or directory": unknown`) with `docker 18.06.1-ce builde68fc7a` on an NVIDIA Tegra board. We are 90% sure that it is a hw specific issue (since we have run on other arm boards with no problem). What would be the best way to debug this?

## How to reproduce
```
$ docker run --detach --name alpine -ti alpine sh
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
9941776d74c9: Already exists 
ae94b3cb7a1b: Already exists 
Digest: sha256:621c2f39f8133acb8e64023a94dbdf0d5ca81896102b9e57c0dc184cadaf5528
Status: Downloaded newer image for alpine:latest
07ee82e38fdf7551451364a6b3aa61f6016abc10aa645fd6b5a4043f1262aa7f

$ docker ps | grep alpine
07ee82e38fdf        alpine                                                       "sh"                     9 seconds ago        Up 8 seconds                            alpine

$ docker exec -ti alpine sh
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "open /proc/self/fd: no such file or directory": unknown
```

## System info
$ uname -m
aarch64

$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:34:24 2018
 OS/Arch:           linux/arm64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:32:30 2018
  OS/Arch:          linux/arm64
  Experimental:     false

$ docker image inspect --format '{{.Os}}/{{.Architecture}}' alpine
linux/arm64

$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Comment by mgolub2** [comment] 2018-11-09 18:58
I am also seeing this issue on an Nvidia PX2 board:

```
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "open /proc/self/fd: no such file or directory"
```

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.6.2
 Git commit:   f5ec1e2
 Built:        Thu Jul  5 23:11:16 2018
 OS/Arch:      linux/arm64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.6.2
 Git commit:   f5ec1e2
 Built:        Thu Jul  5 23:11:16 2018
 OS/Arch:      linux/arm64
 Experimental: false
```

**Comment by WillansRR** [comment] 2018-12-14 09:15
To add to this I also see the issue on an Nvidia PX2 board:

> rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "open /proc/self/fd: no such file or directory"

> Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.6.2
 Git commit:   f5ec1e2
 Built:        Thu Jul  5 23:11:16 2018
 OS/Arch:      linux/arm64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.6.2
 Git commit:   f5ec1e2
 Built:        Thu Jul  5 23:11:16 2018
 OS/Arch:      linux/arm64
 Experimental: false

**Comment by quning18** [comment] 2019-06-04 03:35
still no solution?? similar issue on drive px2:

OCI runtime exec failed: exec failed: container_linux.go:344: starting container process caused "close exec fds: open /proc/self/fd: no such file or directory": unknown

**Comment by asharalam11** [comment] 2019-07-30 23:11
Does anybody have a solution to this?

Same error:
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "open /proc/self/fd: no such file or directory": unknown

**Comment by roots-ai** [comment] 2022-08-05 17:15
Same issue. Works on x86 machine but fails on arm64

**Comment by Ybt-1** [comment] 2024-04-26 13:06
@chaoflow Thank you very much, your suggested method solved my problem. I am using Docker 26.1.0 DRIVE-V6.0.3-P3710-AFW-Aurix. This issue had troubled me for two days, and I regret not seeing your comment earlier.
