### ISSUE TITLE
Docker doesn't restart, XFS (dm-13), Devicemapper, centos7

### ISSUE THREAD

**Issue by Niradnik** [docker/for-linux#146] opened 2017-10-31 09:28 UTC
Hey all !

my issue started when kong started with docker compose with nginx consul and konga, crashed.
I decided to do a docker-compose down to stop and remove those containers here problems started.
I’ve got the errors messages
```
Error response from daemon: driver “devicemapper” failed to remove root filesystem 
Error running DeleteDevice dm_task_run failed kong
devmapper: Error saving transaction metadata: devmapper: Error writing metadata to /var/lib/docker/devicemapper/metadata/.tmp526707588: write /var/lib/docker/devicemapper/metadata/.tmp526707588: no space left on device
```
I removed the images and did a volume prune but still I wasn’t able to remove any of the container started with this docker-compose file.
I thus decided to stop the docker service (I did so while other forgotten container were running).
Now I am not able to start it again I get
```
Job for docker.service failed because the control process exited with error code. See “systemctl status docker.service” and “journalctl -xe” for details.
```

systemctl status docker.service gives me:
```
docker.service - Docker Application Container Engine
Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
Drop-In: /etc/systemd/system/docker.service.d
└─http-proxy.conf
Active: failed (Result: start-limit) since Mon 2017-10-30 12:13:54 CET; 17s ago
Docs: https://docs.docker.com
Process: 20211 ExecStart=/usr/bin/dockerd (code=exited, status=1/FAILURE)
Main PID: 20211 (code=exited, status=1/FAILURE)
Memory: 144.0M
CGroup: /system.slice/docker.service

systemd[1]: Failed to start Docker Application Container Engine.
systemd[1]: Unit docker.service entered failed state.
systemd[1]: docker.service failed.
systemd[1]: docker.service holdoff time over, scheduling restart.
systemd[1]: start request repeated too quickly for docker.service
systemd[1]: Failed to start Docker Application Container Engine.
systemd[1]: Unit docker.service entered failed state.
systemd[1]: docker.service failed.
```

and journalctl -xe repeats:
```
kernel: device-mapper: block manager: btree_node validator check failed for block 2689
kernel: device-mapper: btree spine: node_check failed: blocknr 0 != wanted 2689
kernel: device-mapper: block manager: btree_node validator check failed for block 2689
kernel: XFS (dm-13): metadata I/O error: block 0xb40002 (“xfs_buf_iodone_callbacks”) error 5 numblks 1
kernel: node_check: 1326 callbacks suppressed
```

I found out that /var was full the main space was occupied by /var/lib/docker/devicemapper/devicemapper/data may have lead to the first crash.
Now if I want to move /var/lib/docker to a disk with more space as suggested on internet I get
``` mv: cannot remove ‘/var/lib/docker/devicemapper’: Device or resource busy ``` 
but if I check with fuser /var/lib/docker/devicemapper or  lsof | grep devicemapper I don't get any result

I am using devicemapper, I read it may lead to corruption do you think that's the issue reported as XFS (dm-13) ?

I have no idea on what to do to start it back except reboot the system but the system is a server and I can’t easily reboot it.
the OS is Centos 7, kernel 3.10

Have a good day !

**Comment by thaJeztah** [comment] 2017-10-31 23:18
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-10-31 23:18 UTC
