### ISSUE TITLE
mesos dns issue between agent nodes

### ISSUE THREAD

**Issue by preethamnayak** [docker/for-linux#573] opened 2019-01-26 07:43 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Steps to reproduce the behavior

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by preethamnayak** [comment] 2019-01-26 07:46
I am using mesos-dns to communicate between master and agent nodes. I can successfully connect agent nodes from master. But DNS communication failing between two agent nodes. Can anyone help me to resolve this issue ?

**Comment by thaJeztah** [comment] 2019-02-25 19:09
I think that's a bit out of scope for the issue tracker; keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://join.slack.com/t/dockercommunity/shared_invite/enQtNDM4NjAwNDMyOTUwLWZlMDZmYWRjZjk4Zjc5ZGQ5NWZkOWI1Yjk2NGE3ZWVlYjYxM2VhYjczOWIyZDFhZTE3NTUwZWQzMjhmNGYyZTg)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2019-02-25 19:09 UTC
