### ISSUE TITLE
Please provide repo for docker-ce on Fedora 27

### ISSUE THREAD

**Issue by ksylvan** [docker/for-linux#173] opened 2017-11-29 08:58 UTC
This is the same issue that was not ever completely addressed for https://github.com/docker/for-linux/issues/35

Who do we need to bug to make this a consistent part of the Fedora release process?

In a nutshell, the installation files for Fedora 27 are missing at https://download.docker.com/linux/fedora/

**Comment by thaJeztah** [comment] 2017-11-29 15:21
duplicate of https://github.com/docker/for-linux/issues/164

**Closed by thaJeztah** 2017-11-29 15:21 UTC
