### ISSUE TITLE
"Use Rosetta": Certain node.js/amd64 workloads cause container to become unresponsive/100% CPU

### ISSUE THREAD

**Issue by vincent-herlemont** [docker/for-linux#1483] opened 2024-02-06 16:43 UTC
I installed Docker on an Ubuntu virtual machine:

```bash
$> uname -a
Linux ubuntu-linux-22-04-02-desktop 5.15.0-92-generic #102-Ubuntu SMP Wed Jan 10 09:37:39 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
```
I use parallel desktop pro 19 (with Rosetta activated)

The latest version of docker is installed:
```bash
docker --version
Docker version 25.0.2, build 29cf629
```

<details>

<summary>docker info</summary> 

```bash
docker info
Client: Docker Engine - Community
 Version:    25.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.5
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 8
 Server Version: 25.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-92-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 19.03GiB
 Name: ubuntu-linux-22-04-02-desktop
 ID: 16015445-fbfd-4f60-b143-ee162fca1ffe
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

</details>

It seems that I am encountering exactly the same issue as described in https://github.com/docker/for-mac/issues/6998. Only one CPU is used, and this goes on indefinitely. I do not have this problem when I don't use Rosetta.
 
For reproduce like explained [here](https://github.com/jbinto/rosetta-what), just run:
```bash
docker run --platform linux/amd64 jbinto/rosetta-what
```

<img width="679" alt="Screenshot 2024-02-06 at 15 02 26" src="https://github.com/docker/for-linux/assets/5569193/2c62464d-2ede-491b-8545-95e61d263d72">

`docker stats <name>`
<img width="1052" alt="Screenshot 2024-02-06 at 15 01 58" src="https://github.com/docker/for-linux/assets/5569193/1c2cf06f-0616-4e19-af85-eea3941a1205">

**Comment by thaJeztah** [comment] 2024-06-17 12:23
closing as duplicate of https://github.com/docker/for-mac/issues/6998 and https://github.com/moby/moby/issues/47351

**Closed as not planned by thaJeztah** 2024-06-17 12:23 UTC
