### ISSUE TITLE
ERROR - Cannot unmarshal array into Go struct field

### ISSUE THREAD

**Issue by jeanaugustoos** [docker/for-linux#61] opened 2017-07-16 21:28 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

I'm having the follow error when running the command `docker run hello-world` on Antergos Linux. The steps to reproduce this issue are:
1. Install docker `sudo pacman -S docker`
2. Add docker to the user group `sudo usermod -aG docker ${user}`

### Expected behavior
```
$ docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
...(snipped)...
```

### Actual behavior
```
$ docker run hello-world
docker: Error response from daemon: shim error: json: cannot unmarshal array into Go struct field processState.capabilities of type specs.LinuxCapabilities.
ERRO[0001] error getting events from daemon: context canceled 
```

### Steps to reproduce the behavior

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.29 (downgraded from 1.30)
 Go version:   go1.8.3
 Git commit:   3dfb8343
 Built:        Sat Jul  8 20:56:41 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.8.1
 Git commit:   89658bed64
 Built:        Fri May  5 22:40:58 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 12
 Running: 0
 Paused: 0
 Stopped: 12
Images: 1
Server Version: 17.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: 
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4 (expected: 9c2d8d184e5da67c95d601382adf14862e4f2228)
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.11.9-1-ARCH
Operating System: Antergos Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.762GiB
Name: unnamed
ID: "REDACTED"
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by CuBiC3D** [comment] 2017-07-17 06:38
Same here on Arch and Docker 17.06.0-ce. Related to #49?

**Comment by dmfay** [comment] 2017-07-18 13:30
On Arch I was able to start using Docker again by stopping `docker.service`, reloading daemons, and starting `docker.service`. If you don't have anything you absolutely need to keep running give that a shot.

**Comment by thaJeztah** [comment] 2017-07-18 13:42
There are no official packages for Arch Linux; the version of Docker you're running on Arch linux is not maintained here.

The problem here is that the Arch package ships the wrong version of RunC, which is incompatible with Docker 17.06; see the output of `docker info` (Possibly other changes on configuration that may affect docker);

```
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4 (expected: 9c2d8d184e5da67c95d601382adf14862e4f2228)
```

I recommend opening an issue with the Arch linux packagers

I'm closing this issue because there's nothing that can be done here, but feel free to continue the conversation

**Closed by thaJeztah** 2017-07-18 13:42 UTC

**Comment by mimoralea** [comment] 2017-07-24 03:40
I had the same issue. A `sudo systemctl daemon-reload && sudo systemctl restart docker` fixed it.

**Comment by loretoparisi** [comment] 2019-10-07 14:22
I get this error for this configuration

```json
{
    "runtimes": {
        "default-runtime": "nvidia",
        "nvidia": {
            "path": "nvidia-container-runtime",
            "runtimeArgs": []
        }
    }
}
```

It turns out the `default-runtime` does not work in docker 18.
@thaJeztah any replacement as the default gpu runtime?

**Comment by thaJeztah** [comment] 2019-10-07 14:25
@loretoparisi what version of docker (18 is ambiguous, as Docker uses `YY.MM` formatting for the versions)

**Comment by loretoparisi** [comment] 2019-10-07 17:24
I'm using 
```
loreto@reddragon:~$ dockerd --version
Docker version 18.09.7, build 2d0083d
```

on Ubuntu 18.04

**Comment by gecailong** [comment] 2020-06-01 07:37
my docker version: 1.13.1
my os version:centos 7.4
But I can't run my mirror
it's err:
container_linux.go:247: starting container process caused "process_linux.go:337: running prestart hook 1 caused \"error running hook: exit status 1, stdout: , stderr: could not decode OCI spec: json: cannot unmarshal array into Go struct field Process.process.capabilities of type main.LinuxCapabilities\\n\""
/usr/bin/docker-current: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:337: running prestart hook 1 caused \"error running hook: exit status 1, stdout: , stderr: could not decode OCI spec: json: cannot unmarshal array into Go struct field Process.process.capabilities of type main.LinuxCapabilities\\n\"".
ERRO[0000] error getting events from daemon: net/http: request canceled

it's kerner version: 3.10.0-1127.8.2.el7.x86_64
How can I solve this problem

**Comment by smogsy** [comment] 2020-06-02 07:20
@gecailong 
we have the same issue
CentOS 7.7
docker 1.13.1
i created this https://github.com/NVIDIA/nvidia-container-runtime/issues/105

**Comment by thaJeztah** [comment] 2020-06-02 08:06
Docker 1.13 reached EOL in 2017; if you're running Docker 1.13.1 you may be running the Red Hat fork of Docker, which has many modifications that are not in the upstream Docker source code, and may be the cause of these errors ("running prestart hook 1" sounds like it may be one of the modifications they made with "hooks").

Are you able to reproduce the issue with an official build of a current version (19.03.x at time of writing) of Docker? https://docs.docker.com/engine/install/centos/)

**Comment by smogsy** [comment] 2020-06-02 16:03
@thaJeztah  please see updates notes in attached bug report

Seem redhat uses runc-1.0.0-dev which breaks after Nvidiacontainer-toolkit 1.10 
Due to not meeting OCI spec

**Comment by Davidrjx** [comment] 2020-07-08 06:06
at debian 10, upgrade docker-ce from 17.03 to 18.09, problem still exists, why?

**Comment by Davidrjx** [comment] 2020-07-08 06:09
it works by https://github.com/docker/for-linux/issues/61#issuecomment-539036016
