### ISSUE TITLE
iptables break after every system reboot

### ISSUE THREAD

**Issue by ghost** [docker/for-linux#1469] opened 2023-06-25 12:57 UTC
I'm running docker on my home server to host a bunch of containers but once the service starts and the docker container adds their own iptables rules, the home server stops being able to handle network packets from other devices in my local network. I use my home server as gateway for certain IPs so that traffic heading to certain addresses goes through my home server first.

When running `tracert.exe` from my desktop I can see the packets heading to my home server but after that the connection times out and no more information is provided on the state of the packets. The only way I found to fix the problem is stopping the docker service, completely wiping the content of iptables like [so](https://serverfault.com/a/200658) and then activating the docker service back making docker and its container readd their own rules to iptables. The very same rules, mind you. For some reason these three steps are needed every time I reboot my home server and I am not sure if this is an issue with docker itself or with my version of iptables.

Any idea of what could be the problem?

```bash
user@thinkcentre:~$ sudo iptables -V
[sudo] password for user:
iptables v1.8.9 (nf_tables)

user@thinkcentre:~$ docker version
Client: Docker Engine - Community
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:52:07 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:52:07 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by thaJeztah** [comment] 2023-06-29 09:05
This is probably expected behavior. iptables itself does not automatically restore rules that were added, and it's the responsibility of the tools that created those rules to re-create them. For the docker engine itself, docker will re-create iptables  rules it set up for containers when it starts, but it won't know about iptables rules set by containers (or any other process on the machine).

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- the [Docker community Slack channel](https://dockr.ly/comm-slack)
- the `docker` tags on [StackOverflow](https://stackoverflow.com/questions/tagged/docker*)
- the "Discussions" on the Moby repository - https://github.com/moby/moby/discussions
- the Docker Support Forums - https://forums.docker.com

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed as not planned by thaJeztah** 2023-06-29 09:05 UTC
