### ISSUE TITLE
docker run's --platform option is ignored if the image already exists locally

### ISSUE THREAD

**Issue by sdelafond** [docker/for-linux#1144] opened 2020-11-11 09:54 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

`docker run`'s `--platform` option consistenly uses the platform
passed by the user.

### Actual behavior

Regardeless of the plaform passed by the user, the only one actually
being used is the one downloaded during the first `docker pull`.

### Steps to reproduce the behavior

On an `amd64` host, if I remove, manually pull, and then run a specific
alpine image, I can only run `amd64` (while I expect the second `docker
run` call to return `aarch64` instead):

```
$ docker rmi alpine:3.12.1
Untagged: [...]
$ docker pull alpine:3.12.1
[...]
$ docker run --platform linux/amd64 alpine:3.12.1 uname -m
x86_64
$ docker run --platform linux/arm64/v8 alpine:3.12.1 uname -m
x86_64
```

If I Remove the image, and try running `arm64` directly (letting docker
pull the image itself), I get the expected `aarch64` but then passing
`--platform linux/amd64` has no effect anymore:

```
$ docker rmi alpine:3.12.1
Untagged: [...]
$ docker run --rm --platform linux/arm64/v8 alpine:3.12.1 uname -m
Unable to find image 'alpine:3.12.1' locally
3.12.1: Pulling from library/alpine
[...]
aarch64
$  docker run --rm --platform linux/amd64 alpine:3.12.1 uname -m
aarch64
```

If I handpick the hashes from `docker buildx imagetools inspect alpine:3.12.1`,
I can run either arch just fine:

```
$ docker run --rm docker.io/library/alpine:3.12.1@sha256:d7342993700f8cd7aba8496c2d0e57be0666e80b4c441925fc6f9361fa81d10e uname -m
x86_64
$ docker run --rm docker.io/library/alpine:3.12.1@sha256:fbb820c07896f5c2516167e7146d9938fc82d4b6b1db167defa5b0a7162e4480 uname -m
aarch64
```

**Output of `docker version`:**

```
Docker version 19.03.12, build 48a66213fe
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.3.1-tp-docker)
  app: Docker Application (Docker Inc., v0.8.0)

Server:
 Containers: 249
  Running: 7
  Paused: 0
  Stopped: 242
 Images: 570
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.9.0-1-amd64
 Operating System: Debian GNU/Linux bullseye/sid
 OSType: linux
 Architecture: x86_64
 CPUs: 36
 Total Memory: 31.05GiB
 Name: testbench-001
 ID: CULK:2KJY:HBBJ:4EIF:MGUG:IC2N:6PZ6:54AC:PPPQ:6Q3A:MKRX:OZF5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: sdelafond
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

This is on a physical machine, running Debian sid, and using the
docker-ce packages from the official repository at
https://download.docker.com/linux/debian.

**Comment by Habbie** [comment] 2020-11-11 09:57
Same behaviour confirmed with `5:19.03.13~3-0~debian-buster` on Debian Buster.

**Comment by Habbie** [comment] 2020-12-02 12:00
And in `5:19.03.14~3-0~debian-buster` :)

**Comment by Habbie** [comment] 2021-01-26 13:27
But, it works in `5:20.10.2~3-0~debian-buster` !

via https://docs.docker.com/engine/release-notes/, it looks like this was fixed in https://github.com/moby/moby/pull/40629

**Comment by thaJeztah** [comment] 2021-01-26 16:24
Ah, yes, this should be fixed in docker 20.10 👍

**Closed by thaJeztah** 2021-01-26 16:24 UTC

**Comment by brianjbeach** [comment] 2022-01-05 12:16
I continue to see this behavior in **Docker version 20.10.7, build f0df350**. 

I am trying to build an image for a Raspberry Pi (arm32) on an AWS/EC2 Graviton instance (arm64) based on Alpine. My build command looks like this.

```docker build --platform=linux/arm/v7 .```

This works as expected on a fresh EC2 instance, and the image runs on the Raspberry Pi. However, if I have previously used an **linux/arm64/v8** image (the default for Graviton) on the EC2 instance, the platform flag is ignored and I am left with a v8 image. Deleting the local Alpine image before the build fixes the problem. A little more detail is available [here](https://blog.brianbeach.com/posts/2022-01-04-aws-codebuild-rpi-docker-image/).

**Comment by thaJeztah** [comment] 2022-01-05 16:12
@brianjbeach I think that may be a limitation of the classic builder, which (IIRC) won't check the image, unless `--pull` is specified. I see the fix related to this ticket was for BuildKit only (https://github.com/moby/moby/pull/40629). Possibly could be the issue described in https://github.com/moby/moby/issues/40655

Does it work if you enable buildkit? (`export DOCKER_BUILDKIT=1`). With BuildKit enabled, this looks to be working ok;

```bash
echo "FROM alpine" | docker build -t foo --platform=linux/arm/v8 -
docker inspect --format='{{.Os}}/{{.Architecture}}/{{.Variant}}' foo
linux/arm/v8

echo "FROM alpine" | docker build -t foo --platform=linux/arm/v7 -
docker inspect --format='{{.Os}}/{{.Architecture}}/{{.Variant}}' foo
linux/arm/v7

echo "FROM alpine" | docker build -t foo --platform=linux/amd64 -
docker inspect --format='{{.Os}}/{{.Architecture}}/{{.Variant}}' foo
linux/amd64/
```


With BuildKit disabled, it does not check the platform until a `RUN` line is executed (which starts a container). I guess the issue there is that the initial `FROM` does not hit the `container create` code;

```bash
echo -e "FROM alpine" | DOCKER_BUILDKIT=0 docker build -t foo --platform=linux/arm/v8 -

Sending build context to Docker daemon  2.048kB
Step 1/1 : FROM alpine
 ---> 78571b13081b
Successfully built 78571b13081b
Successfully tagged foo:latest

docker inspect --format='{{.Os}}/{{.Architecture}}/{{.Variant}}' foo
linux/arm/v7
```

Adding a `RUN` to the dockerfile shows the platform mismatch;

```bash
echo -e "FROM alpine\nRUN echo hello" | DOCKER_BUILDKIT=0 docker build -t foo --platform=linux/arm/v8 -

Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM alpine
 ---> 78571b13081b
Step 2/2 : RUN echo hello
 ---> [Warning] The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/amd64) and no specific platform was requested
 ---> Running in 56a1b6390e49
hello
Removing intermediate container 56a1b6390e49
 ---> f566c4133e0d
Successfully built f566c4133e0d
Successfully tagged foo:latest
```
