### ISSUE TITLE
Docker uses a different binding directory than the one defined in the container after renaming folder

### ISSUE THREAD

**Issue by sowdiomyero** [docker/for-linux#147] opened 2017-10-31 16:24 UTC
Actions followed:
The binding directory is `/datas/atlassian/jira/home`
1- creating a mount point: `/new_data`
2- copy the contents of `/datas` in `/new_data`
3- rename `/datas` en `/datas_sav`
4- Mount `/new_datas`
5- rename `/new_data/` -> `/datas/`

All these actions were done without stopping docker or restarting the server.

Docker continues to work and when inspecting the container, the connection point remains on `/datas/ atlassian/jira/home` but in fact docker no longer writes on this directory but on `/datas_sav/atlassian/jira/home`.

Is this behavior normal? Why did not docker get notified when the `/datas/***` directory disappeared before renaming `/new_data/**` to `/datas/**`?

**Additional environment details (AWS, VirtualBox, physical, etc.)**

Serveur version : 
```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.2 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Red Hat Enterprise Linux"
REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_SUPPORT_PRODUCT_VERSION="7.2"
Red Hat Enterprise Linux Server release 7.2 (Maipo)
Red Hat Enterprise Linux Server release 7.2 (Maipo)
```

Docker version : 

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by thaJeztah** [comment] 2017-10-31 16:51
This is the expected behaviour, and due to the way mounts work on Linux; when bind mounting a directory (or file), the mount point is tied to the _inode_, not the file name, so when changing / moving the mount point, the mount will still use the same inode (which can also be troublesome when bind-mounting single files and editing them; see [Mount a host file as a data volume](https://docs.docker.com/v17.03/engine/tutorials/dockervolumes/#mount-a-host-file-as-a-data-volume).

The discussion on https://github.com/moby/moby/issues/12317, and https://github.com/moby/moby/issues/14890 may be of interest as well (that kernel issue has been fixed)

> Is this behavior normal? Why did not docker get notified when the /datas/*** directory disappeared before renaming /new_data/** to /datas/**?

Docker does not monitor the filesystem for changes, nor does it update container-definitions once the container is started, so it's expected that `docker inspect <container>` still shows the old information.


I'm closing this issue, because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-10-31 16:51 UTC
