### ISSUE TITLE
Debian 10 Buster has wrong repositories?

### ISSUE THREAD

**Issue by xorinzor** [docker/for-linux#1036] opened 2020-06-07 11:46 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

Created a docker container using `debian:10`, I'd expect the `buster` package repositories to be used

### Actual behavior

The debian `stretch` package repositories are used

**Comment by thaJeztah** [comment] 2020-06-08 14:28
There's not much information in your report. I tried installing docker using  the script at https://get.docker.com, and after installation I see the correct packages being used, and the correct repository being set up;

```
cat /etc/apt/sources.list.d/docker.list
deb [arch=amd64] https://download.docker.com/linux/debian buster stable
```

I'll close this issue because there's no steps to reproduce the problem in your report, but feel free to continue the conversation

**Closed by thaJeztah** 2020-06-08 14:28 UTC

**Comment by xorinzor** [comment] 2020-06-08 16:33
Odd. I didn't add any steps because I didn't do much else then have `FROM debian:10` in my dockerfile.

This was built using Dockerstation on Docker for Windows. I can't imagine this should make any difference in what sources.list it contains, but for me it only contains the `stretch` repositories.

**Comment by thaJeztah** [comment] 2020-06-08 17:11
I'm not familiar with Dockerstation, so can't tell
