### ISSUE TITLE
Docker start: "container already exists" 

### ISSUE THREAD

**Issue by TidyHuang** [docker/for-linux#809] opened 2019-10-09 09:49 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
docker start ids to start a container 

### Actual behavior
Error response from daemon: OCI runtime create failed: container with id exists: 521c55b1e6f463aabdce32d1478fbcfd21a41d0a4573534725abbe41437eda88: unknown

### Steps to reproduce the behavior
1. docker is installed Debian system
2. start docker container successfully
3. stop docker container 
4. restart docker again

**Output of `docker version`:**
```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:25:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Output of `docker info`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:25:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false
root@SMARTTSW-G1-1:/opt/xvip/bin# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 18.06.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Kernel Version: 3.16.56-OpenNetworkLinux
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 15.51GiB
Name: SMARTTSW-G1-1.EU6
ID: CEO4:TMEN:3GXH:CDWC:FCYH:OIHU:I3ZW:HFOJ:ZABU:W3MT:5BBY:E6PC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by cpuguy83** [comment] 2019-10-09 13:30
This should be fixed in newer versions already.
This was caused by a combination of mishandling the error and assuming user error when really the error needed to be dealt with internally.

**Closed by cpuguy83** 2019-10-09 13:30 UTC

**Comment by dionathanCordova** [comment] 2019-11-14 15:33
Its simple to solve, just remove all container and images, so build that again.

**Comment by celesteking** [comment] 2020-01-06 13:22
> This should be fixed in newer versions already.

It wasn't. 19.03.5 with exact same error after upgrade from 18.

**Comment by cpuguy83** [comment] 2020-01-06 14:37
@celesteking Then please open a new issue with all the relevant details.

**Comment by celesteking** [comment] 2020-01-06 15:30
It appears that killing `runc` process fixed it, but I'm not sure as I had issued `docker rm` and the container is now completely gone.

**Comment by Anon0ne** [comment] 2020-02-24 14:46
I am having this error when the Proxmox VM is rebooted. It has happened to a few different docker containers also, not just one.
OCI runtime create failed: container with id exists: containeridhere: unknown

I am unsure if another reboot will repair it, because I don't want to have to reboot all the time. I had to duplicate/edit and rename the container; then it started. I believe this happened for a LetsEncrypt and a Sonarr container for me.

**Comment by yechiel-optimalq** [comment] 2020-05-19 10:19
> This should be fixed in newer versions already.
> This was caused by a combination of mishandling the error and assuming user error when really the error needed to be dealt with internally.

This reproduced for me on 19.03.08


Client:
 Debug Mode: false

Server:
 Containers: 228
  Running: 228
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.0-1020-azure
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.59GiB
 Name: porky-sensors-2
 ID: RQJD:7ZKW:YLDY:QCHP:MMHB:2X2S:RIUD:AVV6:OH74:C7D6:2VOX:UJU6
 Docker Root Dir: /sensors/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support



After server restart, some containers unable to start (they have restart policy always)

**Comment by TheLat** [comment] 2020-06-17 22:31
@cpuguy83, this error appears to not be resolved.

**Comment by rphanikrishna** [comment] 2020-06-29 15:59
check this blog it solved my issue 
https://ahmetozer.org/Error-response-from-daemon-OCI-runtime-create-failed-container-with-id-exists.html

**Comment by hernandanielg** [comment] 2020-07-08 00:13
Yeah it's true, that blog solved my issue as well
https://ahmetozer.org/Error-response-from-daemon-OCI-runtime-create-failed-container-with-id-exists.html

**Comment by sagar-srivastava** [comment] 2020-08-05 02:53
this blog did not solve my issue, same exact error. my docker version 19.03.12

**Comment by LM1LC3N7** [comment] 2021-01-28 13:27
Hello all,

I have the same issue, and the "fix" described here is not solving the issue permanently:
https://ahmetozer.org/Error-response-from-daemon-OCI-runtime-create-failed-container-with-id-exists.html

After a clean reboot (`reboot now`), none of my containers are restarting. They all fails, unless I remove the `/var/run/docker/runtime-runc/moby` folder that contains container `runtime`.

This is a real issue here, and we are a lot to encounter this bug. Why nothing seems to be done since few years about this specific error?

- OS: CentOS Linux release 8.3.2011
- Docker version: Docker version 20.10.2, build 2291f61

<details><summary>Docker info</summary>

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 11
  Running: 0
  Paused: 0
  Stopped: 11
 Images: 47
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  selinux
  userns
 Kernel Version: 4.18.0-240.10.1.el8_3.x86_64
 Operating System: CentOS Linux 8
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 62.5GiB
 Name: thor
 ID: W4VL:SZ2V:NL7G:YSWL:NXMX:RJJ5:DWF7:5A65:WPDN:PLNG:6UPH:SD6R
 Docker Root Dir: /data/docker/lib/231072.231072
 Debug Mode: true
  File Descriptors: 24
  Goroutines: 33
  System Time: 2021-01-28T14:16:00.5527765+01:00
  EventsListeners: 0
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true

WARNING: No blkio weight support
WARNING: No blkio weight_device support

```
</details>

There is others issues for the exact same error: https://github.com/docker/for-linux/issues/241

**Comment by LM1LC3N7** [comment] 2021-01-28 13:31
Also here: https://github.com/docker/for-linux/issues/49
and here: https://github.com/containerd/containerd/issues/4133
and here: https://github.com/containerd/containerd/issues/4326

**Comment by thaJeztah** [comment] 2021-01-28 22:55
^^ /cc @AkihiroSuda @cpuguy83

**Comment by cpuguy83** [comment] 2021-01-28 22:59
If you rebooted and that data is still there, then the host is not configured properly.
`/var/run` is expected to be a tmpfs.

**Comment by thaJeztah** [comment] 2021-01-28 23:01
Ah, good one, yes.

**Comment by LM1LC3N7** [comment] 2021-01-29 06:12
In `/etc/fstab`, there is nothing about `/var/run`. 
But it is a tmpfs filesystem: 

```bash
$ df -h /var/run
Sys. de fichiers Taille Utilisé Dispo Uti% Monté sur
tmpfs               32G    1,4M   32G   1% /run
```
But if I understand correctly, this should be automatically deleted on each reboot, which is not in my case as the path is still accessible.

**Comment by cpuguy83** [comment] 2021-01-29 17:24
Right, there should not be any data in a tmpfs after reboot, which would easily cause issues for containerd/runc.

**Comment by LM1LC3N7** [comment] 2021-01-30 18:45
Thank you very much for these details, I now understand 🙂 
Docker should check and delete these files after a reboot, no?

**Comment by cpuguy83** [comment] 2021-01-30 18:48
There is no way for Docker to know a reboot occurred or if it is correct to delete the files.

**Comment by LM1LC3N7** [comment] 2021-01-30 19:10
It could check the up time when the service starts? 
If the folder is deleted during containers execution, what could happen?

**Comment by cpuguy83** [comment] 2021-01-30 19:12
We can't just delete the files.
If a container is running it will be cleaned up on restart (except for live restore).

This is why it must be on a tmpfs. The files are intended to be cleaned up on reboot since processes aren't running on reboot.

What will happen is we lose track of state of the containers.

**Comment by 303linuxgroup** [comment] 2021-11-25 08:09
@cpuguy83  If I don’t want to reboot and just want to update the docker image version, do I need to clear /var/run/docker?

**Comment by DawnEve** [comment] 2024-09-25 08:50
I see the same error on my CentOS7, after a forced `service docker restart`:

```
$ docker --version
Docker version 26.1.0, build 9714adc


$ docker start 16b
Error response from daemon: failed to create task for container: task 16b4479c19daeac62f66a17efa326c12949e8a78f953017b7033757938b7be3e: already exists
Error: failed to start containers: 16b
```

**Comment by pirelle** [comment] 2025-01-13 17:29
I had container in `docker ps -a`. I've removed it and then run without issues
