### ISSUE TITLE
How to turn off the log color mark output by stdout？

### ISSUE THREAD

**Issue by wajika** [docker/for-linux#1324] opened 2021-11-10 02:12 UTC
I used filebeat to collect the logs output by container stdout, but why are the logs marked with colors? This makes the log structure very messy, is there any way to turn off the color mark?
![微信截图_20211109161600](https://user-images.githubusercontent.com/17058349/141036946-84d64aeb-c04e-4730-9376-4c832791d763.png)

**Comment by thaJeztah** [comment] 2021-11-10 09:03
These logs look to be generated by the process inside the container you're running, and that process (elasticsearch?) uses colors for the logs (docker does not add these colours).

I'm not familiar with the configuration options for elastic search, but It's possible that the output depends on whether or not the container was started with a TTY attached (e.g. `docker run -t .....`); a quick google search brought me to https://www.elastic.co/guide/en/elasticsearch/reference/current/logging.html, which mentions that elastic uses Log4J for logging, which has it's own options for highlighting (also see https://stackoverflow.com/questions/23067826/how-to-disable-ansi-escape-color-logging-in-log4j2, but you may want to do some more searching)

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the [Docker community Slack channel](http://dockr.ly/slack)
- the Docker Support Forums - https://forums.docker.com
- the `docker` tags on [StackOverflow](https://stackoverflow.com/questions/tagged/docker*)

I'm closing this issue because this is not a bug, but feel free to continue the conversation; I'd also recommend asking in a I elasitcsearch support forum.

**Closed by thaJeztah** 2021-11-10 09:03 UTC

**Comment by wajika** [comment] 2021-11-10 14:21
Thank you for your reply. I probably found the direction
