### ISSUE TITLE
Docker unmounts ZFS subvolumes

### ISSUE THREAD

**Issue by LinAGKar** [docker/for-linux#1470] opened 2023-07-25 20:23 UTC
I am running Docker on OpenSUSE Leap 15.4 with /var/lib/docker on a zfs volume, with some directories in my Docker volumes on ZFS subvolumes (so I can apply separate options for them, and take snapshots). However, after updating from Docker 20.10.23 to 23.0.6, it unmounts all subvolumes in the Docker volumes soon after it starts, making the containers fail to run (and the PostgreSQL databases broke and required restoring from backup).

**Comment by devZer0** [comment] 2023-08-19 00:04
looks similar

https://zfsonlinux.topicbox.com/groups/zfs-discuss/Tbcf2c1775171c991/zfs-filesystem-suddenly-unmounted

https://forums.docker.com/t/zfs-pool-suddenly-unmounted-by-docker-maybe/137325/1

**Comment by thaJeztah** [comment] 2023-09-17 15:18
This looks to be a duplicate of https://github.com/moby/moby/issues/46148


And this should be fixed through;

- https://github.com/moby/moby/issues/46148
- https://github.com/moby/moby/pull/46367
- https://github.com/moby/moby/pull/46366

**Closed as completed by thaJeztah** 2023-09-17 15:18 UTC
