### ISSUE TITLE
Can't retrieve file under /proc which bind to host's /proc

### ISSUE THREAD

**Issue by jerry-yuan** [docker/for-linux#997] opened 2020-05-11 15:54 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
```
$ docker run -d -v /proc:/proc ubuntu sh -c "while true; do sleep 1; done"   # just make a container
$ docker cp<containerId>:/proc/stat ./
$ cat ./stat
# I got the contents of /proc/stat
```
### Actual behavior
```
$ docker run -d -v /proc:/proc ubuntu sh -c "while true; do sleep 1; done"   # just make a container
$ docker cp<containerId>:/proc/stat ./
$ cat ./stat
# I got nothing
```

### Steps to reproduce the behavior
1. start a new container with /proc binding
`docker run -d -v /proc:/proc ubuntu sh -c "while true; do sleep 1; done"`
2. attach to the container and make sure that the file `/proc/stat` has content
```
$ docker exec <containerId> cat /proc/stat
$ # I got the contents of /proc/stat the same as host

$ docker exec <containerId> /bin/bash
$ cat /proc/stat
$ # I got the contents of /proc/stat the same as host
```
3. try to retrive `/proc/stat` by `docker cp`
```
$ docker cp<containerId>:/proc/stat ./
$ cat ./stat
# I got an empty file and there is nothing to output.
```
**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:55 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:23 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.0-51-generic
 Operating System: Ubuntu 19.10
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.59GiB
 Name: *******
 ID: M**Z:F**4:5**V:E**O:K**U:F**X:Q**R:Q**O:H**B:E**P:H**Y:2**L
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  172.*.*.190
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: API is accessible on http://0.0.0.0:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by jerry-yuan** [comment] 2020-05-11 15:56
I am making a project needs to read some hardware information while I have no access with ssh or other way except an exposed Docker API.

**Comment by thaJeztah** [comment] 2020-05-27 13:10
Don't think that would work with `docker cp`, but you could try just piping the output to a file;

```
docker run --rm -v /proc:/proc alpine sh -c 'cat /proc/stat' > ./stat
```


Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2020-05-27 13:10 UTC
