### ISSUE TITLE
Error while starting Docker: Perhaps iptables or your kernel needs to be upgraded.

### ISSUE THREAD

**Issue by lyc8503** [docker/for-linux#1070] opened 2020-07-19 11:28 UTC
* [x] This is a bug report
* [x] I searched existing issues before opening this one

### Expected behavior
Docker starts normally.

### Actual behavior
Docker failed to start with a non-zero exit code.

### Steps to reproduce the behavior

Just install docker and run "systemctl start docker".

**Output of `docker version`:**

```
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:39:04 2019
 OS/Arch:           linux/arm
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
I'm using a linux machine with a custom kernel. 
I tried to use the check-config.sh script to check the environment and the output are as follows.
```
warning: /proc/config.gz does not exist, searching other paths for kernel config ...
error: cannot find kernel config
  try running this script again, specifying the kernel config:
    CONFIG=/path/to/kernel/.config ./check-config.sh or ./check-config.sh /path/to/kernel/.config
```

The output of "journalctl -xe" are as follows:
```
Jul 19 11:24:28 aml dockerd[13056]: Error starting daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain 
Jul 19 11:24:28 aml dockerd[13056]: modprobe: FATAL: Module ip_tables not found in directory /lib/modules/5.3.8-aml-OC-BonusCloud
Jul 19 11:24:28 aml dockerd[13056]: iptables v1.6.0: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Jul 19 11:24:28 aml dockerd[13056]: Perhaps iptables or your kernel needs to be upgraded.
Jul 19 11:24:28 aml dockerd[13056]:  (exit status 3)
```

I guess my kernel might be missing the ip_tables module which prevents Docker from starting.
What can I do now?

**Comment by thaJeztah** [comment] 2020-07-21 21:39
I'd recommend checking the config script itself, and manually check that you have everything that it expects to be there.

Note that Docker 18.06 is really old and reached EOL two years ago, so consider using a more recent version.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2020-07-21 21:39 UTC

**Comment by skiwheelr** [comment] 2020-10-04 02:12
I have the same issue with 19.03. What could it be?

**Comment by lyc8503** [comment] 2020-10-04 02:15
> I have the same issue with 19.03. What could it be?

Maybe your kernel is missing some modules. You should try to recompile your kernel to meet all the requirements listed in the Docker's website.

In this case compiling a new kernel with iptables, namespaces and mqueue worked for me.
