### ISSUE TITLE
docker 18.03.1-ce network not working on Deepin 15.7 - socket permission denied

### ISSUE THREAD

**Issue by igormcoelho** [docker/for-linux#413] opened 2018-08-22 23:47 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior

docker should work normally and resolve domain `sudo docker run busybox nslookup google.com`.

### Actual behavior
Just upgraded Deepin 15.6 to 15.7, and networking stopped working inside docker-ce containers.
Simple error:
```
sudo docker run busybox nslookup google.com
nslookup: socket: Permission denied
```
Just reinstalled Deepin 15.7 from scratch, docker worked, but after reboot, it stopped working again. What can a reboot destroy in docker regarding networking?

Notice that I'm using `sudo` user, so I know that it's not related to permissions outside docker... Container hello-world works, only networking is affected.

### Steps to reproduce the behavior

Install deepin 15.7 and install docker-ce. It will work. After reboot, it won't work anymore.

**Output of `docker version`:**

`Docker version 18.03.1-ce, build 9ee9f40`

**Output of `docker info`:**

```
sudo docker info
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 2
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.15.0-29deepin-generic
Operating System: Deepin 15
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.6GiB
Name: imcoelho-PC
ID: DVSK:UAHR:7JSF:SM6T:E6YQ:5X7T:HWLG:DQLH:N5P3:NQHG:ZDTI:Z74Z
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by igormcoelho** [comment] 2018-08-23 20:09
Ok, just reformatted my system 5 times, still having problems with Deepin 15.7, but also Deepin 15.6 (weird). Just noticed strange things in my `dmesg | tail`:
```
imcoelho@imcoelho-PC:~$ dmesg | tail
[   82.688243] audit: type=1400 audit(1535054819.722:220): apparmor="DENIED" operation="create" profile="/usr/lib/ipsec/charon" pid=4436 comm="charon" family="unix" sock_type="dgram" protocol=0 requested_mask="create" denied_mask="create" addr=none
[   82.690097] audit: type=1400 audit(1535054819.722:221): apparmor="DENIED" operation="create" profile="/usr/lib/ipsec/charon" pid=4436 comm="charon" family="netlink" sock_type="raw" protocol=6 requested_mask="create" denied_mask="create"
[   82.690113] audit: type=1400 audit(1535054819.722:222): apparmor="DENIED" operation="create" profile="/usr/lib/ipsec/charon" pid=4436 comm="charon" family="unix" sock_type="dgram" protocol=0 requested_mask="create" denied_mask="create" addr=none
[   82.690131] audit: type=1400 audit(1535054819.722:223): apparmor="DENIED" operation="create" profile="/usr/lib/ipsec/charon" pid=4436 comm="charon" family="inet6" sock_type="dgram" protocol=17 requested_mask="create" denied_mask="create"
[   82.690140] audit: type=1400 audit(1535054819.722:224): apparmor="DENIED" operation="create" profile="/usr/lib/ipsec/charon" pid=4436 comm="charon" family="unix" sock_type="dgram" protocol=0 requested_mask="create" denied_mask="create" addr=none
[   82.690148] audit: type=1400 audit(1535054819.722:225): apparmor="DENIED" operation="create" profile="/usr/lib/ipsec/charon" pid=4436 comm="charon" family="unix" sock_type="dgram" protocol=0 requested_mask="create" denied_mask="create" addr=none
[   82.690153] audit: type=1400 audit(1535054819.722:226): apparmor="DENIED" operation="create" profile="/usr/lib/ipsec/charon" pid=4436 comm="charon" family="inet" sock_type="dgram" protocol=17 requested_mask="create" denied_mask="create"
[   82.690162] audit: type=1400 audit(1535054819.722:227): apparmor="DENIED" operation="create" profile="/usr/lib/ipsec/charon" pid=4436 comm="charon" family="unix" sock_type="dgram" protocol=0 requested_mask="create" denied_mask="create" addr=none
[   82.690169] audit: type=1400 audit(1535054819.722:228): apparmor="DENIED" operation="create" profile="/usr/lib/ipsec/charon" pid=4436 comm="charon" family="unix" sock_type="dgram" protocol=0 requested_mask="create" denied_mask="create" addr=none
[   82.690176] audit: type=1400 audit(1535054819.722:229): apparmor="DENIED" operation="create" profile="/usr/lib/ipsec/charon" pid=4436 comm="charon" family="unix" sock_type="dgram" protocol=0 requested_mask="create" denied_mask="create" addr=none
```
I guess app armor is limiting docker internet access:
```
sudo docker run busybox nslookup google.com
nslookup: socket: Permission denied
```
```
apt-cache madison apparmor
  apparmor |     2.12-4 | http://packages.deepin.com/deepin panda/main amd64 Packages
```

**Comment by eltoque** [comment] 2018-08-28 19:54
After install apparmor=2.12-4ubuntu5, still not working.

**Comment by igormcoelho** [comment] 2018-08-29 02:06
Did you check `dmesg`? I experimented many times, and all of them this solved the `apparmor="DENIED" ` problem. 
If it doesn't work, I recommend you to fully uninstall `apparmor` and docker... then reboot computer and verify that dmesg messages are gone. Reinstall docker (and apparmor) and make sure problem has arised... then install this specific version, reboot, and pray :)

**Comment by ratemyduck** [comment] 2018-08-29 12:43
This also hurts me. I can't even ping. In my case I get 
```
apparmor="ALLOWED" operation="recvmsg" profile="/usr/lib/ipsec/charon" pid=5364 comm="charon" family="netlink" sock_type="raw" protocol=0 requested_mask="receive" denied_mask="receive"
```
But ping still failes. So I tried disabling (`aa-disable /usr/lib/ipsec/charon`) but then I get 
```
apparmor="DENIED" operation="create" profile="docker-default" pid=5937 comm="ping" family="inet" sock_type="raw" protocol=1 requested_mask="create" denied_mask="create"
```

**Comment by chanble** [comment] 2018-09-03 04:09
I remove apparmor, it works

**Comment by Tset-Noitamotua** [comment] 2018-09-07 15:59
After messing around with apparmor for two days I got sick of it and removed it, too!

The solution of @igormcoelho  works but apart from that `apparmor` is just messy bullshit that gets in your way if you work with Qemu / KVM, docker, virtualbox etc.  ... holy crap! I don't even know what it is good for! so to hell with it!!!!!!!!!!!!!!!!!

**Comment by jodevan** [comment] 2018-09-09 21:36
I'm not sure, but I believe completely removing apparmor may not be a good idea, since this is an extra security layer for your OS, like SELinux, for instance.

There's a section in the Docker documentation: https://docs.docker.com/engine/security/apparmor/#resources-for-writing-profiles

**Comment by michalzubkowicz** [comment] 2018-09-29 08:29
Thanks @igormcoelho, you saved my day.

**Comment by thorix** [comment] 2018-10-18 22:09
I also had this same problem with Deepin. Dmesg was helpful in finding the root problem in my case:
```
Oct 18 13:37:09 laptop kernel: [ 2382.238285] bash[31781] vsyscall attempted with vsyscall=none ip:ffffffffff600400 cs:33 sp:7ffdb0310ba8 a
x:ffffffffff600400 si:7ffdb0312f7b di:0
```
With some more searching you will find Deepin don't have the same kernel config flags as Ubuntu:
grep -ir vsyscall /boot/config-4.16.0-2-amd64
```
CONFIG_GENERIC_TIME_VSYSCALL=y
CONFIG_X86_VSYSCALL_EMULATION=y
# CONFIG_LEGACY_VSYSCALL_EMULATE is not set
CONFIG_LEGACY_VSYSCALL_NONE=y
```

You will not have CONFIG_LEGACY_VSYSCALL_NONE=y set in ubuntu. So for Deepin users you will need to modify /etc/default/grub and add parameter vsyscall=emulate, then exec grub-mkconfig -o /boot/grub/grub.cfg to update.
```
GRUB_CMDLINE_LINUX_DEFAULT="vsyscall=emulate splash quiet"
```
You can see others that seem to know about this problem as well:
https://github.com/linuxdeepin/developer-center/issues/502#issuecomment-382308855

Here is where the Deepin changed 2 years ago https://github.com/linuxdeepin/deepin-kernel/commit/74f87b226a1267b837d98a5d46824f9b5629962e

**Comment by igormcoelho** [comment] 2018-10-19 00:52
I guess removing apparmor is not perfect solution, but it works for many, so I will close this issue. Thanks everyone :)

**Comment by michalzubkowicz** [comment] 2018-10-19 06:18
Really? Guys, don't do it. Removing AppArmor is not an any solution and it's a very bad idea, please reopen.

Ubuntu AppArmor rules are working, so something is wrong in Deepin package, which should be fixed.

**Comment by igormcoelho** [comment] 2018-10-19 10:05
ok :)

**Comment by nlaitan** [comment] 2018-10-28 22:32
since I delete apparmor the deepin updates fail and I could never do them again, someone with the same problem?

**Comment by igormcoelho** [comment] 2018-11-03 17:47
@nlaitan what worked for me is to not remove apparmor, but replace it:
> Ok, just confirmed it has been fixed by replacing package apparmor 2.12-4 with 2.12-4ubuntu5.
> Temporarially added deb http://br.archive.ubuntu.com/ubuntu bionic main to /etc/apt/sources.list, and > run these commands:
> sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 3B4FE6ACC0B21F32
> sudo apt update
> sudo apt install apparmor=2.12-4ubuntu5

**Comment by xiayuhai** [comment] 2018-11-12 06:09
"docker run --privileged" temporarily solved this problem.

**Comment by brenoprata10** [comment] 2018-11-23 12:36
> Ok, just confirmed it has been fixed by replacing package `apparmor 2.12-4` with `2.12-4ubuntu5`.
> Temporarially added `deb http://br.archive.ubuntu.com/ubuntu bionic main` to `/etc/apt/sources.list`, and run these commands:
> 
> ```
> sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 3B4FE6ACC0B21F32
> sudo apt update
> sudo apt install apparmor=2.12-4ubuntu5
> ```
> Important: remove `deb http://br.archive.ubuntu.com/ubuntu bionic main` from sources and lock the apparmor package. Now, it works :)
> 
> ```
> sudo docker run busybox nslookup google.com 
> Server:		192.168.1.1
> Address:	192.168.1.1:53
> 
> Non-authoritative answer:
> Name:	google.com
> Address: 216.58.222.78
> 
> *** Can't find google.com: No answer
> ```

This error ocurred to me because of apparmor as well, it happened because i had installed snapd one day before this issue, so deepin users, be aware of that o/

**Comment by andresilva96** [comment] 2019-04-19 22:45
Only disable

$ sudo mkdir -p /etc/default/grub.d
$ echo 'GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT apparmor=0"' \
  | sudo tee /etc/default/grub.d/apparmor.cfg
$ sudo update-grub
$ sudo reboot

**Comment by jlamasfripp** [comment] 2019-05-23 10:12
Guys, I love you so much right now... reinstalled apparmor and apparmor-profiles and evrithing works perfectly!
remove apparmor
install apparmor2.12-4ubuntu5 and apparmor-profiles_2.12-4ubuntu5_all 
reboot
I recomend do as @ratemyduck said, and all the thanks in the world to @igormcoelho for opening this.
Deepin 15.10 here. Be aware of this new stable update, it can be tricky to go back in track.

**Comment by wendreof** [comment] 2019-07-20 19:05
> I remove apparmor, it works

You saved my life too! Now my Postgres container is running smoothly again!

**Comment by entrealist** [comment] 2019-08-02 11:00
> I remove apparmor, it works

Deepin 15.11 copy that. Remove that fucking crap x2

**Comment by Tset-Noitamotua** [comment] 2019-08-12 22:15
# same shit - another year
## Deepin 15.11 / Docker 19.03.1

Got a new laptop, setting up all my stuff and guess where I end up. Running into the same bullshhh as almost one year ago (scroll up).

```
cat /etc/issue
Deepin GNU/Linux 15.11

uname -r
4.15.0-30deepin-generic

docker --version
Docker version 19.03.1, build 74b1e89
```

Strange thing is: after initial setup of docker everything worked. Not sure if it stopped working after reboot but as @brenoprata10 mentioned I also have installed snapd recently because I wanted to get an working version of `fwupd` to update my hardware's firmware.

I'll try removing/deactivating snapd  i see what happens ...

**Comment by Tset-Noitamotua** [comment] 2019-08-13 01:16
nope ...

apparmor == :shit::shit::shit: x1000 ... it eats your time, your battery ... your life!

## @Tset-Noitamotua :warning:: if u run into this :shit: again just do this:

```
sudo apt remove apparmor
reboot
```

**Comment by Tset-Noitamotua** [comment] 2019-08-15 07:22
1) Just did a fresh install of Deepin 15.10.1
2) Installed Docker 19.03.1
test 1: `docker run hello-word` - PASS :heavy_check_mark: 
test 2: `docker run busybox nslookup google.com` - PASS :heavy_check_mark: 

3) rebooted
test 1: `docker run hello-word` - PASS :heavy_check_mark: 
test 2: `docker run busybox nslookup google.com` - PASS :heavy_check_mark: 

4) checked apparmor status
    ```
    $ service apparmor status
    Unit apparmor.service could not be found.
    ```
    to find out it does not exist :scream: 
can't believe it, check again
    ```
    $ apt search apparmor
    Sorting... Done
    Full Text Search... Done
    apparmor/lion 2.11.0-3+deb9u2 amd64
      user-space parser utility for AppArmor

    ```
    it is not installed.
what else is there?
    ```
    apt search apparmor | grep installed
    libapparmor1/lion,now 2.11.0-3+deb9u2 amd64 [installed]
    ```
    ok, something is installed but seems not to be active daemon/service

### So it turns out AppArmor is not the bitch here at all? Was all the shhh caused by snap? Was apparmor installed and activated by snap?
I appologize for everything I said about AppArmor! Please forgive me :sob:

**Comment by mattzuba** [comment] 2019-08-29 04:57
> Was apparmor installed and activated by snap?

Yes

> apt show snapd | grep Depends    
> 
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> 
> Depends: adduser, apparmor (>= 2.10.95-0ubuntu2.2), ca-certificates, gnupg1 | gnupg, snap-confine (= 2.21-2+b1), squashfs-tools, systemd, ubuntu-core-launcher (= 2.21-2+b1), init-system-helpers (>= 1.18~), libc6 (>= 2.3.2)

**Comment by eduardotkoller** [comment] 2019-08-30 22:06
I was super frustrated searching for this problem and couldn't find anything. I stumbled upon this searching for something else, and it was the same story: all was working until it wasn't anymore, and I couldn't find the reason why. Suddenly, docker containers didn't have permission to bind to any IP address on the docker network. As @brenoprata10 said, this happened after I installed `snapd`, because of fucking `apparmor`. Removed it and it all started working again!

**Comment by rennanhm** [comment] 2019-09-05 04:40
you can create a new container apparmor profile

`sudo mkdir /etc/apparmor.d/containers/`

`sudo nano /etc/apparmor.d/containers/docker-default2`

define profile:
```
#include <tunables/global>

profile docker-default2 flags=(complain) {

}
```
`sudo apparmor_parser -r -W /etc/apparmor.d/containers/docker-default2`

`sudo docker run --security-opt "apparmor=docker-default2" busybox nslookup google.com`

`Server:		192.168.0.1
Address:	192.168.0.1:53

Non-authoritative answer:
Name:	google.com
Address: 216.58.202.142

*** Can't find google.com: No answer`

**Comment by Tset-Noitamotua** [comment] 2019-09-09 21:56
@rennanhm I had no luck with ur suggestion
```
sudo apparmor_parser -r -W /etc/apparmor.d/containers/docker-default2
apparmor_parser: Unable to replace "docker-default2".  Permission denied; attempted to load a profile while confined?
```

**Comment by martinblaha** [comment] 2019-10-05 20:33
If you're  running docker from command line, you can disable apparmor by using the `--security-opt apparmor=unconfined` option.

Source: https://cloud.google.com/container-optimized-os/docs/how-to/secure-apparmor?hl=de

```
$ docker run --security-opt apparmor=unconfined busybox nslookup google.com 
Server:		8.8.8.8
Address:	8.8.8.8:53

Non-authoritative answer:
Name:	google.com
Address: 216.58.201.78
```

**Comment by nelsonenzo** [comment] 2020-01-05 02:39
snapd installing apparmor was the problem I had as well.  Snaps do not seem to play well with deepin. removing apparmor fixed it.
```
sudo apt-get remove apparmor
sudo reboot
```

**Comment by essare** [comment] 2020-01-20 20:22
Removing apparmor is not a good idea !
try adding `--security-opt apparmor=unconfined` in your docker run command it will work ;-)
ex: `docker run --security-opt apparmor=unconfined ...`

**Comment by fcambria** [comment] 2020-02-09 03:02
> I remove apparmor, it works

Thanks!!!!!

**Comment by cocuba** [comment] 2020-02-22 20:44
> Ok, just confirmed it has been fixed by replacing package `apparmor 2.12-4` with `2.12-4ubuntu5`.
> Temporarially added `deb http://br.archive.ubuntu.com/ubuntu bionic main` to `/etc/apt/sources.list`, and run these commands:
> 
> ```
> sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 3B4FE6ACC0B21F32
> sudo apt update
> sudo apt install apparmor=2.12-4ubuntu5
> ```
> 
> Important: remove `deb http://br.archive.ubuntu.com/ubuntu bionic main` from sources and lock the apparmor package. Now, it works :)
> 
> ```
> sudo docker run busybox nslookup google.com 
> Server:		192.168.1.1
> Address:	192.168.1.1:53
> 
> Non-authoritative answer:
> Name:	google.com
> Address: 216.58.222.78
> 
> *** Can't find google.com: No answer
> ```

thanks, works but is important to mention, after do the install, reboot

**Comment by thaJeztah** [comment] 2020-05-29 12:54
From the discussion above, looks like this is an issue with the apparmor package on Deepin. Note that we don't officially  support that Linux distribution (things may work, but they're not tested, and we don't build packages for that platform). If this is still an issue, I see there's a tracking issue in the deepin issue tracker; https://github.com/linuxdeepin/developer-center/issues/684

**Closed by thaJeztah** 2020-05-29 12:54 UTC

**Comment by FlowerBirds** [comment] 2024-10-09 07:12
```
root@merit:~# docker version
Client: Docker Engine - Community
 Version:           23.0.5
 API version:       1.42
 Go version:        go1.19.8
 Git commit:        bc4487a
 Built:             Wed Apr 26 16:17:30 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.5
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.8
  Git commit:       94d3ad6
  Built:            Wed Apr 26 16:17:30 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
root@merit:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
root@merit:/etc/apparmor.d# apt-cache madison apparmor
  apparmor | 2.13.3-7ubuntu5.4 | http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
  apparmor | 2.13.3-7ubuntu5.4 | http://archive.ubuntu.com/ubuntu focal-security/main amd64 Packages
  apparmor | 2.13.3-7ubuntu5 | http://archive.ubuntu.com/ubuntu focal/main amd64 Packages

root@merit:/opt# docker run -it --rm alpine:3.6
/ # ip addr
ip: socket(AF_NETLINK,3,0): Permission denied
/ # exit

```
Unable to use network.
```
root@merit:/etc/apparmor.d# dmesg | tail
[15048.178876] audit: type=1400 audit(1728456949.461:14448): apparmor="DENIED" operation="create" profile="docker-default" pid=31127 comm="mysqld" family="unix" sock_type="stream" protocol=0 requested_mask="create" denied_mask="create" addr=none
[15048.181539] audit: type=1400 audit(1728456949.465:14449): apparmor="DENIED" operation="create" profile="docker-default" pid=31127 comm="mysqld" family="unix" sock_type="stream" protocol=0 requested_mask="create" denied_mask="create" addr=none
[15048.181639] audit: type=1400 audit(1728456949.465:14450): apparmor="DENIED" operation="create" profile="docker-default" pid=31127 comm="mysqld" family="unix" sock_type="stream" protocol=0 requested_mask="create" denied_mask="create" addr=none
[15048.181645] audit: type=1400 audit(1728456949.465:14451): apparmor="DENIED" operation="create" profile="docker-default" pid=31127 comm="mysqld" family="unix" sock_type="stream" protocol=0 requested_mask="create" denied_mask="create" addr=none
[15048.222481] audit: type=1400 audit(1728456949.505:14452): apparmor="DENIED" operation="create" profile="docker-default" pid=31134 comm="mysqld" family="unix" sock_type="stream" protocol=0 requested_mask="create" denied_mask="create" addr=none
[15051.789233] docker0: port 1(veth8601db3) entered disabled state
[15051.789683] vetheccd5e0: renamed from eth0
[15051.865038] docker0: port 1(veth8601db3) entered disabled state
[15051.872337] device veth8601db3 left promiscuous mode
[15051.872345] docker0: port 1(veth8601db3) entered disabled state

```
I remove apparmor, it works!!!
