### ISSUE TITLE
Redirecting website traffic to app container’s URL from Cpanel

### ISSUE THREAD

**Issue by Keepshango** [docker/for-linux#1446] opened 2023-01-26 18:09 UTC
**HOSTING SERVER DETAIL**
Machine : remote VPS
Server : Apache2.4
OS distro : Ubuntu 22.04 LTS
DB server : Mariadb

Hello,

I set a **website and database on host** (VPS) from using **ISPConfig panel**, and now wish to set a **redirection**, so to have the website **pointing to the app container on same host**. The website root initial directory is located at:

 /var/www/clients/client1/web1/web

**QUESTIONS**
Such a redirection can be set from within ISPConfig panel, so may someone tell me if my settings are correct ?
Should I replace the <container_name> with its ID, or change the path to have it pointing the docker image, or volume ? 

**Redirect Type:** ?
**Redirect Path:** /var/lib/docker/overlay2/<container_name> ?

**Above questions assume that :**
- Path to docker image, app container (e.g. tracim), and container volumes is var/lib/docker...,

- My VPS is networking with docker, and connecting app container, through the docker network IP ADDRESS assigned to it by default docker bridge network.   

- A “.env“ file was set and now contains the database environment variable to be passed to the app container

- I edited “docker run“ command line and completed with infos relating the “.env“ file

Regards

**Comment by f2ka07** [comment] 2023-04-01 05:21
Since you can create multiple containers on your VPS. Why do you just use Nginx proxy manager to point your IP addresses and also get SSL certificates for them. See this YouTube Video on [Nginx Proxy Manager using Docker Compose](https://www.youtube.com/watch?v=luVnhaE8HE0) .  Here is the free full course on [docker container management ](https://www.udemy.com/course/software-containerization-with-docker-virtualization/?referralCode=261CDF33EBDC0096BA3A).

**Comment by thaJeztah** [comment] 2023-06-29 08:47
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- the [Docker community Slack channel](https://dockr.ly/comm-slack)
- the `docker` tags on [StackOverflow](https://stackoverflow.com/questions/tagged/docker*)
- the "discussions" on the Moby repository (https://github.com/moby/moby/discussions)
- the Docker Support Forums - https://forums.docker.com

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed as not planned by thaJeztah** 2023-06-29 08:47 UTC
