### ISSUE TITLE
Would like to be able to run containers as LDAP/AD-user

### ISSUE THREAD

**Issue by olegblecher** [docker/for-linux#640] opened 2019-04-02 08:46 UTC
* [ ] This is a bug report
* [x] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
I expect to be able to run Docker containers as an AD-domain-joined user.

### Actual behavior
I get the following error:
`docker: Error response from daemon: linux spec user: unable to find user ${ADUSER}: no matching entries in passwd file`

### Steps to reproduce the behavior

Set up new Debian server, join to the domain with Samba+SSSD. `getent passwd ${ADUSER}` works perfectly fine.
Add user to group `docker`.
`docker run -d --user ${ADUSER} ubuntu:latest sleep`

Otherwise, if the ${ADUSER} creates the container, without `--user ${ADUSER}`, then the container is practically owned by root.

**Output of `docker version`:**

```
Docker version 18.09.4, build d14af54
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 10
Server Version: 18.09.4
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-8-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.73GiB
Name: myserver
ID: GV3T:DDIO:Q22P:DFJX:ZD6U:D32E:75KJ:BLYS:X2VS:LWSY:MTMJ:DG42
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
Physical server.

**Comment by iagomez** [comment] 2019-04-15 14:59
**Have you tried passing the `uid` to the `--user` flag?**

Looks like that is failing because `${ADUSER}` doesn't exist in the container. Per the docs:
> When passing a numeric ID, the user does not have to exist in the container.

I can reproduce the error you're seeing with local users as well, which suggests this is not related to AD:

```
[root@ip-172-31-40-76 ~]# useradd test
[root@ip-172-31-40-76 ~]# logout
[ec2-user@ip-172-31-40-76 ~]$ id test
uid=1001(test) gid=1001(test) groups=1001(test)

[ec2-user@ip-172-31-40-76 ~]$ sudo docker run --user test hello-world
docker: Error response from daemon: linux spec user: unable to find user test: no matching entries in passwd file.
ERRO[0000] error waiting for container: context canceled

[ec2-user@ip-172-31-40-76 ~]$ id test
uid=1001(test) gid=1001(test) groups=1001(test)
[ec2-user@ip-172-31-40-76 ~]$
[ec2-user@ip-172-31-40-76 ~]$ sudo docker run --user 1001 hello-world
Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.
```

**Comment by ncihnegn** [comment] 2019-08-14 22:43
Need this as well.

**Comment by thaJeztah** [comment] 2019-08-15 00:32
This won't be possible; as commented above, the user you specify here is either a numeric ID, or (if a non-numeric ID), a user that is present inside the container (which is then used to look up the user's UID in the container image using the passwd file)

Given that the lookup must be done _before_ the container is started (as it's used to start the container's process), it's not possible to do a lookup from within the container (basically, it's a chicken and egg situation), so the only option is to use the passwd file.

I'm closing this issue, because this is not something that can be implemented because of the above, but feel free to continue the conversation

**Closed by thaJeztah** 2019-08-15 00:32 UTC

**Comment by jwalzer** [comment] 2023-02-19 20:54
The thing is: that this doesn't even work, when I only use the UID because it looks like docker only uses 32Bit U/GIDs ...

```
# docker run --rm --name hw -u '3743417424:3743416833' hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
2db29710123e: Pull complete
Digest: sha256:6e8b6f026e0b9c419ea0fd02d3905dd0952ad1feea67543f525c73a0a790fefb
Status: Downloaded newer image for hello-world:latest
docker: Error response from daemon: uids and gids must be in range 0-2147483647.
# id 3743417424
uid=3743417424(IN6-ADDR\jwalzer) gid=3743416833(IN6-ADDR\Domain Users) ....
```
