### ISSUE TITLE
docker-ce-17.12.1.ce-1.el7.centos.x86_64 seems to have broken dns resolution inside of my containers

### ISSUE THREAD

**Issue by markmorlino** [docker/for-linux#255] opened 2018-03-16 20:18 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

dns resolution works from inside containers

### Actual behavior

dns resolution doesn't work from inside containers

### Steps to reproduce the behavior

`docker run -ti --rm  alpine ping -c 1 www.google.com`

works with 17.12.0-ce.
with 17.12.1-ce it fails: `ping: bad address 'www.google.com'`

**Output of `docker version`:**

```
Client:
 Version:	17.12.1-ce
 API version:	1.35
 Go version:	go1.9.4
 Git commit:	7390fc6
 Built:	Tue Feb 27 22:15:20 2018
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.1-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	7390fc6
  Built:	Tue Feb 27 22:17:54 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

```
Containers: 256
 Running: 2
 Paused: 0
 Stopped: 254
Images: 10
Server Version: 17.12.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.11.6.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.4 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.51GiB
Name: qppar-dev-superset-ecs-ip-10-247-24-207.awscloud.cms.local
ID: GVFO:GJPG:OSYD:Y24N:BOC2:JXGE:EWK7:NEUY:J26P:Y3RI:5EJA:C7EN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
this problem happened in AWS

`yum downgrade docker-ce-17.12.0.ce-1.el7.centos.x86_64 && service restart docker` has resolved the problem

**Comment by leaberry** [comment] 2018-05-01 16:00
I can confirm this as well in Docker version 18.03.1-ce, build 9ee9f40 on Centos 7.3 (and 7.4)

Docker is not routing inbound udp packets on port 53 correctly. You can see this with a simple test on two physical servers using netcat. I have an example here.

Prior to running this example the iptables rules were completely wiped on the server and dockerd restarted. 
![screen shot 2018-05-01 at 8 42 42 am](https://user-images.githubusercontent.com/4764447/39480645-0874b1b0-4d26-11e8-9596-10f75f0ecaa8.png)

**Incidentally the dns-opt setting in daemon.json is ignored as well** and the only way to workaround this problem is to start your container with `--dns-opt "use-vc"` which forces dns to use tcp packets instead. Like this

`docker run --dns-opt "use-vc" -it tutum/dnsutils /bin/bash`

I consider this a large bug. It only affects Centos7. My testing on ubuntu 16.04 shows dns resolution works as expected.

**Comment by ctelfer** [comment] 2018-05-15 19:06
I gave a few tries at reproducing both the original and the follow-up comment symptoms issue on RHEL 7.3 and 7.4 using docker's current master branch.  The ordinary "ping google" test passed without issue.  Not sure if that was something fixed between 17.12 and the 18.x series.

As for the second set of tests, my AWS RHEL machines came up with most ports (including 53) blocked by default.  So iptables would pass either port 53 or 4444 at first.  After adjusting to allow for those in the host namespace, traffic flowed cleanly both to and from the container regardless of port.

Now, it is entirely possible that my setup doesn't end up matching the one described as `the iptables rules were completely wiped on the server and dockerd restarted` above.  My RHEL machine clearly had a lot of system-config firewall rules in place.  Maybe a dump of `iptables -L -nv` in the host namespace would give some pointer as to what is going on.

**Comment by leaberry** [comment] 2018-05-15 22:45
You're correct. I cannot reproduce it on a clean iso Centos 7.4 install. I can only reproduce it on the puppetized base config we use. I compared the `iptables -L -nv` output and it's the same on the two boxes. It's not a firewall issue but it is subtle. 

I've looked at the sysctl settings between the boxes I have and nothing sticks out. I'm setting some docker socket overrides so the socket belongs to `group=wheel` but I set that up on the clean test box and it still worked.

So yes, something is wrong, but it's probably not something you can fix. My guess is it's an interaction between some system/kernel settings and docker. I might debug a little more but I'm just comparing the two machines to see what's different.

**Comment by thaJeztah** [comment] 2018-05-29 22:28
let me close this issue for now, given that it looks to be situation dependent, and there's no consistent way to reproduce

**Closed by thaJeztah** 2018-05-29 22:29 UTC
