### ISSUE TITLE
Docker service crashes unexpectedly (MX Linux)

### ISSUE THREAD

**Issue by oxfn** [docker/for-linux#1046] opened 2020-06-24 20:10 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one (**by stack trace**)

### Environment
* OS Linux mxpc 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
* All hardware is new and tested, memory and disks are OK

### Expected behavior
Docker service works without crash

### Actual behavior
Docker service crashes unexpectedly. Service log shows:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55f246db3388]

goroutine 733 [running]:
github.com/armon/go-radix.recursiveWalk(0x0, 0xc002790e08, 0x55f247f57900)
        /build/docker.io-X5uIDh/docker.io-18.09.1+dfsg1/.gopath/src/github.com/armon/go-radix/radix.go:519 +0x28
github.com/armon/go-radix.recursiveWalk(0xc00238e6f0, 0xc002790e08, 0x55f200000000)
        /build/docker.io-X5uIDh/docker.io-18.09.1+dfsg1/.gopath/src/github.com/armon/go-radix/radix.go:525 +0x7a
github.com/armon/go-radix.recursiveWalk(0xc002991b90, 0xc002790e08, 0xc002790c00)
        /build/docker.io-X5uIDh/docker.io-18.09.1+dfsg1/.gopath/src/github.com/armon/go-radix/radix.go:525 +0x7a
github.com/armon/go-radix.recursiveWalk(0xc003211050, 0xc002790e08, 0xc002790cc0)
        /build/docker.io-X5uIDh/docker.io-18.09.1+dfsg1/.gopath/src/github.com/armon/go-radix/radix.go:525 +0x7a
github.com/armon/go-radix.recursiveWalk(0xc002fcac30, 0xc002790e08, 0x18)
        /build/docker.io-X5uIDh/docker.io-18.09.1+dfsg1/.gopath/src/github.com/armon/go-radix/radix.go:525 +0x7a
github.com/armon/go-radix.(*Tree).WalkPrefix(0xc0029bd6a0, 0xc000be4620, 0x1a, 0xc002790e08)
        /build/docker.io-X5uIDh/docker.io-18.09.1+dfsg1/.gopath/src/github.com/armon/go-radix/radix.go:473 +0xdb
github.com/docker/libnetwork/networkdb.(*NetworkDB).reapTableEntries(0xc002640000)
        /build/docker.io-X5uIDh/docker.io-18.09.1+dfsg1/.gopath/src/github.com/docker/libnetwork/networkdb/cluster.go:396 +0x3c5
github.com/docker/libnetwork/networkdb.(*NetworkDB).reapState(0xc002640000)
        /build/docker.io-X5uIDh/docker.io-18.09.1+dfsg1/.gopath/src/github.com/docker/libnetwork/networkdb/cluster.go:362 +0x2d
github.com/docker/libnetwork/networkdb.(*NetworkDB).reapState-fm()
        /build/docker.io-X5uIDh/docker.io-18.09.1+dfsg1/.gopath/src/github.com/docker/libnetwork/networkdb/cluster.go:170 +0x2c
github.com/docker/libnetwork/networkdb.(*NetworkDB).triggerFunc(0xc002640000, 0x12a05f200, 0xc000cdda40, 0xc00263a480)
        /build/docker.io-X5uIDh/docker.io-18.09.1+dfsg1/.gopath/src/github.com/docker/libnetwork/networkdb/cluster.go:256 +0x10a
created by github.com/docker/libnetwork/networkdb.(*NetworkDB).clusterInit
        /build/docker.io-X5uIDh/docker.io-18.09.1+dfsg1/.gopath/src/github.com/docker/libnetwork/networkdb/cluster.go:178 +0x830
```

### Steps to reproduce the behavior

1. Start docker service
2. Init swarm
3. Deploy the stack with 4 services (custom flask app, custom flask+rq app, postgres, redis)
4. Use app for about 5 minutes

Then app stops responding. 

**Output of `docker version`:**

```
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.11.6
 Git commit:        4c52b90
 Built:             Tue, 03 Sep 2019 19:59:35 +0200
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.6
  Git commit:       4c52b90
  Built:            Tue Sep  3 17:59:35 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**
```
Containers: 29
 Running: 2
 Paused: 0
 Stopped: 27
Images: 30
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: fv5xj3kxhjajcfo2wzcxsv4kr
 Is Manager: true
 ClusterID: 7gxu3ib287szc07jd3fi5o1um
 Managers: 1
 Nodes: 1
 Default Address Pool: 10.0.0.0/8  
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 127.0.0.1
 Manager Addresses:
  127.0.0.1:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 1.0.0~rc6+dfsg1-3
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.19.0-6-amd64
Operating System: Debian GNU/Linux 10 (buster)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.774GiB
Name: mxpc
ID: YE7I:LQSJ:UVMP:YQ3Q:GMCY:O5EF:W756:WN3J:GFCO:THVN:O4DA:5WNN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Comment by thaJeztah** [comment] 2020-06-29 15:21
Note that;

- docker 18.09.x reached EOL last year and is no longer maintained
- MX Linux is not a distro that we build official packages for, and is untested
- from the output of your `docker version` and `docker info`, this looks to be a non-official build, and from the paths in the stack dump, I suspect those builds may be using different (possibly incompatible) versions of build-time dependencies

Looks like MX Linux is a Debian derivative; Are you seeing the same problem if you install the official Docker package for debian? (https://docs.docker.com/engine/install/debian/) 

I'd recommend opening a ticket in the MX Linux issue tracker if that's where you installed this package from.

Closing this ticket because of the above, but feel free to to continue the conversation

**Closed by thaJeztah** 2020-06-29 15:21 UTC

**Comment by joelpet** [comment] 2021-02-14 21:44
I see the same crashes happening repeatedly – almost exactly once every thirty minutes – on an up-to-date Debian 10 running version `18.09.1+dfsg1-7.1+deb10u2` of `docker.io`:

```
Feb 14 22:20:44 dockerd[5474]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 14 22:20:44 dockerd[5474]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5640c9faf368]
Feb 14 22:20:44 dockerd[5474]: goroutine 1255 [running]:
Feb 14 22:20:44 dockerd[5474]: github.com/armon/go-radix.recursiveWalk(0x0, 0xc00176be08, 0x5640cb153600)
Feb 14 22:20:44 dockerd[5474]:         /build/docker.io-xinzYt/docker.io-18.09.1+dfsg1/.gopath/src/github.com/armon/go-radix/radix.go:519 +0x28
Feb 14 22:20:44 dockerd[5474]: github.com/armon/go-radix.recursiveWalk(0xc002a9f470, 0xc00176be08, 0x5640cb153600)
Feb 14 22:20:44 dockerd[5474]:         /build/docker.io-xinzYt/docker.io-18.09.1+dfsg1/.gopath/src/github.com/armon/go-radix/radix.go:525 +0x7a
Feb 14 22:20:44 dockerd[5474]: github.com/armon/go-radix.recursiveWalk(0xc00a91e240, 0xc00176be08, 0xc00176bc00)
Feb 14 22:20:44 dockerd[5474]:         /build/docker.io-xinzYt/docker.io-18.09.1+dfsg1/.gopath/src/github.com/armon/go-radix/radix.go:525 +0x7a
Feb 14 22:20:44 dockerd[5474]: github.com/armon/go-radix.recursiveWalk(0xc006657d70, 0xc00176be08, 0x19)
Feb 14 22:20:44 dockerd[5474]:         /build/docker.io-xinzYt/docker.io-18.09.1+dfsg1/.gopath/src/github.com/armon/go-radix/radix.go:525 +0x7a
Feb 14 22:20:44 dockerd[5474]: github.com/armon/go-radix.(*Tree).WalkPrefix(0xc009c97800, 0xc0015abce0, 0x1a, 0xc00176be08)
Feb 14 22:20:44 dockerd[5474]:         /build/docker.io-xinzYt/docker.io-18.09.1+dfsg1/.gopath/src/github.com/armon/go-radix/radix.go:473 +0xdb
Feb 14 22:20:44 dockerd[5474]: github.com/docker/libnetwork/networkdb.(*NetworkDB).reapTableEntries(0xc00a69e480)
Feb 14 22:20:44 dockerd[5474]:         /build/docker.io-xinzYt/docker.io-18.09.1+dfsg1/.gopath/src/github.com/docker/libnetwork/networkdb/cluster.go:396 +0x3c5
Feb 14 22:20:44 dockerd[5474]: github.com/docker/libnetwork/networkdb.(*NetworkDB).reapState(0xc00a69e480)
Feb 14 22:20:44 dockerd[5474]:         /build/docker.io-xinzYt/docker.io-18.09.1+dfsg1/.gopath/src/github.com/docker/libnetwork/networkdb/cluster.go:362 +0x2d
Feb 14 22:20:44 dockerd[5474]: github.com/docker/libnetwork/networkdb.(*NetworkDB).reapState-fm()
Feb 14 22:20:44 dockerd[5474]:         /build/docker.io-xinzYt/docker.io-18.09.1+dfsg1/.gopath/src/github.com/docker/libnetwork/networkdb/cluster.go:170 +0x2c
Feb 14 22:20:44 dockerd[5474]: github.com/docker/libnetwork/networkdb.(*NetworkDB).triggerFunc(0xc00a69e480, 0x12a05f200, 0xc001a93ec0, 0xc009c97c40)
Feb 14 22:20:44 dockerd[5474]:         /build/docker.io-xinzYt/docker.io-18.09.1+dfsg1/.gopath/src/github.com/docker/libnetwork/networkdb/cluster.go:256 +0x10a
Feb 14 22:20:44 dockerd[5474]: created by github.com/docker/libnetwork/networkdb.(*NetworkDB).clusterInit
Feb 14 22:20:44 dockerd[5474]:         /build/docker.io-xinzYt/docker.io-18.09.1+dfsg1/.gopath/src/github.com/docker/libnetwork/networkdb/cluster.go:178 +0x830
Feb 14 22:20:44 systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 14 22:20:44 systemd[1]: docker.service: Failed with result 'exit-code'.
Feb 14 22:20:44 systemd[1]: docker.service: Service RestartSec=100ms expired, scheduling restart.
Feb 14 22:20:44 systemd[1]: docker.service: Scheduled restart job, restart counter is at 149.
Feb 14 22:20:44 systemd[1]: Stopped Docker Application Container Engine.
Feb 14 22:20:44 systemd[1]: docker.service: Found left-over process 3277 (docker-containe) in control group while starting unit. Ignoring.
Feb 14 22:20:44 systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Feb 14 22:20:44 systemd[1]: docker.service: Found left-over process 7334 (docker-containe) in control group while starting unit. Ignoring.
Feb 14 22:20:44 systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Feb 14 22:20:44 systemd[1]: docker.service: Found left-over process 7491 (docker-containe) in control group while starting unit. Ignoring.
Feb 14 22:20:44 systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Feb 14 22:20:44 systemd[1]: docker.service: Found left-over process 7650 (docker-containe) in control group while starting unit. Ignoring.
Feb 14 22:20:44 systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Feb 14 22:20:44 systemd[1]: docker.service: Found left-over process 7687 (docker-containe) in control group while starting unit. Ignoring.
Feb 14 22:20:44 systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Feb 14 22:20:44 systemd[1]: docker.service: Found left-over process 7835 (docker-containe) in control group while starting unit. Ignoring.
Feb 14 22:20:44 systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Feb 14 22:20:44 systemd[1]: docker.service: Found left-over process 3349 (sleep) in control group while starting unit. Ignoring.
Feb 14 22:20:44 systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Feb 14 22:20:44 systemd[1]: docker.service: Found left-over process 7392 (apache2) in control group while starting unit. Ignoring.
Feb 14 22:20:44 systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Feb 14 22:20:44 systemd[1]: docker.service: Found left-over process 8377 (apache2) in control group while starting unit. Ignoring.
Feb 14 22:20:44 systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Feb 14 22:20:44 systemd[1]: docker.service: Found left-over process 8378 (apache2) in control group while starting unit. Ignoring.
Feb 14 22:20:44 systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Feb 14 22:20:44 systemd[1]: docker.service: Found left-over process 8379 (apache2) in control group while starting unit. Ignoring.
Feb 14 22:20:44 systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Feb 14 22:20:44 systemd[1]: docker.service: Found left-over process 8380 (apache2) in control group while starting unit. Ignoring.
Feb 14 22:20:44 systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Feb 14 22:20:44 systemd[1]: docker.service: Found left-over process 8381 (apache2) in control group while starting unit. Ignoring.
Feb 14 22:20:44 systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Feb 14 22:20:44 systemd[1]: docker.service: Found left-over process 7519 (mysqld) in control group while starting unit. Ignoring.
Feb 14 22:20:44 systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Feb 14 22:20:44 systemd[1]: docker.service: Found left-over process 7675 (registry) in control group while starting unit. Ignoring.
Feb 14 22:20:44 systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Feb 14 22:20:44 systemd[1]: docker.service: Found left-over process 7717 (node) in control group while starting unit. Ignoring.
Feb 14 22:20:44 systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Feb 14 22:20:44 systemd[1]: docker.service: Found left-over process 7893 (gotify-app) in control group while starting unit. Ignoring.
Feb 14 22:20:44 systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
```

**Output of `docker stack ls`:**

```
NAME                SERVICES            ORCHESTRATOR
gotify              1                   Swarm
[redacted]          3                   Swarm
organice            1                   Swarm
registry            1                   Swarm
```

**Output of `docker version`:**

```
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.11.6
 Git commit:        4c52b90
 Built:             Sun, 14 Jun 2020 22:12:29 +0200
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.6
  Git commit:       4c52b90
  Built:            Sun Jun 14 20:12:29 2020
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 264
 Running: 6
 Paused: 0
 Stopped: 258
Images: 51
Server Version: 18.09.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 840
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: [redacted]
 Is Manager: true
 ClusterID: [redacted]
 Managers: 1
 Nodes: 1
 Default Address Pool: 10.0.0.0/8  
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: [redacted]
 Manager Addresses:
  [redacted]:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 1.0.0~rc6+dfsg1-3
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.19.0-14-amd64
Operating System: Debian GNU/Linux 10 (buster)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.6GiB
Name: [redacted]
ID: [redacted]
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by thaJeztah** [comment] 2021-02-15 09:59
@joelpet docker.io `18.09.1+dfsg1-7.1+deb10u2` is a version of docker that's built and packaged by the debian package maintainers; those packages are known to sometimes use incorrect (sometimes incompatible) versions of build-dependencies. Note that Docker 18.09 reached EOL two years ago.

Are you able to reproduce the problem with a current version of the official docker packages from download.docker.com? (https://docs.docker.com/engine/install/debian/)

**Comment by joelpet** [comment] 2021-02-18 22:13
@thaJeztah Thank you for your response. I prefer using packages from the official Debian repositories because then I can be somewhat confident that the software they contain is free. By the way, the team responsible for packaging Docker seems to experience some churn in doing so. [[1]] Are you working with them to improve their packaging experience?

I want to try the latest Docker version from Debian testing – `20.10.3+dfsg1-2`, at the time of writing – but I am not sure when that will happen.

[1]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=908603#12
