### ISSUE TITLE
Docker exists

### ISSUE THREAD

**Issue by pulli23** [docker/for-linux#1021] opened 2020-05-27 14:11 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
When using `docker start pg` I expect the (postgres) docker to start when it is not started. Esepcially when the reports from `docker ps` are empty. But `docker ps -a` shows the docker existing

### Actual behavior

The following error is returned:

```
Error response from daemon: OCI runtime create failed: container with id exists: bdc64f7a17dd5cb0f2e4ce38645652fc614e16422939ff7aad01581892e01f9a: unknown
```
Where the id is indeed the id of the `pg` docker.

This occurred after rebooting, but only after using the docker image for over a year.

### Steps to reproduce the behavior
create a docker: `docker run --name pg -e POSTGRES_PASSWORD=mysecretpassword -d postgres`
stop: `docker stop pg`
reboot
start: `docker start pg`

I have to note that this only happened after hundreds of times rebooting.

**Output of `docker version`:**

```
Client:
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.13.4
 Git commit:        1752eb3
 Built:             Sat Nov 16 01:05:26 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.13.4
  Git commit:       9552f2b
  Built:            Sat Nov 16 01:07:48 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Output of `docker info`:**

```
Containers: 18
 Running: 0
 Paused: 0
 Stopped: 18
Images: 215
Server Version: 18.09.9
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
runc version: N/A
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-101-generic
Operating System: Ubuntu Core 16
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.58GiB
Name: paul-GP60-2QF
ID: AUH2:C5QZ:SZJ6:AGOK:PQEU:K3ZN:JNVN:3MKK:LOQX:D3IB:7OQF:MO2W
Docker Root Dir: /var/snap/docker/common/var-lib-docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by thaJeztah** [comment] 2020-05-27 14:26
Looks like you've installed the docker `snap` package. That package is built and maintained by Canonical (and there's various issues with the snap installs).

Are you still able to reproduce this on a current (19.03.x) version of the official docker packages? (https://docs.docker.com/engine/install/ubuntu/)

If you cannot switch to use those packages, I recommend opening a ticket in the Canonical issue tracker.


I'm closing this ticket because we don't support the snap packages, but feel free to continue the conversation

**Closed by thaJeztah** 2020-05-27 14:26 UTC
