### ISSUE TITLE
Docker stack does not respect the "user" setting

### ISSUE THREAD

**Issue by sido420** [docker/for-linux#483] opened 2018-11-12 13:23 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
I expect the user option in Docker compose to behave the same on Docker stack when I provide a user ID and/group ID explicitly in docker-compose. 

### Actual behavior
However, in swarm mode, service's containers are running as root for some reason and so is the process inside the container.

### Steps to reproduce the behavior
I'm using the following service definition in Docker compose (removed extra options).
```
version: '3.7'
services:
  webcdn:
    image: nginx:latest
    user: ${Nginx_UserID}:${Nginx_GroupID}
    deploy:
      restart_policy:  
        condition: any
        delay: 10s
        max_attempts: 100
        window: 20s
      mode: replicated
      replicas: 1
      update_config:
        delay: 5s
```
The user and group ids are coming from .env file.

**Output of `docker version`:**
```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:25:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:27 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 0
 Paused: 0
 Stopped: 0
Images: 33
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 12v6jhk14wnhzxqp5kop15ufp
 Is Manager: true
 ClusterID: sikodzkjx5g8kj1wiw0v4dqjm
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.1.16
 Manager Addresses:
  192.168.1.16:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-46-generic
Operating System: Ubuntu 17.10
OSType: linux
Architecture: x86_64
WARNING: No swap limit support
CPUs: 8
Total Memory: 11.72GiB
Name: ubuntu-macpro
ID: NOL5:5EBO:JGFF:CQYB:U7BI:AGFF:KKOZ:HUG4:7MDC:KMPD:GQJG:DGSH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Its a physical machine running Linux.

**Comment by sido420** [comment] 2018-11-12 15:22
This is what the process (ps aux) hierarchy looks like from host:
```
root     28767  0.0  0.0 144908  9012 ?        Ss   10:17   0:00 nginx: master process nginx -g daemon off;
systemd+ 28960  0.0  0.0 411488  7972 ?        SNl  10:17   0:00 nginx: worker process
systemd+ 28961  0.0  0.0 411488  7972 ?        SNl  10:17   0:00 nginx: worker process
systemd+ 28962  0.0  0.0 411488 10840 ?        SNl  10:17   0:00 nginx: worker process
systemd+ 28963  0.0  0.0 411488  7972 ?        SNl  10:17   0:00 nginx: worker process
systemd+ 28964  0.0  0.0 411488  7972 ?        SNl  10:17   0:00 nginx: worker process
systemd+ 28966  0.0  0.0 411488  7972 ?        SNl  10:17   0:00 nginx: worker process
systemd+ 28967  0.0  0.0 411488  7972 ?        SNl  10:17   0:00 nginx: worker process
systemd+ 28968  0.0  0.0 411488  7972 ?        SNl  10:17   0:00 nginx: worker process
systemd+ 28969  0.0  0.0 145084  3400 ?        S    10:17   0:00 nginx: cache manager process
```
I'm not sure where this systemd+ user comes from. This is causing permission issues on attached volumes for me and files cannot be served.

```
root@2f5c09e69338:/# id systemd+
id: 'systemd+': no such user
```

**Comment by thaJeztah** [comment] 2018-11-12 21:39
> The user and group ids are coming from `.env` file.

I suspect this is the issue; `docker stack deploy` does not automatically load `.env` files; when using variables in the compose file; those environment variables must be set in the shell that you deploy from. You can follow this issue to see if work is being done on this; https://github.com/moby/moby/issues/29133 

Reproducing your issue (with a simplified stack file);

```bash
Nginx_UserID=123 Nginx_GroupID=456 docker stack deploy -c- testing <<'EOF'
version: '3.7'
services:
  webcdn:
    tty: true
    image: busybox:latest
    user: ${Nginx_UserID}:${Nginx_GroupID}
EOF
```

After the service was deployed, I inspect one of the containers of the service;


```bash
docker inspect --format '{{.Config.User}}' a2821a7c5d16 
123:456
```

I'm closing this issue, because this looks to be working, but feel free to continue the conversation

**Closed by thaJeztah** 2018-11-12 21:39 UTC
