### ISSUE TITLE
How can I mount a file onto a container?

### ISSUE THREAD

**Issue by only-gale** [docker/for-linux#6] opened 2017-06-02 06:59 UTC
I wanna use a custom mysql config file when running mysql/mysql-server image.
### Expected behavior
Everything is fine as correct as described [here](https://hub.docker.com/r/mysql/mysql-server/)
### Actual behavior
Please see the image below for details.
### Information

  - Linux distro: Ubuntu Xenial
  - Docker CE version: 17.03.1-ce

### Steps to reproduce the behavior
The steps is shown in the image below.

![docker-issue](https://cloud.githubusercontent.com/assets/3478864/26714130/b2d4026c-47a2-11e7-939b-a86f58330c6c.jpg)

**Comment by thaJeztah** [comment] 2017-07-01 03:51
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-07-01 03:51 UTC
