### ISSUE TITLE
poor performance when move dir which contains large quantities of small files with docker overlay2

### ISSUE THREAD

**Issue by blueskyll** [docker/for-linux#379] opened 2018-07-31 08:51 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

we make a docker image with a dir(almost 3.3G) which contains large quantities of small files, and then load this image to run containers. We move(mv) this dir(which means we move dir from overlay lower layer to upper layer) in container, and everything is normal when we do this operation with docker graph configured on SSD. However when docker graph is configured on HDD, the same move operation takes quite a long time(3.3G with about 8 hours) while performance of copy operation seems normal.
### Expected behavior
move dir from lower layer to upper layer (3.3G) should complete in a few minutes.

### Actual behavior
![image](https://user-images.githubusercontent.com/7546095/43449855-0cc25910-94e4-11e8-882b-dfd492726356.png)

### Steps to reproduce the behavior

**Output of `docker version`:**

```
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:23:40 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:25:03 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:23:40 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:25:03 2017
 OS/Arch:      linux/amd64
 Experimental: false
[root@yq01-ai2b-dev-online03 ~]# docker info
Containers: 33
 Running: 16
 Paused: 0
 Stopped: 17
Images: 40
Server Version: 17.09.1-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: 10.255.99.13:5000/hdfs
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: nvidia runc
Default Runtime: nvidia
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64-dirty (expected: 3f2f8b84a77f73d38244dd690525642a72156c64)
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.17.11-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 251.8GiB
Name: yq01-ai2b-dev-online03.yq01
ID: G5WH:KQE6:Y5AG:AH6H:4IAT:TTGH:VZK4:AL3Y:QIJS:5SVG:COEJ:7ZXD
Docker Root Dir: /home/disk3/docker-data
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 10.255.99.13:5000
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by thaJeztah** [comment] 2018-07-31 09:12
I don't think docker is involved here, as overlayfs is directly provided by the kernel; moving these files does mean that not only all files have to be copied, but also that (for directories), whiteout files have to be created (which may add additional overhead).

Have you tried performing the same action directly on an overlay mount on the host (i.e., manually setting up an overlayfs mount, and doing a `cp` , `mv`) ?


What distro, and kernel version are you running? What's the underlying filesystem?

**Comment by blueskyll** [comment] 2018-07-31 09:37
@thaJeztah Thanks. The env is Centos 7 with kernel 4.x, and the underlying filesystem is xfs. It indeed should be a overlayfs problem, action directly on overlay has the same performace.

**Comment by thaJeztah** [comment] 2018-07-31 10:10
Is there a reason you want to keep those files in the container's filesystem? Have you considered using a _volume_ for those files? (could be an anonymous volume if files don't have to persist beyond the container's lifecycle); doing so would skip the performance penalty of copy-on-write / overlay filesystems.

As to the problem in general; I don't think there's much to be done here; perhaps @szmi or @koct9i have any suggestions (or could indicate if this is a possible regression in overlayfs)


I'll close this issue, because of the above, but feel free to continue the conversation

**Closed by thaJeztah** 2018-07-31 10:10 UTC

**Comment by koct9i** [comment] 2018-08-02 07:32
I have no idea why mv is so slow, in worst case it should make a copy of moved files.
Probably directory merging does not scale well.

Feature redirect_dir should help in most cases
https://www.kernel.org/doc/Documentation/filesystems/overlayfs.txt
