### ISSUE TITLE
ARG without default value used in FROM does not take any value at all

### ISSUE THREAD

**Issue by rrajkomar** [docker/for-linux#59] opened 2017-07-13 13:35 UTC
* [x] This is a bug report
* [x] This is a feature request
* [x] I searched existing issues before opening this one

When defining a build argument in a Dockerfile to beused in the FROM instruction, if the ARG instruction does not have a default value, no value is set to the argument even if you pass a value in the CLI command 

### Expected behavior
`docker build --build-arg BASE_DOCKER_IMAGE=debian:jessie  .` should create an image with a FROM debian:jessie and the RUN echo instruction shoudl display "debian:jessie"

### Actual behavior

Both usage resolve to empty string

### Steps to reproduce the behavior
See attached files (remove the txt extension !) for a code sample
[docker-compose.yml.txt](https://github.com/docker/for-linux/files/1145322/docker-compose.yml.txt)
[Dockerfile.txt](https://github.com/docker/for-linux/files/1145321/Dockerfile.txt)

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:04 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:18:59 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 26
 Running: 15
 Paused: 0
 Stopped: 11
Images: 832
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /opt/docker/aufs
 Backing Filesystem: extfs
 Dirs: 765
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.63GiB
Name: morningstar
ID: U3JL:JURH:RYBD:2MSN:RCL3:QUMM:2G3G:JXOJ:5PM6:U64E:6LED:EIJX
Docker Root Dir: /opt/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
Same thing happens when using docker-compose (with the docker-compose file) (which is expected considering the behaviour of docker itself)

**Comment by dnephin** [comment] 2017-07-13 16:19
Here's what I see:

```
$ docker build --build-arg=BASE_DOCKER_IMAGE=debian:jessie .
Sending build context to Docker daemon    108kB
Step 1/3 : ARG BASE_DOCKER_IMAGE
 --->
Step 2/3 : FROM ${BASE_DOCKER_IMAGE}
 ---> 3e83c23dba6a
Step 3/3 : RUN echo ${BASE_DOCKER_IMAGE}
 ---> Running in 9be32436afb8

 ---> 3f90eb09d7c6
Removing intermediate container 9be32436afb8
Successfully built 3f90eb09d7c6
$
```

This is working as intended. The `ARG` before `FROM` is used as the base image. To use an ARG in a build stage you have to define it within that build stage:

```
ARG BASE_DOCKER_IMAGE
FROM ${BASE_DOCKER_IMAGE}
ARG BASE_DOCKER_IMAGE
RUN echo ${BASE_DOCKER_IMAGE}
```

which then prints the value you expect.

The docs mention this: https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact but could be improved to be more clear.  I'll open a PR to update the docs, but close this issue since it's not a bug.

**Closed by dnephin** 2017-07-13 16:19 UTC

**Comment by dnephin** [comment] 2017-07-13 16:31
https://github.com/docker/cli/pull/333
