### ISSUE TITLE
docker container exit with code 139

### ISSUE THREAD

**Issue by GitSoftwareNow** [docker/for-linux#1014] opened 2020-05-21 13:35 UTC
root@test11#docker ps -a
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
7b606d820b89 android "/anbox-init.sh" 15 hours ago Exited (139) 15 hours ago condescending_jackson

root@test11:/home# docker logs 7b606d820b89
root@test11:/home#

**Comment by buliverd53** [comment] 2020-05-22 13:43
Same here =/
```
docker info
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.84-microsoft-standard
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 12.44GiB
 Name: docker-desktop
 ID: 36FV:UDZS:ABTQ:SNR2:ARME:XJ6Y:RI5P:AUO7:FLRN:OAW5:JGYU:VAUX
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 42
  Goroutines: 55
  System Time: 2020-05-22T13:43:13.1280568Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by GitSoftwareNow** [comment] 2020-05-23 03:20
no logs here

**Comment by thaJeztah** [comment] 2020-05-27 12:46
There's some information in this comment: https://github.com/docker/for-linux/issues/1019#issuecomment-633410195

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/docker/for-linux/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2020-05-27 12:46 UTC
