### ISSUE TITLE
pygame program not working in ubuntu docker base image

### ISSUE THREAD

**Issue by nirupamjm** [docker/for-linux#1086] opened 2020-08-17 08:13 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
pygame program executed in ubuntu host machine..
![image](https://user-images.githubusercontent.com/68326831/90372604-fdcc1680-e0b3-11ea-87a3-6fd274f3e110.png)

![image](https://user-images.githubusercontent.com/68326831/90372486-d1b09580-e0b3-11ea-809c-17d346acdc28.png)

### Actual behavior
same pygame program executed in ubuntu container(got only partial output..GUI not getting displayed )
![image](https://user-images.githubusercontent.com/68326831/90372107-3c150600-e0b3-11ea-94b7-0ff9f19bcaf1.png)

### Steps to reproduce the behavior

DOCKERFILE:
FROM ubuntu:18.04
COPY . /app
WORKDIR /app
RUN apt-get update \
&& apt-get install -y python3-pip python3-dev \
&& cd /usr/local/bin \
&& ln -s /usr/bin/python3 python \
&& pip3 install --upgrade pip
RUN apt-get install xauth -y
RUN apt install xrdp xfce4 xfce4-goodies tightvncserver
RUN echo xfce4-session> /home/ubuntu/.xsession
RUN cp /home/ubuntu/.xsession /etc/skel
RUN sed -i '0,/-1/s//ask-1/' /etc/xrdp/xrdp.ini
RUN service xrdp restart
RUN pip3 install -r requirements.txt
CMD ["python3", "./main.py"]

--------------------------------------------------
main.py:

import pygame
pygame.init()
screen = pygame.display.set_mode([500, 500])
running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
    screen.fill((255, 255, 255))
    pygame.draw.circle(screen, (0, 0, 255), (250, 250), 75)
    pygame.display.flip()
pygame.quit()
---------------------------------------------------------------------------------------
requirements.txt:
pygame

**Comment by EtricKombat** [comment] 2020-08-17 08:15
@nirupamjm getting same issue for me too.

Hi @thaJeztah can you please advice us in anyway?

**Comment by EtricKombat** [comment] 2020-08-17 08:17
@thaJeztah is there a way to host GUI based applications in docker containers?

**Comment by thaJeztah** [comment] 2020-08-17 08:32
You'd probably want to bind-mount the X11 socket into the container; you're currently only creating a volume for it, similar to https://github.com/jessfraz/dockerfiles/blob/6e1142c2078ba65f306b518137313fa00114db0c/chrome/stable/Dockerfile#L7-L8

so `-v /tmp/.X11-unix:/tmp/.X11-unix` (specify both the path on the host, and where you want to mount it in the container) instead of `-v /tmp/.X11-unix`, which will create an anonymous volume for it

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2020-08-17 08:32 UTC

**Comment by EtricKombat** [comment] 2020-08-18 12:45
Hi @thaJeztah , thank you for pointing this out. From now forth will post related topics in the above listed link.

I was able to resolve this , listing below the code i used : 

https://github.com/EtricKombat/docker/tree/master/src/pygame_blue_success


        docker run -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --user="$(id --user):$(id --group)" 8d61c1d60fcd

**Comment by thaJeztah** [comment] 2020-08-18 15:53
Good to hear that worked! 👍
