### ISSUE TITLE
docker-ce centos 7 mirror eror

### ISSUE THREAD

**Issue by rushins** [docker/for-linux#831] opened 2019-10-18 21:36 UTC
hello
i try to install docker-ce on Centos 7 the repository seems its getting errors.

https://download.docker.com/linux/centos/7/x86_64/stable/repodata/41e005ebd85154b765a5b043b3f94ac79eccdabd4028b54259461fb5fa48f500-primary.sql

can someone check and find out.

**Comment by gonrial** [comment] 2019-10-18 21:43
@rushins https://github.com/docker/for-linux/issues/830#issuecomment-543930808

**Comment by gonrial** [comment] 2019-10-18 22:55
The issue is fixed now ... if you encounter problems you need to clean the cache and rebuild it.
```
sudo yum clean metadata 
sudo yum makecache
```

**Closed** 2019-10-23 18:50 UTC
