### ISSUE TITLE
SHELL command in Dockerfile cannot use build-args

### ISSUE THREAD

**Issue by stffnm** [docker/for-linux#1339] opened 2021-12-30 14:27 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
I want to use docker build build-arg to change the SHELL command inside a Dockerfile.

```docker
from ubuntu

ARG MY_SHELL

RUN echo $MY_SHELL

SHELL [$MY_SHELL, "-c"]

RUN ls
```

using 
```
docker build --build-arg MY_SHELL="/bin/bash" .
```
I expect the same behaviour as using 
```
SHELL ["/bin/bash", "-c"]
```
in the Dockerfile

### Actual behavior
 
```
Error response from daemon: dockerfile parse error line 7: SHELL requires the arguments to be in JSON form
```

**Output of `docker version`:**

```
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.7-0ubuntu5~20.04.2
 Built:             Mon Nov  1 00:34:17 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       20.10.7-0ubuntu5~20.04.2
  Built:            Fri Oct 22 00:45:53 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.5-0ubuntu3~20.04.1
  GitCommit:        
 runc:
  Version:          1.0.1-0ubuntu2~20.04.1
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit: 
```

**Comment by thaJeztah** [comment] 2022-01-04 08:58
Thanks for reporting. Hm.. yes, this is because the "exec-form" (JSON) notation in Dockerfiles do not perform variable substitution. There's been some discussion around this to add support for this (for build-args), but doing so would be a breaking change, so no decision was made yet on that.

That said, if you use BuildKit as builder, you can use a build-arg to use different code-paths based on the value of a build-arg. With that, it's possible to construct flows similar to an "if/else" or "switch" statement.

Here's an example: 

```bash
# syntax=docker/dockerfile:1

# MY_SHELL allows switching between /bin/sh and /bin/bash as SHELL for the build
ARG MY_SHELL=sh

# base-sh uses the default shell (/bin/sh)
FROM ubuntu:20.04 AS base-sh

# base-bash uses bash as shell
FROM ubuntu:20.04 AS base-bash
SHELL ["/bin/bash", "-c"]

# base is the base stage used for further builds, and depending on the
# value of $MY_SHELL,  is an alias for either "base-sh" or "base-bash",
# so uses either /bin/sh or /bin/bash
FROM base-$MY_SHELL AS base

FROM base AS some-stage
RUN echo $0
```

With the above Dockerfile, if no build-arg is passed (or `--build-arg MY_SHELL=sh`), then the default (`/bin/sh`) is used;

```bash
DOCKER_BUILDKIT=1 docker build --progress=plain --no-cache .

# ...
#9 [some-stage 1/1] RUN echo $0
#9 sha256:f16e52a610bac6cb1460f4af7b2e3b840d52ff2a542bd749030e5a7fef5dd7c7
#9 0.212 /bin/sh
#9 DONE 0.2s
# ...
```

When passing `--build-arg MY_SHELL=bash`, the `base-bash` variant of the base stage is used, which uses `/bin/bash` as `SHELL` for `RUN` instructions in the Dockerfile.

```bash
DOCKER_BUILDKIT=1 docker build --progress=plain --no-cache --build-arg MY_SHELL=bash .

# ...
#10 [some-stage 1/1] RUN echo $0
#10 sha256:3f6f0e6f820d5fc06e1adf8a80d986de95986e250b523e61d5e1993ba8b8e1af
#10 0.217 /bin/bash
#10 DONE 0.2s
# ...
```

And you can add additional variants, for example, `zsh`:

```dockerfile
# base-zsh uses zsh as shell
FROM ubuntu:20.04 AS base-zsh
RUN apt-get update && apt-get install -y --no-install-recommends zsh
SHELL ["/bin/bash", "-c"]
```

Be aware though that the `SHELL` instruction is only used for `RUN` instructions during build, and _not_ as the default shell inside the image that was built. If your intent was to set the default shell for the image that was built, you're likely looking for the `CMD` instruction, for example:

```dockerfile
FROM ubuntu:20.04
CMD ["sh"]
```

**Comment by thaJeztah** [comment] 2022-01-04 09:02
Let me close this ticket, as this is not a bug, and if it was meant as a feature request, it's better to open a ticket for that in the BuildKit repository, which is where the Dockerfile syntax is maintained (https://github.com/moby/buildkit), but feel free to continue the conversation after I close this ticket; I haven't seen requests for this before; could you describe your use-case a bit more?  I'm interested to hear what your intended use-case is for this 🤔

**Closed by thaJeztah** 2022-01-04 09:02 UTC

**Comment by stffnm** [comment] 2022-01-04 09:41
Thank you very much for the clarification!

I use anaconda in my images and I need to build similar docker images with different conda environment names.

In the Dockerfile, I create a conda environment with
`RUN conda create -n MY_ENV_NAME`
and use
`SHELL ["conda", "run", "-n", "MY_ENV_NAME", "/bin/bash", "-c"]`

so that I can run regular conda commands like
`RUN conda install -n MY_ENV_NAME pkg1 pkg2 ...`
thereafter.

Maybe there is a better solution to this?

**Comment by thaJeztah** [comment] 2022-01-04 11:46
Ah, interesting, yes, I understand your use-case.

> Maybe there is a better solution to this?

Hm.. good question. I'm not familiar with anaconda; perhaps using a `.condarc` or (symlinking?) the conda environment could work.

Possibly an entrypoint script that's used as shell (`SHELL ["/bin/foo.sh"]`) where the script sets up the environment, and then `exec "$@"` could work (similar to the [erntrypoint script in the WordPress image](https://github.com/docker-library/wordpress/blob/fbc4dd7593dd0cf7a239348cb7ebcdcbf505286f/latest/php7.4/apache/docker-entrypoint.sh#L99), but then to be used during build (not at runtime) 🤔
