### ISSUE TITLE
rm -f /var/cache inside my container remove my git folder in host system

### ISSUE THREAD

**Issue by Protoc0d** [docker/for-linux#587] opened 2019-02-11 10:42 UTC
Hello,
i'm using Docker version 18.09.1, build 4c52b90 on Fedora Workstation 29

I work on project symfony using some containers managed using docker-compose. This is my shell output.
``` shell
[protocod@localhost] ~/dev/project (unstable) ⚡ 
❯ docker exec -it 8f8fe9d3bebc /bin/bash
root@8f8fe9d3bebc:/# cd /var/www
root@8f8fe9d3bebc:/var/www# ls
html
root@8f8fe9d3bebc:/var/www# cd html/
root@8f8fe9d3bebc:/var/www/html# ls 
LICENSE  Makefile  README.md  app  bin  composer.json  composer.lock  data  doc  docker  docker-compose.dnsdock.yml  docker-compose.yml  dump-sql  mysqldump.sh  phpunit.xml.dist  src  var  vendor  web
root@8f8fe9d3bebc:/var/www/html# rm -rf /var 
rm: cannot remove '/var/www/html': Device or resource busy
root@8f8fe9d3bebc:/var/www/html# rm -rf /var/cache
root@8f8fe9d3bebc:/var/www/html# exit
exit
[protocod@localhost] ~/dev/project
❯ ls  

```

So, i've deleted the folder /var/cache inside my container, then, my git repository (current folder in host system) content has disappeared. Did you have similar issues ?
I don't understand how my git folder was deleted. 

Thank you for reading this, i will try to find a solution.
Maximilien

**Comment by thaJeztah** [comment] 2019-03-19 18:04
The container you're running this command in probably bind-mounts the directory from your host. When doing so you give the container access to those files, and any change you make to those files (including _deleting_ those files) is made directly to the files you mounted from the host.

This is not a bug, but something to take into account when configuring your container / writing your docker-compose file; by default, containers are isolated, but when using bind-mounts you're explicitly granting them access to files on the host.

I'll close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2019-03-19 18:04 UTC
