### ISSUE TITLE
Losing the Redis data after restart docker, please help

### ISSUE THREAD

**Issue by MacMillan13** [docker/for-linux#1210] opened 2021-02-24 18:12 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

Don't lose Redis data from volume after restart docker.

### Actual behavior
Lose the Redis data after the restart docker.  My docker-compose is 
`
  redis:

    image: bitnami/redis:latest
    container_name: face_redis
    restart: always
    command:
      - 'redis-server'
      - '--loglevel ${REDIS_LOGLEVEL:-warning}'
      - '--databases 2'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--maxmemory ${REDIS_MAXMEM:-50mb}'
      - '--maxmemory-policy ${REDIS_POLICY:-noeviction}'
      - '--requirepass ${REDIS_PASSWORD}'
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/data:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - internal
`

### Steps to reproduce the behavior
Changed volumes, changed Redis image, added commands.

**Output of `docker version`:**

```
Docker version 19.03.6
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by thaJeztah** [comment] 2021-02-25 13:27
I suspect you're bind-mounting your data directory to the wrong location in the container. Note that unlike the official Redis image from Docker Hub (https://hub.docker.com/_/redis), which stores persistent data in `/data` inside the container, the Bitnami redis variant uses a different path for data storage; see ["Persisting your database" section in their documentation](https://hub.docker.com/r/bitnami/redis)
```

> For persistence you should mount a directory at the /bitnami path. If the mounted directory is empty, it will be initialized on the first run.


Generally, I would recommend using the official Redis image from Docker Hub; https://hub.docker.com/_/redis, which also provide multi-arch images (allowing deployment on different architectures); be sure to read the "start with persistent storage" section in the documentation for the image on Docker Hub; https://hub.docker.com/_/redis

If you need to use the bitnami variant, be sure to read their documentation as well, to use the correct paths and configuration to persist your data (https://hub.docker.com/r/bitnami/redis)


Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/docker/for-linux/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2021-02-25 13:27 UTC

**Comment by MacMillan13** [comment] 2021-02-25 14:33
> I suspect you're bind-mounting your data directory to the wrong location in the container. Note that unlike the official Redis image from Docker Hub (https://hub.docker.com/_/redis), which stores persistent data in `/data` inside the container, the Bitnami redis variant uses a different path for data storage; see ["Persisting your database" section in their documentation](https://hub.docker.com/r/bitnami/redis)
> 
> > For persistence you should mount a directory at the /bitnami path. If the mounted directory is empty, it will be initialized on the first run.
> 
> Generally, I would recommend using the official Redis image from Docker Hub; https://hub.docker.com/_/redis, which also provide multi-arch images (allowing deployment on different architectures); be sure to read the "start with persistent storage" section in the documentation for the image on Docker Hub; https://hub.docker.com/_/redis
> 
> If you need to use the bitnami variant, be sure to read their documentation as well, to use the correct paths and configuration to persist your data (https://hub.docker.com/r/bitnami/redis)
> 
> Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
> but for [reporting bugs and feature requests](https://raw.githubusercontent.com/docker/for-linux/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;
> 
> * the Docker Support Forums - https://forums.docker.com
> * the [Docker community Slack channel](http://dockr.ly/slack)
> 
> I'm closing this issue because this is not a bug, but feel free to continue the conversation

Thanks for the answer! But I also tried to do it by official Redis, but doesn't work. Please help..

  redis:
    image: redis:latest
    container_name: face_redis
    restart: always
    command:
      - 'redis-server'
      - '--loglevel ${REDIS_LOGLEVEL:-warning}'
      - '--databases 2'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--maxmemory ${REDIS_MAXMEM:-50mb}'
      - '--maxmemory-policy ${REDIS_POLICY:-noeviction}'
      - '--requirepass ${REDIS_PASSWORD}'
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/data:/data
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - internal

**Comment by thaJeztah** [comment] 2021-02-25 15:01
- Does it work with the `--appendonly yes` option (as documented on https://hub.docker.com/r/bitnami/redis, and https://redis.io/topics/persistence)?
- Can you see data being written to the `./docker/redis/data` directory on your machine?

(also note that the `REDIS_REPLICATION_MODE` env-var looks to be something for the bitnami images only, so you may need to make changes in in your configuration if you need that setting)

**Comment by MacMillan13** [comment] 2021-02-25 15:19
@thaJeztah yes I see data in ./docker/redis/data. I updated docker-compose, added --appendonly yes, but doesn't work.. After restart docker lost data from volumes... I lost more than 3 days on this.

  redis:
    image: redis:latest
    container_name: face_redis
    restart: always
    command:
      - 'redis-server'
      - '--loglevel ${REDIS_LOGLEVEL:-warning}'
      - '--databases 2'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--maxmemory ${REDIS_MAXMEM:-50mb}'
      - '--maxmemory-policy ${REDIS_POLICY:-noeviction}'
      - '--requirepass ${REDIS_PASSWORD}'
      - '--appendonly yes'
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/data:/data
    networks:
      - internal

**Comment by thaJeztah** [comment] 2021-02-25 17:16
> After restart docker lost data from volumes..

Do you mean your `./docker/redis/data` directory is deleted (or files in it?)

**Comment by MacMillan13** [comment] 2021-02-25 17:22
@thaJeztah file exists, but data that was cached before docker restart is lost..

**Comment by thaJeztah** [comment] 2021-02-25 17:40
If you're running on Linux, then the `./docker/redis/data:/var/lib/redis` bind-mount is literally that; it's a bind-mount in the container, so "files in the container === files on the host" (i.e., there's nothing "in between").
So if redis didn't write its cache to disk, it's most likely a redis configuration issue. You can try doing a manual `save` (https://redis.io/commands/save), but otherwise probably need some config changes described in (https://redis.io/topics/persistence).

> before docker restart is lost..

With `docker restart` you mean a restart of the container, the docker daemon, or your machine? Where is `./docker/redis/data` located on your host? Is it in your home-directory? (in case cryptfs is used, that won't be decrypted until you are logged in), is it on a separate storage? (if so: was it mounted the moment that the docker daemon started?)

**Comment by MacMillan13** [comment] 2021-02-25 18:25
@thaJeztah This is my Ubuntu remote server. Redis saves work fine. Docker restart meanse docker-compose down and then docker-compose up --build. Yes this is my home catalog.

**Comment by thaJeztah** [comment] 2021-02-25 21:13
Not sure I have answers for your situation, and I would have to dive into that situation myself, but that's really out of scope for this issue tracker (it's very unlikely to be an issue with the docker daemon itself)

I did a quick search, and there's an old ticket on the issue tracker for the redis image about this; https://github.com/docker/for-linux/issues/1210, and I see an open ticket that may be related https://github.com/docker-library/redis/issues/262. Perhaps those provide more details to help you debug.

**Comment by MacMillan13** [comment] 2021-02-26 07:05
@thaJeztah this ticket 1210 is mine. Okay, thanks for trying.

**Comment by thaJeztah** [comment] 2021-02-26 07:33
Ah, sorry must've had the wrong url on my clipboard; this was the old issue I tried to link  https://github.com/docker-library/redis/issues/4

**Comment by ch1ru** [comment] 2024-07-11 22:54
I had this issue and found that simply binding the data directory to a named volume with the appendonly flag solved the issue. Also I was using the redis:alpine image:

```
redis:
  container_name: redis
  image: redis:alpine
  restart: always
  command: redis-server --appendonly yes
  volumes:
    - redis_data:/data
  ports:
    - 6379:6379

volumes:
  redis_data:
```
Hope this helps anyone with this issue in the future.
