### ISSUE TITLE
pulling multi-cpu architecture images by digest fails

### ISSUE THREAD

**Issue by yamlCase** [docker/for-linux#1150] opened 2020-11-20 19:20 UTC
Pulling a multi-cpu architecture image by digest from docker.io will fail.

Example:

Expected behavior:
```
$ docker pull library/openjdk:8-jre
8-jre: Pulling from library/openjdk
756975cb9c7e: Pull complete
d77915b4e630: Pull complete
5f37a0a41b6b: Pull complete
713f7746108e: Pull complete
ba38f0ad15ed: Pull complete
aef0ecdbb451: Pull complete
Digest: sha256:315ebe39e23eb2aed74f218ec74d6f3b82309cd1a43811ea6188120df110e9d0
Status: Downloaded newer image for openjdk:8-jre
docker.io/library/openjdk:8-jre
```

Failed behavior:
```
$ docker pull library/openjdk:tag@sha256:1655f064c3c6ad37b09d73ee5d4f89a519d5a10ab40ac5ac0e414815d23dc535
sha256:1655f064c3c6ad37b09d73ee5d4f89a519d5a10ab40ac5ac0e414815d23dc535: Pulling from library/openjdk
3889bb8d808b: Pulling fs layer
4830fb08bc2d: Pulling fs layer
126d9a92c0cb: Pulling fs layer
864d6ab6d378: Waiting
699c3656ce68: Waiting
17338a5c062b: Waiting
18237a144c3e: Waiting
9ef729ad546f: Waiting
image operating system "windows" cannot be used on this platform
```

Docker version: 19.03.13

**Comment by cpuguy83** [comment] 2020-11-20 19:25
Are you on Windows? That digest is for a Windows image.

**Comment by cpuguy83** [comment] 2020-11-20 19:28
Here's the (current) manifests referenced from the sha for library/openjdk:8-jre

The manifest with the sha you specified in your command is for Windows.

```json
{
  "manifests": [
    {
      "digest": "sha256:7ee341dd70298e4ad59e1c0c1b00648aaaa097a9e6f1ae1c66af1e4b9c473737",
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "platform": {
        "architecture": "amd64",
        "os": "linux"
      },
      "size": 1581
    },
    {
      "digest": "sha256:454a0881d85220bb74d33e2e6e5c937ddb8f649fe13682f7dae7d39599b0b68e",
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "platform": {
        "architecture": "amd64",
        "os": "windows",
        "os.version": "10.0.17763.1577"
      },
      "size": 2357
    },
    {
      "digest": "sha256:1655f064c3c6ad37b09d73ee5d4f89a519d5a10ab40ac5ac0e414815d23dc535",
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "platform": {
        "architecture": "amd64",
        "os": "windows",
        "os.version": "10.0.14393.4046"
      },
      "size": 2280
    }
  ],
  "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
  "schemaVersion": 2
}
```

**Comment by cpuguy83** [comment] 2020-11-20 19:43
Closing because the digest of the manifest you fetched in the first is Linux, the digest that you specified is Windows, so it seems like this is working as expected (can't run a Windows image on Linux node).

**Closed by cpuguy83** 2020-11-20 19:43 UTC

**Comment by yamlCase** [comment] 2020-11-20 20:06
It won't matter.  If you're on linux it will fail because of Windows fs image. If you're on windows, the same image will fail because of linux fs images

**Comment by cpuguy83** [comment] 2020-11-20 20:11
The problem is the SHA you pulled is specifically for Windows. The image needs to match the host platform.
