### ISSUE TITLE
/var/lib/docker gets spammed on container build...

### ISSUE THREAD

**Issue by kratan** [docker/for-linux#64] opened 2017-07-20 07:19 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
Dockerfile:
```
FROM ubuntu:latest

ENV UID=58473773 USERNAME=ad-user

RUN apt-get -y update && \
    apt-get -y install sudo && \
   useradd -ms /bin/bash --uid ${UID} ${USERNAME} && \
    echo "${USERNAME} ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/${USERNAME} && \
    chmod 0440 /etc/sudoers.d/${USERNAME}

CMD ["su", "-", "${USERNAME}", "-c", "/bin/bash"]
```
Container should build normally.

Sense behind that dockerfile is to have a container, which an AD user builds an run and he should able to sudo as root user but as standard he should have his uid to be the same as outside the container...

### Actual behavior
if i build the container, my /var/lib/docker is spammed until hdd is full

### Steps to reproduce the behavior
use the dockerfile above with docker 17.06.0-ce and build it with 
```
docker build -t sample_ubuntu .
```

your /var/lib/docker should get spammed....

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:17:22 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:16:12 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-3-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 160
Total Memory: 503.9GiB
Name: i31ForHLR5
ID: H67D:PCNF:IMBI:UG47:3VTC:JFQ3:LTNR:HTHZ:E6SN:A33M:ZDUV:4GVS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by thaJeztah** [comment] 2017-10-08 00:12
Thanks for reporting; this is a duplicate of https://github.com/moby/moby/issues/5419 (https://github.com/moby/moby/issues/28920), and the discussion on that issue contains more information about the underlying problem.

As a workaround, you can create the user with the `-l` (`--no-log-init`) option, to prevent Linux from reserving space for all the users in between.

I'll close this issue here, to prevent the discussion from diverging, but feel free to continue the conversation.

**Closed by thaJeztah** 2017-10-08 00:12 UTC
