### ISSUE TITLE
error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.27/containers/json: read unix @->/var/run/docker.sock: read: connection reset by peer

### ISSUE THREAD

**Issue by WUMUXIAN** [docker/for-linux#435] opened 2018-09-10 08:33 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Steps to reproduce the behavior

**Output of `docker version`:**

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:31:19 2017
 OS/Arch:      linux/amd64
error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.27/version: read unix @->/var/run/docker.sock: read: connection reset by peer
```

**Output of `docker info`:**

```
error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.27/containers/json: read unix @->/var/run/docker.sock: read: connection reset by peer
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

- AWS Instance - m5.large
- AMI - k8s-1.9-debian-stretch-amd64-hvm-ebs-2018-03-11 (ami-a5c90ed8)

Cause:

The disk is full, however, I can't use any `docker system prune` `docker rmi $(docker images -qa)` or anything, because all docker xxx results to:
```
error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.27/containers/json: read unix @->/var/run/docker.sock: read: connection reset by peer
```

**Comment by thaJeztah** [comment] 2018-11-13 18:01
If the disk is full, and the daemon is no longer able to start because of that, you can't run docker commands (therefore the docker cli fails to connect with the daemon; it's not running, or failing to perform its actions).

I don't think this is a bug, so I'll close this issue, but feel free to continue the conversation

**Closed by thaJeztah** 2018-11-13 18:01 UTC

**Comment by susmithaMaheshkumar** [comment] 2018-11-26 19:33
I have the same issues. But i still have 12G of space left in my SD card. What could be error ?

Filesystem      Size  Used Avail Use% Mounted on
/dev/root        14G  1.5G   12G  11% /
devtmpfs        427M     0  427M   0% /dev
tmpfs           431M     0  431M   0% /dev/shm
tmpfs           431M   17M  415M   4% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           431M     0  431M   0% /sys/fs/cgroup
/dev/mmcblk0p1   64M   31M   34M  48% /boot
tmpfs            87M     0   87M   0% /run/user/1000

**Comment by stunum** [comment] 2019-03-09 10:43
I had the same problem on a VPS！
<img width="393" alt="df1" src="https://user-images.githubusercontent.com/12244421/54070437-13bc9180-429b-11e9-97fe-ab0bc272b3a4.png">
<img width="921" alt="dk" src="https://user-images.githubusercontent.com/12244421/54070438-13bc9180-429b-11e9-994a-5f9df5581402.png">
<img width="984" alt="hh" src="https://user-images.githubusercontent.com/12244421/54070439-14552800-429b-11e9-8bba-c1ada2512d17.png">

**Comment by logoff** [comment] 2019-08-24 11:15
I can confirm that it happens on my Raspberry Pi 3 with this data:

```
$ uname -a
Linux rpi3 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
```
```
$ lsb_release -a 
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```
```
$ docker --version
Docker version 19.03.1, build 74b1e89
```
And enough free space:
```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        14G  2,9G   11G  22% /
devtmpfs        484M     0  484M   0% /dev
tmpfs           488M     0  488M   0% /dev/shm
tmpfs           488M  7,2M  481M   2% /run
tmpfs           5,0M  4,0K  5,0M   1% /run/lock
tmpfs           488M     0  488M   0% /sys/fs/cgroup
/dev/mmcblk0p1  253M   40M  213M  16% /boot
/dev/sda1       1,8T  1,2T  572G  68% /media/data
tmpfs            98M     0   98M   0% /run/user/1000
```

**Comment by Lentolo** [comment] 2019-09-06 14:24
Same problem also for me with raspberry:

```
uname -a
----------------
Linux stspiserver 4.19.58-v7+ #1245 SMP Fri Jul 12 17:25:51 BST 2019 armv7l GNU/Linux

lsb_release -a
----------------
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 9.9 (stretch)
Release:        9.9
Codename:       stretch

docker --version
----------------
Docker version 19.03.1, build 74b1e89

df -h
----------------
Filesystem                      Size  Used Avail Use% Mounted on
/dev/root                        29G  5.4G   22G  20% /
devtmpfs                        459M     0  459M   0% /dev
tmpfs                           464M     0  464M   0% /dev/shm
tmpfs                           464M   47M  417M  11% /run
tmpfs                           5.0M  4.0K  5.0M   1% /run/lock
tmpfs                           464M     0  464M   0% /sys/fs/cgroup
/dev/mmcblk0p1                   43M   23M   20M  53% /boot
/dev/sda1                       458G   34G  401G   8% /data
tmpfs                            93M     0   93M   0% /run/user/1001
overlay                          29G  5.4G   22G  20% /var/lib/docker/overlay2/21af7e1d14f2c21532a9d2aba598428c7042187cc51150dc7cee210e09386e63/merged
overlay                          29G  5.4G   22G  20% /var/lib/docker/overlay2/37e09c9f9c2d86e31260a832c740be964d5624ade3128eba2bdc3fb7f4a882f4/merged
overlay                          29G  5.4G   22G  20% /var/lib/docker/overlay2/993c41bdad93af1ba5ac37bf5ee65fc129f74e32b7dcbe667a48bd0669b95d88/merged
overlay                          29G  5.4G   22G  20% /var/lib/docker/overlay2/9d2c3644559de35b8ce1ec07149b7b41531ec234adc27568041a08a072ae4e48/merged

```

**Comment by hantmac** [comment] 2019-10-29 11:17
I met this problem because of memory not enough, when I increase the memory the problem solved.

**Comment by hmtai** [comment] 2020-01-09 07:28
I also meet the same issue:
```
# docker ps
error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/json: read unix @->/var/run/docker.sock: read: connection reset by peer
```
However my host has enough memory and disk.I delete the all the docker directories `/var/lib/docker` `/var/lib/docker-engine` `/var/lib/docker-shim`.Then the docker restart successfully.

**Comment by tslmy** [comment] 2020-04-12 06:50
Note to self:
1. Ensure that your docker deamon is running: `sudo dockerd`
  -  If `failed to start daemon: error while opening volume store metadata database: timeout`, then `sudo rm /var/lib/docker/volumes/metadata.db` and retry.
  - If `failed to start daemon: pid file found, ensure docker is not running or delete /var/run/docker.pid`, then `sudo rm /var/run/docker.pid` and retry.
then retry.

**Comment by nwmcsween** [comment] 2020-05-11 16:42
This is still an issue, I have 16GB free, im assuming it's some sort of corruption in /var/lib from docker itself (disks are on raid10).

**Comment by matthsena** [comment] 2020-06-17 23:32
Applying  these commands worked for me:

`sudo service docker stop && \`
`sudo rm -rf /var/lib/docker && \`
` sudo service docker start`

**Comment by nwmcsween** [comment] 2020-06-18 01:46
Nuking all of Dockers state isn't a fix, considering this is 3 years old and no progress means I'm not going to consider docker production ready.

**Comment by thaJeztah** [comment] 2020-06-18 12:00
> considering this is 3 years old and no progress means I'm not going to consider docker production ready.

I agree that nuking Docker state isn't a fix, but a workaround, so (generally) not recommended. This issue has collected various comments that are unrelated to the original report, but may seem similar. The `error during connect` error means that the docker client is unable to connect to the daemon, which can have many reasons. The daemon may not have been started, a networking connection could be causing an issue (if the daemon is remote), or any reason the daemon failed to start (logs for the daemon and/or system logs may provide more details in that situation)

**Comment by alexandruge** [comment] 2020-06-24 10:49
So I have this issue to on RPI 4. Enough mem and disk space. 
The thing is the docker containers are running:

**pi@raspberrypi:~ $ docker ps
error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/json: read unix @->/var/run/docker.sock: read: connection reset by peer**
pi@raspberrypi:~ $ docker info
Containers: 8
 Running: 7
 Paused: 0
 Stopped: 1
Images: 19
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 1.0.0~rc6+dfsg1-3
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.19.97-v7l+
Operating System: Raspbian GNU/Linux 10 (buster)
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 3.814GiB
Name: raspberrypi
ID: DNXZ:KM6S:TRU5:N3XX:2TIQ:47HC:JKL5:KBPD:NJUZ:D43B:NBIE:YKGM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: alifie
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
pi@raspberrypi:~ $ docker --version
Docker version 18.09.1, build 4c52b90
pi@raspberrypi:~ $ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        15G  9.1G  4.4G  68% /
devtmpfs        1.8G     0  1.8G   0% /dev
tmpfs           2.0G     0  2.0G   0% /dev/shm
tmpfs           2.0G  9.9M  1.9G   1% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/mmcblk0p1  253M   53M  200M  21% /boot
/dev/sda5       1.9T  1.8T   90G  96% /mnt/usbHDD
tmpfs           391M     0  391M   0% /run/user/1000

After restart of RPI the containers come up as expected.

**Comment by juampe** [comment] 2020-07-17 12:38
https://github.com/moby/moby/issues/17846

    Stop docker daemon
    sudo rm /var/lib/docker/network/files/local-kv.db
    Start docker daemon

**Comment by IsusRamzy** [comment] 2024-12-13 22:05
Same error! Enough storage, please re-open!

**Comment by ramzes13** [comment] 2025-01-08 09:56
I have this error after I migrate ubuntu from 22.04 to 24.04 and reinstall the docker. I tried to fix it multiple times

**Comment by ursamiklavcic** [comment] 2025-01-09 14:09
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create": dial unix /var/run/docker.sock: connect: permission denied. 

Please do something!

**Comment by IsusRamzy** [comment] 2025-01-09 17:14
> docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create": dial unix /var/run/docker.sock: connect: permission denied.
> 
> Please do something!

Use sudo.

**Comment by ursamiklavcic** [comment] 2025-01-10 07:46
> > docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create": dial unix /var/run/docker.sock: connect: permission denied.
> > Please do something!
> 
> Use sudo.

That would be possible, but unfortunately I'm working on HPC cluster... I found a work around singularity docker pull ...
