### ISSUE TITLE
Where is the module that handles network requests in Docker CE?

### ISSUE THREAD

**Issue by VxBPMN4MS** [docker/for-linux#1088] opened 2020-08-20 10:14 UTC
I am a novice at reading Docker source code, now encountered some problems.
In Docker-CE 19.03, external network requests are sent to the container, and where is the module that handles these requests in the source code (or. Go file)?More specifically, I've deployed a microservice in Docker that the outside world can access through RESTful API, I want to set the probe in this process , but I can't find the exact location. I am looking forward to your reply .

**Comment by thaJeztah** [comment] 2020-08-24 12:41
Docker containers are handled by linux namespaces, and a container (by default) gets its own Linux networking namespace and a virtual network interface that's added to that namespace. When you "publish" / map a port, iptables rules are added to map the host's port to the container's port.

The networking stack is mostly handled through libnetwork, which can be found in https://github.com/docker/libnetwork.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2020-08-24 12:41 UTC

**Comment by VxBPMN4MS** [comment] 2020-08-25 04:49
> Docker containers are handled by linux namespaces, and a container (by default) gets its own Linux networking namespace and a virtual network interface that's added to that namespace. When you "publish" / map a port, iptables rules are added to map the host's port to the container's port.
> 
> The networking stack is mostly handled through libnetwork, which can be found in https://github.com/docker/libnetwork.
> 
> Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
> but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;
> 
> * the Docker Support Forums - https://forums.docker.com
> * the [Docker community Slack channel](http://dockr.ly/slack)
> 
> I'm closing this issue because this is not a bug, but feel free to continue the conversation

Thanks for your reply. I used the issue tracker by mistake. I am sorry for this and will correct it in the future.
In a few days ago, I tried launched a discussion in [](https://forums.docker.com), however, no one answers. Maybe my question was stupid.
------------------------------------
I followed your tips and tried a few:
1. I found "libnetwork". Since I'm using Docker-CE, its location is [](https://github.com/docker/docker-ce/tree/master/components/engine/vendor/github.com/docker/libnetwork)
2. I added "logrus.info("XXX--wj")" to the source code that looks like it handles network requests (for example, including the keyword "ResponseWriter ").
Before you reply, I have made such modifications in more places.
3. I completely compiled and generated Docker-CE_19.03.deb, Docker-CE-CLI_19.03.deb.
4. I installed the generated installation package on the new computer, deployed the microservice, and used the following command several times
`curl http://localhost:8001/docker ; jourctl -u docker.service > log.txt`
5. When I look at the log file, I expect that every time I visit the microservice, the log will leave a mark I made ("XXX -- wj"), but it doesn't show up.
This is the log file. [log.txt](https://github.com/docker/for-linux/files/5121372/log.txt)
Note that the mark in these logs were generated during the container initialization process, and none of the mark I expected appeared when visiting the microservice.
-------------------------------------
I'm thinking, maybe my idea is impossible, or I've missed some key points, could you give me more help or tips?

**Comment by thaJeztah** [comment] 2020-08-25 13:00
> When I look at the log file, I expect that every time I visit the microservice, the log will leave a mark I made ("XXX -- wj"), but it doesn't show up.

No, docker itself doesn't handle network traffic; it sets up networking, but no network traffic of your container will go through the docker code.

**Comment by VxBPMN4MS** [comment] 2020-08-25 14:23
Thank you for answering it again. My problem is completely solved.
