### ISSUE TITLE
19.03.5: This QEMU binary requires the membarrier system call.

### ISSUE THREAD

**Issue by matwey** [docker/for-linux#899] opened 2020-01-17 11:05 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

Hello, I am running docker 19.03.5 from openSUSE Leap 15.1 distro. I also use qemu 3.1.1.1 binfmt binary translators. 

### Steps to reproduce the behavior

When I run `docker build --platform=linux/arm/v7 -t myimage .` I see the following

```
This QEMU binary requires the membarrier system call.
Please upgrade your system to a newer version of Linux
```

and then the execution failure follows immediately.
I believe this is due to `membarrier` disabled in default docker seccomp profile.

### Expected behavior

Build success

### Actual behavior

```
This QEMU binary requires the membarrier system call.
Please upgrade your system to a newer version of Linux
```

**Output of `docker version`:**

```
Client:
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838f1
 Built:             Thu Dec 12 12:00:00 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838f1
  Built:            Thu Dec 12 12:00:00 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.1.3_catatonit
  GitCommit:
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc.)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 2
 Server Version: 19.03.5
 Storage Driver: btrfs
  Build Version: Btrfs v4.19.1 
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: oci runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.12.14-lp151.28.36-default
 Operating System: openSUSE Leap 15.1
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.846GiB
 Name: localhost
 ID: RKO5:IW45:4XEA:SM3G:CIMV:LNYU:WUC6:R7LF:MNQO:MRGV:GHQD:IACZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by Nazgolze** [comment] 2020-01-21 09:46
I'm running into the same membarrier issue with recent (3.10 and later) alpine images.
I can confirm that it's precisely because membarrier is not whitelisted in the default docker seccomp profile (musl is using it)

**Comment by thaJeztah** [comment] 2020-01-22 10:47
@akihirosuda @tonistiigi ptal

**Comment by tonistiigi** [comment] 2020-01-22 16:37
cc @justincormack

**Comment by Julio-Guerra** [comment] 2020-03-20 17:08
As far as I understood the issue [we also faced in node's libuv], it is fixed by the update of libseccomp in docker v19.03.8: https://github.com/moby/moby/commit/96896f2d0bc16269778dd4f60a4920b49953ffed

**Comment by matwey** [comment] 2020-03-21 14:11
> As far as I understood the issue [we also faced in node's libuv], it is fixed by the update of libseccomp in docker v19.03.8: [moby/moby@96896f2](https://github.com/moby/moby/commit/96896f2d0bc16269778dd4f60a4920b49953ffed)

No, it doesn't. The commit you are referring existed in v19.03.5. The commit message also states that `membarrier` is NOT added.

**Comment by Julio-Guerra** [comment] 2020-03-21 15:33
My bad indeed. How do you explain the syscall is permitted on recent docker versions then?

**Comment by thaJeztah** [comment] 2020-05-27 18:03
A PR was merged to add this sys call to the default seccomp profile; https://github.com/moby/moby/pull/40731
That change is not yet in a release though, but you could either disabled libseccomp for the container, or specify a custom profile.

Let me close this one, but feel free to continue the conversation

**Closed by thaJeztah** 2020-05-27 18:03 UTC
