### ISSUE TITLE
issues with iptables 1.8.0; 1.6.2 works

### ISSUE THREAD

**Issue by plutext** [docker/for-linux#481] opened 2018-11-12 04:43 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

Docker would work as expected with iptables 1.8.0

### Actual behavior

Various iptables related errors, such as unknown option --dport

Workaround is to downgrade iptables to 1.6.2

See also https://github.com/docker/for-linux/issues/364#issuecomment-429559614

### Steps to reproduce the behavior

**Output of `docker version`:**

```
Docker version 18.06.1-ce, build e68fc7a215
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

Manjaro

**Comment by thaJeztah** [comment] 2018-11-12 21:45
Looks like this is a duplicate of https://github.com/moby/moby/issues/38099, and due to iptables 1.8 now using nft. 

A fix for this was merged in libnetwork; https://github.com/docker/libnetwork/pull/2285, and being in the engine through https://github.com/moby/moby/pull/38120, which will be included in an upcoming patch release for Docker 18.09.

Not sure if the package-name is the same on your distro, but this comment https://github.com/moby/moby/issues/38099#issuecomment-434894468 explains how to install the "legacy" version of iptables, which should not show this problem.

Let me close this one, as this is resolved on master, and will be included in a patch release for 18.09

**Closed by thaJeztah** 2018-11-12 21:45 UTC
