### ISSUE TITLE
no docker installed in ubuntu 18.10

### ISSUE THREAD

**Issue by navelal** [docker/for-linux#513] opened 2018-12-06 10:59 UTC
Tried to install though get.docker.com but no sucess.

# This script is meant for quick & easy install via:
#   $ curl -fsSL https://get.docker.com -o get-docker.sh
#   $ sh get-docker.sh

at last used the below and it is SUCCESFUL
used the below command to get this installed.

rootadmin@rootadmin-Virtual-Machine:~$ sudo snap install docker
docker 18.06.1-ce from Docker, Inc (docker-inc) installed

**Comment by navelal** [comment] 2018-12-06 11:00
rootadmin@rootadmin-Virtual-Machine:~$ sudo snap install docker
docker 18.06.1-ce from Docker, Inc (docker-inc) installed

THIS COMMAND INSTALLED DOCKER SUCCESFULLY

**Comment by thaJeztah** [comment] 2018-12-07 23:32
duplicate of https://github.com/docker/for-linux/issues/442

**Closed by thaJeztah** 2018-12-07 23:32 UTC
