### ISSUE TITLE
It's not easy to tell what networks my service is connected to

### ISSUE THREAD

**Issue by kristiehoward** [docker/for-linux#29] opened 2017-06-15 21:10 UTC
### Expected behavior
I can easily find out what network my service is on when I do a `docker service inspect`

### Actual behavior
When I do a `docker service inspect`, I only get `Networks` with an array of "targets" back, which means I have to run an additional `docker network ls`, scroll back up, and match up those network ids to see what networks my service is connected to. I'd like to see the network name next to the target.

`docker service inspect s1`
![image](https://user-images.githubusercontent.com/7132362/27201762-b0b037ea-51d3-11e7-8616-7740cde5ba2d.png)

To try and get that information in one screen:
![image](https://user-images.githubusercontent.com/7132362/27201850-1a167f46-51d4-11e7-82e7-32fe8e094fff.png)

### Information
Client:
 Version:      17.06.0-ce-rc3
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   7953dbc
 Built:        Tue Jun 13 08:32:10 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce-rc3
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   7953dbc
 Built:        Tue Jun 13 08:23:12 2017
 OS/Arch:      linux/amd64
 Experimental: false

### Steps to reproduce the behavior
Create a service connected to a network. Try and see what networks your service is connected to.

**Comment by cpuguy83** [comment] 2017-06-29 15:09
Try with `docker service inspect --pretty`

**Comment by thaJeztah** [comment] 2017-10-08 13:02
Correct, the service "specs" use the unique ID of the network (names are not guaranteed to be unique). The "raw" inspect output shows those ID's, but when using the `--pretty` option, the network-names are resolved and printed;

```bash
$ docker network create -d overlay foobar
qjl8bln19is32c6nguizalvnt

$ docker service create --network foobar --name test nginx:alpine
rt6ruwawmblls97ts937dx0ie

$ docker service inspect --pretty test

ID:		rt6ruwawmblls97ts937dx0ie
Name:		test
Service Mode:	Replicated
 Replicas:	1
Placement:
UpdateConfig:
 Parallelism:	1
 On failure:	pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Update order:      stop-first
RollbackConfig:
 Parallelism:	1
 On failure:	pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Rollback order:    stop-first
ContainerSpec:
 Image:		nginx:alpine@sha256:83f10f82722087e6944e0348b2e64a95baf247135de7c237f4dec7729a386d7f
Resources:
Networks: foobar
Endpoint Mode:	vip
```

Closing this one, because this is the expected behavior

**Closed by thaJeztah** 2017-10-08 13:02 UTC
Labels: Kind/workshop-feedback
