### ISSUE TITLE
Error downloading packages:

### ISSUE THREAD

**Issue by jdzhang1221** [docker/for-linux#311] opened 2018-05-21 09:49 UTC
when i exceute command "sudo yum install docker-ce"
report "docker-ce-18.03.1.ce-1.el7.centos.x86_64: [Errno 256] No more mirrors to try."

**Comment by thaJeztah** [comment] 2018-05-21 23:17
Sounds like you didn't configure your machine to use the docker package repositories.

Please follow the instructions in the installation guide; https://docs.docker.com/install/linux/docker-ce/centos/

I'll close this issue because this looks like a configuration issue, not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2018-05-21 23:17 UTC
