### ISSUE TITLE
Cgroup cpu real-time period error on API create request

### ISSUE THREAD

**Issue by PeterDavidCarter** [docker/for-linux#970] opened 2020-04-05 12:51 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior

I expect a POST request to the Docker container creation endpoint to require the same kernel features as the other methods of Docker container creation. I would expect Docker to have support for Ubuntu 18.04 Server LTS OOTB or for this to be mentioned prominantly in the Engine API. If additional steps are required to configure the distro to work with Docker rest API container creation, I would expect these to be documented somewhere.

### Actual behavior

When attempting to test the Docker container creation functionality using curl, I get the following output:

![image](https://user-images.githubusercontent.com/23146481/78498791-4954d800-7744-11ea-83a1-38666b1b72da.png)

### Steps to reproduce the behavior

**Output of `docker version`:**

```
Docker version 19.03.8, build afacb8b7f0
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 20
  Running: 14
  Paused: 0
  Stopped: 6
 Images: 33
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: pd66q9ae1oo2bilk2o4aqcmwa
  Is Manager: true
  ClusterID: y1qxxb8m26yh4zec9ti48c0mx
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 37.187.158.82
  Manager Addresses:
   37.187.158.82:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-91-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 62.88GiB
 Name: ns326154
 ID: DUW2:6ULU:7YMH:NNHN:ITF7:A4PZ:WY64:XFSB:RWUD:6UE4:X4J3:IHJO
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: REDACTED
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: API is accessible on http://0.0.0.0:1112 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

Dedicated server.

**Comment by cpuguy83** [comment] 2020-04-05 16:21
The message is saying that your kernel does not have support for real-time. This is expected on the stock Ubuntu kernel.

What docs are you referring to?

**Comment by PeterDavidCarter** [comment] 2020-04-05 16:41
So I can't use the Docker API with a stock Linux kernel? Seems like this should be mentioned on https://docs.docker.com/engine/api/v1.40/#section/Authentication or somewhere similar. Really messes with my use-case.

**Comment by PeterDavidCarter** [comment] 2020-04-05 16:42
Don't see why Docker can support creating a container via a docker run etc, but not via REST request on the same kernel.

**Comment by cpuguy83** [comment] 2020-04-05 16:57
`docker run` is using the REST API.
The issue is you are trying to set the cpu-rt-period which is dependent on support in the kernel.

**Comment by PeterDavidCarter** [comment] 2020-04-05 17:02
I'm not trying to set anything. I'm just making a request to the REST API using the exact example json given on the Docker site which makes no explicit mention of that setting:

[
  {
    "Id": "8dfafdbc3a40",
    "Names": [
      "/boring_feynman"
    ],
    "Image": "ubuntu:latest",
    "ImageID": "d74508fb6632491cea586a1fd7d748dfc5274cd6fdfedee309ecdcbc2bf5cb82",
    "Command": "echo 1",
    "Created": 1367854155,
    "State": "Exited",
    "Status": "Exit 0",
    "Ports": [
      {
        "PrivatePort": 2222,
        "PublicPort": 3333,
        "Type": "tcp"
      }
    ],
    "Labels": {
      "com.example.vendor": "Acme",
      "com.example.license": "GPL",
      "com.example.version": "1.0"
    },
    "SizeRw": 12288,
    "SizeRootFs": 0,
    "HostConfig": {
      "NetworkMode": "default"
    },
    "NetworkSettings": {
      "Networks": {
        "bridge": {
          "NetworkID": "7ea29fc1412292a2d7bba362f9253545fecdfa8ce9a6e37dd10ba8bee7129812",
          "EndpointID": "2cdc4edb1ded3631c81f57966563e5c8525b81121bb3706a9a9a3ae102711f3f",
          "Gateway": "172.17.0.1",
          "IPAddress": "172.17.0.2",
          "IPPrefixLen": 16,
          "IPv6Gateway": "",
          "GlobalIPv6Address": "",
          "GlobalIPv6PrefixLen": 0,
          "MacAddress": "02:42:ac:11:00:02"
        }
      }
    },
    "Mounts": [
      {
        "Name": "fac362...80535",
        "Source": "/data",
        "Destination": "/data",
        "Driver": "local",
        "Mode": "ro,Z",
        "RW": false,
        "Propagation": ""
      }
    ]
  },
  {
    "Id": "9cd87474be90",
    "Names": [
      "/coolName"
    ],
    "Image": "ubuntu:latest",
    "ImageID": "d74508fb6632491cea586a1fd7d748dfc5274cd6fdfedee309ecdcbc2bf5cb82",
    "Command": "echo 222222",
    "Created": 1367854155,
    "State": "Exited",
    "Status": "Exit 0",
    "Ports": [],
    "Labels": {},
    "SizeRw": 12288,
    "SizeRootFs": 0,
    "HostConfig": {
      "NetworkMode": "default"
    },
    "NetworkSettings": {
      "Networks": {
        "bridge": {
          "NetworkID": "7ea29fc1412292a2d7bba362f9253545fecdfa8ce9a6e37dd10ba8bee7129812",
          "EndpointID": "88eaed7b37b38c2a3f0c4bc796494fdf51b270c2d22656412a2ca5d559a64d7a",
          "Gateway": "172.17.0.1",
          "IPAddress": "172.17.0.8",
          "IPPrefixLen": 16,
          "IPv6Gateway": "",
          "GlobalIPv6Address": "",
          "GlobalIPv6PrefixLen": 0,
          "MacAddress": "02:42:ac:11:00:08"
        }
      }
    },
    "Mounts": []
  },
  {
    "Id": "3176a2479c92",
    "Names": [
      "/sleepy_dog"
    ],
    "Image": "ubuntu:latest",
    "ImageID": "d74508fb6632491cea586a1fd7d748dfc5274cd6fdfedee309ecdcbc2bf5cb82",
    "Command": "echo 3333333333333333",
    "Created": 1367854154,
    "State": "Exited",
    "Status": "Exit 0",
    "Ports": [],
    "Labels": {},
    "SizeRw": 12288,
    "SizeRootFs": 0,
    "HostConfig": {
      "NetworkMode": "default"
    },
    "NetworkSettings": {
      "Networks": {
        "bridge": {
          "NetworkID": "7ea29fc1412292a2d7bba362f9253545fecdfa8ce9a6e37dd10ba8bee7129812",
          "EndpointID": "8b27c041c30326d59cd6e6f510d4f8d1d570a228466f956edf7815508f78e30d",
          "Gateway": "172.17.0.1",
          "IPAddress": "172.17.0.6",
          "IPPrefixLen": 16,
          "IPv6Gateway": "",
          "GlobalIPv6Address": "",
          "GlobalIPv6PrefixLen": 0,
          "MacAddress": "02:42:ac:11:00:06"
        }
      }
    },
    "Mounts": []
  },
  {
    "Id": "4cb07b47f9fb",
    "Names": [
      "/running_cat"
    ],
    "Image": "ubuntu:latest",
    "ImageID": "d74508fb6632491cea586a1fd7d748dfc5274cd6fdfedee309ecdcbc2bf5cb82",
    "Command": "echo 444444444444444444444444444444444",
    "Created": 1367854152,
    "State": "Exited",
    "Status": "Exit 0",
    "Ports": [],
    "Labels": {},
    "SizeRw": 12288,
    "SizeRootFs": 0,
    "HostConfig": {
      "NetworkMode": "default"
    },
    "NetworkSettings": {
      "Networks": {
        "bridge": {
          "NetworkID": "7ea29fc1412292a2d7bba362f9253545fecdfa8ce9a6e37dd10ba8bee7129812",
          "EndpointID": "d91c7b2f0644403d7ef3095985ea0e2370325cd2332ff3a3225c4247328e66e9",
          "Gateway": "172.17.0.1",
          "IPAddress": "172.17.0.5",
          "IPPrefixLen": 16,
          "IPv6Gateway": "",
          "GlobalIPv6Address": "",
          "GlobalIPv6PrefixLen": 0,
          "MacAddress": "02:42:ac:11:00:05"
        }
      }
    },
    "Mounts": []
  }
]

**Comment by cpuguy83** [comment] 2020-04-05 17:32
In your request you have:
```
    "CpuRealtimePeriod": 1000000,
    "CpuRealtimeRuntime": 10000
```

This is trying to set cgroup parameters that are only available on real-time kernels.

It looks like you took this from the example data in the documentation. That data is only there to show you what a value might look like.

It should be enough to create a container with only:

```
{
  "Image": "hello-world:latest"
}
```

**Comment by PeterDavidCarter** [comment] 2020-04-05 17:44
Useful info. You might want to update the docs though, as they don't seem exactly forthcoming on required fields.

**Comment by thaJeztah** [comment] 2020-05-27 17:48
Let me close this issue because the original problem seems to be resolved.

The API reference is generated from the swagger definition in https://github.com/moby/moby/blob/master/api/swagger.yaml, contributions are always welcome to improve

**Closed by thaJeztah** 2020-05-27 17:48 UTC
