### ISSUE TITLE
Docker Exec does not resize terminal on container

### ISSUE THREAD

**Issue by mabombo** [docker/for-linux#314] opened 2018-05-22 08:42 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Host with docker installed (stty -a)
```
[~]# stty -a
speed 38400 baud; rows 42; columns 210; line = 0;
..........................
..........................
```
### Shell inside a container (docker exec -it 9804cf214e7e21a3b63a7a227512d93ba5b4ac4df0c7ef7d01a1b7a2b5e106e6 /bin/bash)
```
[~]# stty -a
speed 38400 baud; rows 42; columns 210; line = 0;
...........................
...........................
```

### Host with docker installed (stty -a)
```
[~]# stty -a
speed 38400 baud; rows 42; columns 210; line = 0;
..........................
..........................
```
### Shell inside a container (docker exec -it 9804cf214e7e21a3b63a7a227512d93ba5b4ac4df0c7ef7d01a1b7a2b5e106e6 /bin/bash)
```
[~]# stty -a
speed 38400 baud; rows 0; columns 0; line = 0;
...........................
...........................
```
### Steps to reproduce the behavior

```
[ ~]# docker pull ubuntu
[ ~]# docker run -d -it ubuntu /bin/bash
16dffb0af8ab1fd0bc755ecb8be39b739d6408f2009bf028483723db5d6ff6a9
[~]# docker exec -it 16dffb0af8ab1fd0bc755ecb8be39b739d6408f2009bf028483723db5d6ff6a9 /bin/bash
root@16dffb0af8ab:/# 
root@16dffb0af8ab:/# stty -a
speed 38400 baud; rows 0; columns 0; line = 0;

Sometime on first exec the rows and columns are set correctly, try more time to exec inside a container
The problem is for all images. With previous Docker CE version the problem disappear .
```
**Output of `docker version`:**

```
Docker version 18.03.1-ce, build 9ee9f40
```

**Output of `docker info`:**

```
Containers: 15
 Running: 15
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.5 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 31.25GiB
Name: epress02docker
ID: VX3P:3XSO:6BQJ:V6AS:HZYH:CCEZ:7X3G:XSBX:ARWN:KCR4:JNPD:IMOA
Docker Root Dir: /dockerStorage
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

OS Host with docker installed
[~]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.5 (Maipo)

Tested Image Ubuntu

**Comment by thaJeztah** [comment] 2018-05-22 22:21
This looks like the same issue as reported in https://github.com/moby/moby/issues/35407

The cause is a race-condition in the resize-event being sent to the container. 
There's no fix available yet, but as a workaround; if you resize your terminal-window, the container should pick up the correct size.

**Comment by danielpops** [comment] 2018-05-25 17:56
Here is another workaround:

`sudo docker exec -it -e COLUMNS="`tput cols`" -e LINES="`tput lines`" container_name bash`

**Comment by mabombo** [comment] 2018-05-25 18:04
Thank you best regards MAURO

Inviato da iPhone

**Comment by thaJeztah** [comment] 2018-06-08 22:45
Fixed on master through https://github.com/moby/moby/pull/37172

**Closed by thaJeztah** 2018-06-08 22:45 UTC
Labels: bug

**Comment by haridsv** [comment] 2019-01-10 09:19
Workaround by @danielpops doesn't seem to help. It does set `ROWS` and `COLUMNS`, but `stty -a` still shows 0 rows and columns and this is problematic for JRuby and JRuby based interactive programs as discussed here: https://stackoverflow.com/questions/49649449/hbase-shell-crash-after-backspace

```
$ echo $LINES $COLUMNS
107 364
$ stty -a
speed 38400 baud; rows 0; columns 0; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; flush = ^O; min = 1; time = 0;
-parenb -parodd cs8 -hupcl -cstopb cread -clocal -crtscts -cdtrdsr
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc -ixany -imaxbel -iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke
```

**Comment by thaJeztah** [comment] 2019-02-21 20:52
There was a follow-up pull request that's been merged in the cli, and should fix the remaining issues with resizing; https://github.com/docker/cli/pull/1529 (it's not in a release yet though)
