### ISSUE TITLE
No /dev/init in container

### ISSUE THREAD

**Issue by vanko69** [docker/for-linux#120] opened 2017-10-05 11:06 UTC
I am using:
Ubuntu 16.04.3
Kernel 4.4.0-96-generic

docker version:
```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64
Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

docker info:
```
Containers: 19
 Running: 18
 Paused: 0
 Stopped: 1
Images: 30
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /docker/aufs
 Backing Filesystem: extfs
 Dirs: 266
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-96-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 40
Total Memory: 125.8 GiB
Name: cvic-srv3
ID: 4QMB:GOVM:7RFC:A65C:3FZE:QYOI:JW73:KO56:VRZA:O4C6:D7TE:EYBC
Docker Root Dir: /docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

/etc/docker/daemon.json:
`{"init": true}`

NO /dev/init in containers.
I rebooted the machine more than 10 times. Try different version of docker. No effect.

**Comment by thaJeztah** [comment] 2017-10-07 00:23
I'm not able to reproduce;

First check if the `docker-init` binary is installed on the host;

```bash
$ which docker-init
/usr/bin/docker-init
```

Create configuration file:

```bash
$ mkdir -p /etc/docker/
$ echo '{"init":true}' > /etc/docker/daemon.json

$ systemctl restart docker
```

Now run a container an verify the `init` is inserted into the container:

```bash
$ docker run --rm busybox /dev/init -h
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
03b1be98f3f9: Pull complete
Digest: sha256:3e8fa85ddfef1af9ca85a5cfb714148956984e02f00bec3f7f49d3925a91e0e7
Status: Downloaded newer image for busybox:latest
init (tini version 0.13.0 - git.949e6fa)
Usage: init [OPTIONS] PROGRAM -- [ARGS] | --version

Execute a program under the supervision of a valid init process (init)

Command line options:

  --version: Show version and exit.
  -h: Show this help message and exit.
  -s: Register as a process subreaper (requires Linux >= 3.4).
  -v: Generate more verbose output. Repeat up to 3 times.
  -g: Send signals to the child's process group.
  -l: Show license and exit.

Environment variables:

  TINI_SUBREAPER: Register as a process subreaper (requires Linux >= 3.4)
  TINI_VERBOSITY: Set the verbosity level (default: 1)
```

Tested on:


```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
 
Note that changing the `init` option on the daemon will only affect containers that are started _after_ the configuration was changed, not containers that already exist.

I'm closing this issue because I'm not able to reproduce, but feel free to continue the conversation if you think I closed by mistake, or have additional information

**Closed by thaJeztah** 2017-10-07 00:23 UTC

**Comment by vanko69** [comment] 2017-10-09 07:41
Thank you. I will investigate.
