### ISSUE TITLE
docker image filter returns always 0

### ISSUE THREAD

**Issue by drpaneas** [docker/for-linux#220] opened 2018-02-05 12:32 UTC
* [x] This is a bug report

### Expected behavior

I would expect, when filtering does **not** find the string, to simply return a non-zero value.

```bash
panos@panos:~> docker images --filter reference=alpine:3.5
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
alpine              3.5                 37c7be7a096b        4 months ago        3.99MB
panos@panos:~> echo $?
0

panos@panos:~> docker images --filter reference=asdasdasdasdasd
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
panos@panos:~> echo $?
1
```

### Actual behavior

```bash
panos@panos:~> docker images --filter reference=alpine:3.5
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
alpine              3.5                 37c7be7a096b        4 months ago        3.99MB
panos@panos:~> echo $?
0

panos@panos:~> docker images --filter reference=asdasdasdasdasd
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
panos@panos:~> echo $?
0
```

### Steps to reproduce the behavior

```bash
panos@panos:~> docker images --filter reference=asdasdasdasdasd
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
panos@panos:~> echo $?
0
```

**Output of `docker version`:**

```
panos@panos:~> docker --version
Docker version 17.09.1-ce, build f4ffd2511ce9
```

**Output of `docker info`:**

```
panos@panos:~> docker info
Containers: 20
 Running: 0
 Paused: 0
 Stopped: 20
Images: 41
Server Version: 17.09.1-ce
Storage Driver: btrfs
 Build Version: Btrfs v4.14.1
 Library Version: 102
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: oci runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: N/A (expected: )
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.14.15-1-default
Operating System: openSUSE Tumbleweed
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.473GiB
Name: panos.suse.de
ID: FAF2:J5GJ:ZYZO:M6FG:I6NN:CUZZ:36UR:OM3B:O2D5:ZPSL:S4HT:OQLK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by drpaneas** [comment] 2018-03-20 13:20
Anyone? It's been over a month and there's no response. Please comment even if this is not considered to be a bug, then just *close* it.

**Comment by vdemeester** [comment] 2018-03-20 14:31
@drpaneas sorry for the long delay :bowing_man: . So, on that issue, I really think this is an expected behavior. The command lists images and you can *filter* the result. The fact that the filtering ends up with an empty list is not an error, just like having an empty list (when there is not yet any images on the docker daemon) is not one.

If you try to inspect an image though, using `docker image inspect asdasdasdasdasd`, if it's not found, it will return an error.

With that said, I'm gonna go ahead and closing it as it's an expected behavior, but feel free to discuss more if you think it's not :angel:

**Closed by vdemeester** 2018-03-20 14:31 UTC

**Comment by adubkov** [comment] 2019-02-06 20:32
@vdemeester 

First of all this is actually important change which may affect many people scripts. So we have to be carefully when changing it.

I partially agree with you about `--filter` argument behaviour (however it is also arguable).

But when I explicitly run:
```
 docker images myimage:latest
```

I do expect it will print an image which exactly matched an argument only if the image is exist otherwise it should return non zero status code because it can not find the image. 


Also I would add:
```
docker image 98bda94a92b2
```
