### ISSUE TITLE
Configuration of ulimit nofile didn't work 

### ISSUE THREAD

**Issue by Ducatel** [docker/for-linux#541] opened 2019-01-02 16:36 UTC
Hi,

* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

Impossible to set ulimits for dockerd

On system with custom ulimits, running command like bellow should return the system value
```
docker run --rm centos:7 /bin/bash -c 'ulimit -Hn && ulimit -Sn'
4096
1024
```

### Actual behavior

Return a default value.

### Steps to reproduce the behavior

1. Install ubuntu 18.04.1 x64 server
2. install docker and microk8s with snap

#### Way 1
3.  set `/etc/security/limits.conf`  with `*       -       nofile  65536`
4. reboot
5. execute `docker run --rm centos:7 /bin/bash -c 'ulimit -Hn && ulimit -Sn'` (should return 65536 twice but no )

#### Way 2
6. add `--default-ulimit nofile=65536:65536` to `/var/snap/microk8s/current/args/dockerd`
7. reboot
8. execute `docker run --rm centos:7 /bin/bash -c 'ulimit -Hn && ulimit -Sn'` (should return 65536 twice but no )

#### Way 3
9. add 
````
"default-ulimit" : {
        "nofile":{
            "Name":" nofile",
            "Hard":" 65536",
            "Soft":" 65536"
    }
}
````
 to ` /var/snap/microk8s/354/args/docker-daemon.json`
10. execute `systemctl restart  snap.microk8s.daemon-docker.service `
11. execute ` journalctl -u snap.microk8s.daemon-docker.service -f` will return `unable to configure the Docker daemon with file /var/snap/microk8s/354/args/docker-daemon.json: the following directives don't match any configuration option: nofile` 

**Output of `docker version`:**

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.4
 Git commit:        e68fc7a
 Built:             Mon Oct  1 14:25:31 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e68fc7a
  Built:            Mon Oct  1 14:25:33 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Output of `docker info`:**

```
 docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 18.06.1-ce
Storage Driver: aufs
 Root Dir: /var/snap/docker/common/var-lib-docker/aufs
 Backing Filesystem: extfs
 Dirs: 1
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: N/A (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: 949e6fa (expected: fec3683)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-43-generic
Operating System: Ubuntu Core 16
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.821GiB
Name: tsi-k8s-1
ID: SXNH:J6LK:GLWZ:FS6Y:BW63:M2DI:E4JO:FO4S:7342:YRDE:SX7T:WSOE
Docker Root Dir: /var/snap/docker/common/var-lib-docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 44
 System Time: 2019-01-02T16:31:53.331367288Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

So do you have any idea about that ?

**Comment by haimari** [comment] 2019-04-03 14:18
Same issue
```
Welcome to Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-46-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

 * Ubuntu's Kubernetes 1.14 distributions can bypass Docker and use containerd
   directly, see https://bit.ly/ubuntu-containerd or try it now with

     snap install microk8s --classic

 * Canonical Livepatch is available for installation.
   - Reduce system reboots and improve kernel security. Activate at:
     https://ubuntu.com/livepatch
Last login: Wed Apr  3 13:33:47 2019 from 10.100.100.97
root@haproxy1:~# docker info
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 10
Server Version: 18.09.4
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-46-generic
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 40
Total Memory: 15.29GiB
Name: haproxy1.stapp.me
ID: RADA:WKAP:TJSK:YGBM:GZA5:ZSOA:5EGV:R4GO:ICQ4:HHUF:OVOJ:UJHM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Comment by sdillahey** [comment] 2019-06-06 21:39
Ran into similar issues. Modifying the ulimit of `DOCKER_OPTS` in docker.service worked for us.
https://jira.hyperledger.org/browse/CE-342

**Comment by Ducatel** [comment] 2019-06-07 07:35
Hum thanks for that, I will check ;)

**Comment by raduboghirnea** [comment] 2020-07-03 14:16
I found a solution for this problem. I have a blazemeter cloud account that uses "private location" - a docker server that I want to simulate 20k threads - and this exhaust the default 4096 "files" = ubuntu threads. The problem is that the framework starts a new running container for every test execution, so I could not pass --ulimit parameters as an argument to docker run command. The solution was to alter the default settings that docker uses when it runs a container. 
I have a "snap" type of installation, but I think the solution is valid for classical docker installation. 
1 - locate daemon.json file of docker - I have it in : /var/snap/docker/current/config 
2 - sudo vi on the file. 
content before : 
{
    "log-level":        "error",
    "storage-driver":   "overlay2"
}

content after : 


{
    "log-level":        "error",
    "storage-driver":   "overlay2",
    "default-ulimits": {
    "nofile": {
      "Name": "nofile",
      "Hard": 63000,
      "Soft": 63000
    }
    }
}

3 . restart the docker service - I use sudo snap restart docker. 

- All new containers that are created after this should return 63000/63000 when calling : 
 sudo docker exec -it b4589b3a77af /bin/sh -c 'ulimit -Hn && ulimit -Sn'

carefull with the syntax in daemon.json file - there should be default-ulimits (not default-ulimit) , also, values for Hard and Soft should be integer, not double quoted .

**Comment by rulatir** [comment] 2020-08-25 12:01
> Ran into similar issues. Modifying the ulimit through `LimitNOFILE`, `LimitNPROC`, `LimitCORE` in docker.service worked for us.

`docker.service` is a system file installed with the docker package. It is not intended to be modified by the user, and changes will be overwritten by updates. Still looking for a solution that doesn't require me to do "illegal" things.

**Comment by zygzagZ** [comment] 2023-05-30 10:25
Today I learned you can override it not only in service config file containerd.service, but also in config directory: containerd.service.d.
So it is possible to not modify upstream-provided file and still apply the patch:
```
# mkdir -p /etc/systemd/system/containerd.service.d/
# cat >/etc/systemd/system/containerd.service.d/filelimit.conf <<EOF
[Service]
LimitNOFILE=500000
EOF
```
This worked for me.
Source: https://access.redhat.com/solutions/1257953

**Comment by cpuguy83** [comment] 2023-06-07 15:56
Closing since this is a non-issue.
The OP has a typo in the config.
Use `defualt-ulimits` in the daemon config or `--ulimit` with `docker run`.

**Closed by cpuguy83** 2023-06-07 15:56 UTC
