### ISSUE TITLE
17.06.0 on Ubuntu - Docker system service fails to start.

### ISSUE THREAD

**Issue by glenpike** [docker/for-linux#47] opened 2017-06-29 12:46 UTC
### Expected behavior
Docker service starts

### Actual behavior
Docker service fails to start

### Information
Distro: Ubuntu Xenial
Docker CE: 17.06.0~ce-0~ubuntu
### Steps to reproduce the behavior

1. systemctl start docker

Docker service fails to start.

2. systemctl log / journal -xe not helpful, but syslog says:

```
Jun 29 11:43:40 mc-1 systemd[1]: Starting Docker Application Container Engine...
Jun 29 11:43:40 mc-1 docker[5899]: `docker daemon` is not supported on Linux. Please run `dockerd` directly
Jun 29 11:43:40 mc-1 systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Jun 29 11:43:40 mc-1 systemd[1]: Failed to start Docker Application Container Engine.
```

3.  sudo systemctl edit --full docker.service has nothing about docker daemon, but shows the following line:

```
ExecStart=/usr/bin/dockerd -H fd://
```

Similar to #11 ?

Workaround:
```
apt-get install docker-ce=17.05.0~ce-0~ubuntu-xenial
```

**Comment by glenpike** [comment] 2017-06-29 12:59
See: https://github.com/docker/machine/issues/4156

**Comment by narration-sd** [comment] 2017-06-30 00:37
I'm not sure why this didn't cross-reference, but

https://github.com/docker/for-linux/issues/11#issuecomment-312143765

**Comment by corbathegeek** [comment] 2017-07-05 22:23
Workaround listed above doesn't work. Can't locate the ubuntu xenial version:

`peterc@L4692197:~$ sudo apt-get install docker-ce=17.05.0~ce-0~ubuntu-xenial
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Version '17.05.0~ce-0~ubuntu-xenial' for 'docker-ce' was not found
peterc@L4692197:~$ 
`

**Comment by glenpike** [comment] 2017-07-06 06:55
Have you updated your apt-cache?
`sudo apt-get update`

Then checked what packages are available for docker?
`sudo apt-cache showpkg docker-ce`
(Command from top of my head so if it doesn't work read the doc's for apt-cache)

That should show all the available versions then you can pick one that's not the broken version.

**Comment by muffl0n** [comment] 2017-07-10 13:37
Having the same problem. Downgrading to 17.03.2 helps
```
apt-get install docker-ce=17.03.2~ce-0~ubuntu-xenial
```

**Comment by mpepping** [comment] 2017-08-17 12:10
It seems that [this Engine Deprecation feature](https://docs.docker.com/engine/deprecated/#docker-daemon-subcommand) is already activated for 17.06 .. whilst scheduled for the 17.12 release.

**Comment by glenpike** [comment] 2017-08-30 09:47
This issue also happens if you use the regenerate-certs command - necessary if you reboot your machine and it gets a new IP...

**Comment by FX-HAO** [comment] 2017-09-06 10:05
Replace this line in `/etc/systemd/system/docker.service` and then run `systemctl daemon-reload` should fix the problem on Ubuntu.
```
# ExecStart=/usr/bin/docker daemon -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver aufs --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=generic  --mtu=1472 --bip=10.1.63.1/24
ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver aufs --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=generic  --mtu=1472 --bip=10.1.63.1/24
```

**Comment by michalm86** [comment] 2017-10-19 10:07
Or use `systemctl edit docker` to override ExecStart
https://success.docker.com/KBase/Using_systemd_to_control_the_Docker_daemon

**Comment by christoph-hipp** [comment] 2017-12-11 21:57
Installing 17.09.1-ce in Ubuntu 16.04
To me, it appears to be an unresolvable problem after  doing `apt-get dist-upgrade `. Wild guess is, it is connected with the Kernel Version...

This environment **works fine** with 17.09.1-ce ...
**4.4.0-97-generic** #120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

This environment **fails** with 17.09.1-ce (**17.05.0-ce works fine, though!**)...
**4.4.0-103-generic** #126-Ubuntu SMP Mon Dec 4 16:23:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by lianesten** [comment] 2018-01-03 13:02
If for any reason the status container after run image is Exited, use:

`docker run -d -ti <image_id>`

This indicate interctive CLI, so the status container will be Up.

**Comment by KingReload** [comment] 2018-01-17 15:27
I have a funny one for you guys:

`
user:~$ sudo service docker start
 * Starting Docker: docker                                                                                    [ OK ]
user:~$ sudo service docker status
 * Docker is not running
`

**Comment by sepidetari** [comment] 2018-01-21 10:22
I have the same problem and failed to solve it till now ....
just after installing try to run: 
sudo docker run hello-world
but Received this:
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.See 'docker run --help'.
then:
sudo service docker start
 * Starting Docker: docker
sudo service docker status
 * Docker is not running

**Comment by seemethere** [comment] 2018-07-09 20:22
Closing this since it's related to an older (unsupported version of Docker CE).

Feel free to continue the conversation or post a new issue if you see this issue arise with newer versions of Docker CE!

**Closed by seemethere** 2018-07-09 20:22 UTC

**Comment by bronsonatcs** [comment] 2018-10-24 19:08
i dunno ive tried multiple version and come into the same issue, i feel like removing docker is leaving some files behind which is causing errors when re installing it.

**Comment by ffactory-ofcl** [comment] 2019-04-14 10:57
I'm having this problem while running Debian on armhf on my phone in chroot.

**Comment by filinvadim** [comment] 2019-06-22 19:24
sudo apt install docker.io
helps me

**Comment by crisanlucid** [comment] 2019-07-13 08:03
> sudo service docker start

Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.

**Comment by 0x4164** [comment] 2019-09-18 06:51
> sudo apt install docker.io
> helps me

same here, the cause of my case is missing dockerd. i have to install containerd & docker.io with apt.

`journalctl -u docker.service` says
* /usr/bin/dockerd not present or not executable

**Comment by plato1123** [comment] 2019-12-28 08:36
I ran sudo dockerd --debug and got:
failed to start daemon: mkdir /var/lib/docker/runtimes: not a directory

dafuq?  

sudo rm /var/lib/docker/runtimes

sudo mkdir /var/lib/docker/runtimes

sudo chmod a+w /var/lib/docker/runtimes

sudo service docker start

Now she works!

**Comment by nikluwfy** [comment] 2020-03-18 16:45
This solved issue for me: 
```
echo "export DOCKER_HOST=tcp://localhost:2375" >> ~/.bashrc && source ~/.bashrc
```

**Comment by kurdi89** [comment] 2020-04-08 22:44
was getting the same error on WSL and @nikluwfy  answer solved it 

```bash
echo "export DOCKER_HOST=tcp://localhost:2375" >> ~/.zshrc && source ~/.zshrc
```

**Comment by hassaan-prog** [comment] 2020-04-27 09:35
> I have a funny one for you guys:
> 
> `user:~$ sudo service docker start`
> ` * Starting Docker: docker [ OK ]`
> `user:~$ sudo service docker status`
> ` * Docker is not running`

i am still facing the same issue on WSL, even after trying above posted solutions.

**Comment by thaJeztah** [comment] 2020-04-28 11:15
WSL1 does not have all features needed to run a container engine such as docker or containerd, so that's expected; you can run docker on WSL2; if your machine supports WSL2, you can install Docker Desktop for Windows, and have it run docker in WSL2

**Comment by nikluwfy** [comment] 2020-04-28 11:55
> > I have a funny one for you guys:
> > `user:~$ sudo service docker start`
> > ` * Starting Docker: docker [ OK ]`
> > `user:~$ sudo service docker status`
> > ` * Docker is not running`
> 
> i am still facing the same issue on WSL, even after trying above posted solutions.

@thaJeztah is right. You can't install and run Docker services directly in your subsystem.
You have to install and run your Docker Desktop for Windows and then try running command I've suggested above.

**Comment by hassaan-prog** [comment] 2020-04-30 04:35
@thaJeztah  @nikluwfy  thank you for your answers, i made it work by following [docker desktop documentatio](https://docs.docker.com/docker-for-windows/wsl-tech-preview/)n, and that done the trick for me.

**Comment by ckvtvm-arch** [comment] 2020-06-19 21:33
i have same issue, please let me know the solution

root@L5PXPQN2:/home/centy# sudo service docker restart
 * Starting Docker: docker                                                                                                                                       [ OK ]
root@L5PXPQN2:/home/centy# sudo service docker status
 * Docker is not running

**Comment by ckvtvm-arch** [comment] 2020-06-19 21:34
Please let me know how you solved this

root@L5PXPQN2:/home/centy# sudo service docker restart
 * Starting Docker: docker                                                                                                                                       [ OK ]
root@L5PXPQN2:/home/centy# sudo service docker status
 * Docker is not running

**Comment by thaJeztah** [comment] 2020-06-22 08:14
@ckvtvm-arch there's no single answer to that question. The service failing to run can have any reason. I'd recommend looking for logs to find out what's causing that problem in your situation (`journalctl -xu docker` would probably give more details if the service failed).

Please keep in mind that this issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)
