### ISSUE TITLE
SIGSEGV in syslog driver

### ISSUE THREAD

**Issue by matevarga** [docker/for-linux#159] opened 2017-11-11 15:26 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
Docker daemon works properly.

### Actual behavior
Docker daemon crashed:
`/var/log/upstart/docker.log` 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1512ea2]

goroutine 824906 [running]:
github.com/docker/docker/daemon/logger/syslog.(*syslogger).Log(0xc42000e520, 0xc422886360, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/logger/syslog/syslog.go:137 +0x82
github.com/docker/docker/daemon/logger.(*RingLogger).run(0xc422d2ab40)
        /go/src/github.com/docker/docker/daemon/logger/ring.go:116 +0x7c
created by github.com/docker/docker/daemon/logger.newRingLogger
        /go/src/github.com/docker/docker/daemon/logger/ring.go:43 +0x207
```

### Steps to reproduce the behavior
I can't reproduce this, it was a crash in production. There's been no memory pressure or high load on the server. 

**Output of `docker version`:**

```
Docker version 17.06.0-ce, build 02c1d87
```

**Output of `docker info`:**

```
Containers: 11
 Running: 9
 Paused: 0
 Stopped: 2
Images: 44
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: # redacted #
 Backing Filesystem: extfs
 Dirs: 604
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay weavemesh
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.0-75-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 62.92GiB
Name: # redacted # 
ID: 7JF5:X2H4:IMXS:Y6RK:IL74:RZ3B:LP4C:YOSL:PT2H:OGQS:L33G:QDNS
Docker Root Dir: # redacted #
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: # redacted #
Https Proxy: # redacted #
Username: # redacted #
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

VMWare ESXi, `DOCKER_OPTS="--storage-driver=aufs --log-opt mode=non-blocking"`

**Comment by thaJeztah** [comment] 2017-11-12 00:34
This looks like a duplicate of https://github.com/moby/moby/issues/34869, which was resolved in https://github.com/moby/moby/pull/33832 (back ported to Docker CE 17.06.1 and up through https://github.com/docker/docker-ce/pull/95

I recommend updating to 17.06.2. Be aware that Docker 17.06.x has reached end of life; the current "stable" release of Docker CE is 17.09, which is still supported.

I'll go ahead and close this, because this should be fixed, but leave a comment if you're still able to reproduce after updating, thanks!

**Closed by thaJeztah** 2017-11-12 00:34 UTC

**Comment by matevarga** [comment] 2017-11-14 07:42
Cheers.
