### ISSUE TITLE
fatal error: unexpected signal during runtime execution [signal SIGBUS: bus error code=0x2 addr=0x122ca94 pc=0x44c6af]

### ISSUE THREAD

**Issue by gabrielschmith** [docker/for-linux#285] opened 2018-04-19 17:15 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
docker was not supposed to stop running the current machine

### Actual behavior
When running the [rancher](https://rancher.com/) on a container docker the same ends up locking the machine. The machine only responds again when the system restarts.

fatal error: unexpected signal during runtime execution
[signal SIGBUS: bus error code=0x2 addr=0x122ca94 pc=0x44c6af]

runtime stack:
runtime.throw(0xf2fe90, 0x2a)
        /usr/local/go/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:274 +0x2db
runtime.gentraceback(0x426b76, 0xc42018dbd8, 0x0, 0xc4200001a0, 0x0, 0xc42018dc18, 0x20, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/runtime/traceback.go:244 +0x2ef
runtime.callers.func1()
        /usr/local/go/src/runtime/traceback.go:707 +0x90
runtime.systemstack(0x1683f00)
        /usr/local/go/src/runtime/asm_amd64.s:327 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1132

goroutine 1 [running, locked to thread]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:281 fp=0xc42018db60 sp=0xc42018db58
runtime.callers(0x4, 0xc42018dc18, 0x20, 0x20, 0x100000000000000)
        /usr/local/go/src/runtime/traceback.go:708 +0xdb fp=0xc42018dbd8 sp=0xc42018db60
runtime.mProf_Malloc(0xc420336000, 0x2000)
        /usr/local/go/src/runtime/mprof.go:245 +0x76 fp=0xc42018dd48 sp=0xc42018dbd8
runtime.profilealloc(0x1684520, 0xc420336000, 0x2000)
        /usr/local/go/src/runtime/malloc.go:843 +0x4b fp=0xc42018dd68 sp=0xc42018dd48
runtime.mallocgc(0x2000, 0xeaf140, 0x1, 0xed2d80)
        /usr/local/go/src/runtime/malloc.go:773 +0x4e7 fp=0xc42018de08 sp=0xc42018dd68
runtime.newarray(0xeaf140, 0x3e8, 0xc4202ea570)
        /usr/local/go/src/runtime/malloc.go:833 +0x64 fp=0xc42018de48 sp=0xc42018de08
runtime.makechan(0xd8aac0, 0x3e8, 0xc4202ea720)
        /usr/local/go/src/runtime/chan.go:93 +0x1d4 fp=0xc42018dea0 sp=0xc42018de48
fatal error: unexpected signal during runtime execution
panic during panic
[signal SIGBUS: bus error code=0x2 addr=0x122ca94 pc=0x44c6af]

runtime stack:
runtime.startpanic_m()
        /usr/local/go/src/runtime/panic.go:653 +0x19a
runtime.systemstack(0xf557f8)
        /usr/local/go/src/runtime/asm_amd64.s:343 +0xab
runtime.startpanic()
        /usr/local/go/src/runtime/panic.go:569 +0x1e
runtime.throw(0xf2fe90, 0x2a)
        /usr/local/go/src/runtime/panic.go:595 +0x88
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:274 +0x2db
runtime.gentraceback(0xffffffffffffffff, 0xc42018db58, 0x0, 0xc4200001a0, 0x0, 0x0, 0x64, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/runtime/traceback.go:244 +0x2ef
runtime.traceback1(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc4200001a0, 0x0)
        /usr/local/go/src/runtime/traceback.go:691 +0x121
runtime.traceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc4200001a0)
        /usr/local/go/src/runtime/traceback.go:652 +0x52
runtime.tracebackothers(0x1683fa0)
        /usr/local/go/src/runtime/traceback.go:799 +0x2ec
runtime.dopanic_m(0x1683fa0, 0x42c6e5, 0x7ffd9a608678)
        /usr/local/go/src/runtime/panic.go:699 +0x2a0
runtime.dopanic.func1()
        /usr/local/go/src/runtime/panic.go:578 +0x3c
runtime.systemstack(0x7ffd9a608648)
        /usr/local/go/src/runtime/asm_amd64.s:343 +0xab
runtime.dopanic(0x0)
        /usr/local/go/src/runtime/panic.go:579 +0x61
runtime.throw(0xf2fe90, 0x2a)
        /usr/local/go/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:274 +0x2db
runtime.gentraceback(0x426b76, 0xc42018dbd8, 0x0, 0xc4200001a0, 0x0, 0xc42018dc18, 0x20, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/runtime/traceback.go:244 +0x2ef
runtime.callers.func1()
        /usr/local/go/src/runtime/traceback.go:707 +0x90
runtime.systemstack(0x1683f00)
        /usr/local/go/src/runtime/asm_amd64.s:327 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1132

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 58
 Running: 3
 Paused: 0
 Stopped: 55
Images: 695
Server Version: 17.09.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 851
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-38-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.705GiB
Name: alltradeci-linux
ID: ESN5:NJG6:2FUQ:62PR:J63W:AQC2:A3BS:THEY:BDPV:5CXS:MNQ7:6CNA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
physical machine

**Comment by thaJeztah** [comment] 2018-04-19 17:53
Docker 17.09 reached EOL in december, so I'd recommend updating to a currently supported version of Docker. If you cannot update to the current version for whatever reason, at least make sure that you update to the latest patch release for the 17.09.x release (Docker CE 17.09.1 https://github.com/docker/docker-ce/releases/tag/v17.09.1-ce), which has various fixes, among some fixes for panics.

Closing this issue because this version of Docker reached EOL, but feel free to continue the conversation

**Closed by thaJeztah** 2018-04-19 17:53 UTC

**Comment by zxmrlc** [comment] 2020-06-09 02:36
> Docker 17.09 reached EOL in december, so I'd recommend updating to a currently supported version of Docker. If you cannot update to the current version for whatever reason, at least make sure that you update to the latest patch release for the 17.09.x release (Docker CE 17.09.1 https://github.com/docker/docker-ce/releases/tag/v17.09.1-ce), which has various fixes, among some fixes for panics.
> 
> Closing this issue because this version of Docker reached EOL, but feel free to continue the conversation
I have the same problem in docker version 18.06.1-ce

**Comment by zxmrlc** [comment] 2020-06-09 02:38
> Docker 17.09 reached EOL in december, so I'd recommend updating to a currently supported version of Docker. If you cannot update to the current version for whatever reason, at least make sure that you update to the latest patch release for the 17.09.x release (Docker CE 17.09.1 https://github.com/docker/docker-ce/releases/tag/v17.09.1-ce), which has various fixes, among some fixes for panics.
> 
> Closing this issue because this version of Docker reached EOL, but feel free to continue the conversation




sorry, I have the same problem in docker version 18.06.1-ce.

**Comment by thaJeztah** [comment] 2020-06-09 13:31
Docker 18.06 is also EOL; current release is 19.03.x

**Comment by zxmrlc** [comment] 2020-07-06 02:51
> Docker 18.06 is also EOL; current release is 19.03.x
THANKS for your reply
It's not the Docker version that caused the problem .
Updating the version of docker did not solve the problem.
`fatal error: unexpected signal during runtime execution
[signal SIGBUS: bus error code=0x2 addr=0x122ca94 pc=0x44c6af]`
The runtime  error is caused by a hardware error.
in my case, the disk is damaged, making dockerd unreadable files in /data/lib/docker.
Replace the disk, the problem is solved......
