### ISSUE TITLE
Overlay network nodes with encryption cannot connect to each other. ESP traffic registering on node.

### ISSUE THREAD

**Issue by danbrianwhite** [docker/for-linux#91] opened 2017-08-30 17:52 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

When using a Docker SWARM overlay network with the encrypted option enabled, nodes should able to connect to each other's services. 

### Actual behavior
When using a Docker SWARM overlay network with the encrypted option enabled, nodes are not able to connect to each other's services. The ESP traffic is hitting the nodes. However, when creating a network without encryption, the same nodes can connect to the services.

### Steps to reproduce the behavior

create a docker swarm with multiple masters

then add an encrypted network
```
docker network create --opt encrypted --subnet=192.168.1.0/24 --driver overlay mynetwork
docker service create --mode global  --name nginx --network mynetwork --endpoint-mode dnsrr -e MODE=swarm nginx
```

connect to the nginx service via bash

ex:  
```
docker exec -it cb0e84fdb075 /bin/bash
apt-get update
apt-get install -y dnsutils
apt-get install -y curl
nslookup nginx
```

Then curl the service from a different node

`curl 192.168.1.x`

The service cannot be found

Only the current node's service will be able to be curled.

When running a tcpdump for esp traffic, the traffic shows up on the requested node. The traffic will also show up on the requesting node.

```
ubuntu@ip-172-31-63-1:~$ sudo tcpdump -p esp
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
17:42:34.557153 IP ec2-34-234-117-190.compute-1.amazonaws.com > ip-172-31-63-1: ESP(spi=0xbbcef373,seq=0x3344), length 116
17:42:35.562238 IP ec2-34-234-117-190.compute-1.amazonaws.com > ip-172-31-63-1: ESP(spi=0xbbcef373,seq=0x3345), length 116
17:42:37.578244 IP ec2-34-234-117-190.compute-1.amazonaws.com > ip-172-31-63-1: ESP(spi=0xbbcef373,seq=0x3346), length 116
17:42:41.706319 IP ec2-34-234-117-190.compute-1.amazonaws.com > ip-172-31-63-1: ESP(spi=0xbbcef373,seq=0x3347), length 116
17:42:49.898310 IP ec2-34-234-117-190.compute-1.amazonaws.com > ip-172-31-63-1: ESP(spi=0xbbcef373,seq=0x3348), length 116
```

Now add a standard network without encryption
```
docker network create --subnet=192.168.1.0/24 --driver overlay mynetwork2
docker service create --mode global  --name nginx2 --network mynetwork2 --endpoint-mode dnsrr -e MODE=swarm nginx
```

connect to the nginx service via bash

ex:  
```
docker exec -it 8fb5f0616998 /bin/bash
apt-get update
apt-get install -y dnsutils
apt-get install -y curl
nslookup nginx2
```

Then curl the service from a different node

`curl 192.168.1.x`

All of the services return a response for curl

**Output of `docker version`:**

```
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:51:24 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:50:16 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 17.06.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 25
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: xqwf13319q9khgo42s0zvprtb
 Is Manager: true
 ClusterID: o310qhz17ejute84low7xgmko
 Managers: 2
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: REDACTED
 Manager Addresses:
  REDACTED:2377
  REDACTED:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-32-generic
Operating System: Ubuntu 17.04
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 484.6MiB
Name: ip-172-31-63-0
ID: UEHZ:EGQ2:LXRK:XGT6:76KE:3R2H:IW7K:SD6S:TTOZ:7LWJ:SCB2:YZ6H
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

This is running in AWS using Ubuntu Linux:
us-east-1 | zesty | 17.04 | amd64 | hvm:ebs-ssd | 20170811 | ami-7b4d7900 | hvm
All network ports opened.

Additional Notes:
Issue occurs when using the public DNS ip address applied to the EC2 instances.

However, when using the internal IP Address for an EC2 instance, the encrypted network runs properly.

**Comment by fentas** [comment] 2017-10-17 19:36
Since you are using AWS maybe this issue will help you https://github.com/moby/moby/issues/27425
> Opening up ECP (protocol 50 as "Custom protocol" in an AWS security group) wins all the things.

**Comment by thaJeztah** [comment] 2017-11-02 16:07
Yes this looks like protocol 50 traffic is not allowed between the nodes. From the [documentation](https://docs.docker.com/engine/swarm/swarm-tutorial/#open-protocols-and-ports-between-the-hosts)

> ### Open protocols and ports between the hosts
> 
> The following ports must be available. On some systems, these ports are open by default.
> 
> * **TCP port 2377** for cluster management communications
> * **TCP** and **UDP port 7946** for communication among nodes
> * **UDP port 4789** for overlay network traffic
> 
> If you are planning on creating an overlay network with encryption (`--opt encrypted`),
> you will also need to ensure **ip protocol 50** (**ESP**) traffic is allowed.

I think this is a configuration issue, not a bug, so I'll close this issue, but feel free to continue the conversation

**Closed by thaJeztah** 2017-11-02 16:07 UTC

**Comment by emcgee** [comment] 2018-05-19 07:12
Interestingly enough, we're seeing exactly the same thing and have with all ports/protocols opened. 

Setting up the encrypted tunnels as described above works in Ubuntu 16.04 with the 4.4 kernel, but not in anything newer (Debian 9 with 4.9, Ubuntu 18.04 with 4.15, etc...)

We see exactly the same scenario of one-way ESP traffic -- outlined in more detail here: https://github.com/moby/moby/issues/30727#issuecomment-390385320

@danbrianwhite Did you ever come to a resolution on this? 

/cc @thaJeztah

**Comment by bijeebuss** [comment] 2019-02-13 16:30
Can confirm this is still an issue. When I have a manager node on ubuntu 16.04 and worker node on ubuntu 18.04 tasks can communicate only with an unencrypted overlay network, however if they are both ubuntu 16.04 the encrypted overlay network works.

**Comment by emcgee** [comment] 2019-02-21 08:17
@bijeebuss This is being tracked over at https://github.com/moby/moby/issues/37115 - please feel free to go comment on that and see if you can raise any alarm bells!
