### ISSUE TITLE
RFC: pull containerd released branch/tag in vendor

### ISSUE THREAD

**Issue by zhsj** [docker/for-linux#887] opened 2020-01-06 06:02 UTC
I see in https://github.com/docker/docker-ce repo, the `components/engine/vendor.conf` shows the containerd version is `acdcf13d5eaf0dfe0eaeabe7194a82535549bc2b`, which is from containerd master branch.

Would you like me to update this to a taged version, or from latest commit in release branch? If you're not against this, I will first send PR to moby repo then the docker-ce repo. (I think for docker-ce master branch, it should be containerd/1.3 release?)

**Comment by AkihiroSuda** [comment] 2020-01-07 10:21
Rolling back master to v1.3 may cause regression. I think this should be postponed to containerd v1.4+.

**Comment by zhsj** [comment] 2020-01-07 14:49
Yes, this could be postponed after containerd v1.4. I just wish docker-ce is working towards using some taged versions of containerd.

BTW, docker-ce apt/rpm repo ships a taged version of containerd, does it matter if docker-ce engine is not built/vendor with that version?

**Comment by AkihiroSuda** [comment] 2020-01-07 15:02
> does it matter if docker-ce engine is not built/vendor with that version?

No

**Comment by thaJeztah** [comment] 2020-01-13 16:50
> BTW, docker-ce apt/rpm repo ships a tagged version of containerd, does it matter if docker-ce engine is not built/vendor with that version?

The tags in the containerd repository are currently tagging the binary releases, and thus refer to the binary release. The `go` API is currently marked "unstable" (see https://github.com/containerd/containerd/blob/f593efdf0c160037c9f831983f62537285739b03/RELEASES.md#public-api-stability), which means that not all fixes / changes in the Go API are backported to release branches; because of that, the recommendation is currently to vendor from `master`.

Having a stable Go API is on the roadmap for containerd, but not yet in place; see https://github.com/containerd/containerd/issues/3554

**Comment by thaJeztah** [comment] 2020-05-27 18:04
let me close this one per the above, but feel free to continue the conversation

**Closed by thaJeztah** 2020-05-27 18:04 UTC
