### ISSUE TITLE
Docker TLS handshake error

### ISSUE THREAD

**Issue by RahulKanvinde** [docker/for-linux#620] opened 2019-03-12 06:41 UTC
I am using a proxy server to get access to load docker images. The docker version is 18.03.0-ce.
I get the following error:

Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: tls: first record does not look like a TLS handshake.

My system:

Docker version  18.03.0-ce., build 0520e24302
Windows 7 OS 64 bit

**Comment by thaJeztah** [comment] 2019-03-20 10:43
This looks like something in your setup, not a bug; please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/docker/for-linux/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://join.slack.com/t/dockercommunity/shared_invite/enQtNDM4NjAwNDMyOTUwLWZlMDZmYWRjZjk4Zjc5ZGQ5NWZkOWI1Yjk2NGE3ZWVlYjYxM2VhYjczOWIyZDFhZTE3NTUwZWQzMjhmNGYyZTg)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2019-03-20 10:43 UTC
