### ISSUE TITLE
Docker 20.10 cannot start up on Fedora 32

### ISSUE THREAD

**Issue by Cuda-Chen** [docker/for-linux#1163] opened 2020-12-10 08:01 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
Start the daemon successfully by typing `systemctl start docker`.

### Actual behavior
`systemctl start docker` failed with showing following messages:
```
$ systemctl start docker
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
```

### Steps to reproduce the behavior

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        7287ab3
 Built:             Tue Dec  8 19:00:38 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.4.2-docker)

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info

```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
- Physical server with Fedora 32 with details by typing `uname -r`:
```
5.9.12-100.fc32.x86_64
```

<br/>

- Message shown by `systemctl status docker.service`:
```
● docker.service - Docker Application Container Engine
     Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Thu 2020-12-10 15:43:15 CST; 7min ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
    Process: 8321 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
   Main PID: 8321 (code=exited, status=1/FAILURE)
        CPU: 210ms

Dec 10 15:43:15 localhost.localdomain systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
Dec 10 15:43:15 localhost.localdomain systemd[1]: Stopped Docker Application Container Engine.
Dec 10 15:43:15 localhost.localdomain systemd[1]: docker.service: Start request repeated too quickly.
Dec 10 15:43:15 localhost.localdomain systemd[1]: docker.service: Failed with result 'exit-code'.
Dec 10 15:43:15 localhost.localdomain systemd[1]: Failed to start Docker Application Container Engine.
```

<br/>

- Message shown by `journalctl -u docker.service`:
```
Dec 10 15:43:03 localhost.localdomain systemd[1]: Starting Docker Application Container Engine...
Dec 10 15:43:03 localhost.localdomain dockerd[8145]: time="2020-12-10T15:43:03.719607888+08:00" level=info msg="Starting up"
Dec 10 15:43:03 localhost.localdomain dockerd[8145]: time="2020-12-10T15:43:03.720436912+08:00" level=info msg="parsed scheme: \"unix\"" module=grpc
Dec 10 15:43:03 localhost.localdomain dockerd[8145]: time="2020-12-10T15:43:03.720448151+08:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Dec 10 15:43:03 localhost.localdomain dockerd[8145]: time="2020-12-10T15:43:03.720460681+08:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
Dec 10 15:43:03 localhost.localdomain dockerd[8145]: time="2020-12-10T15:43:03.720467701+08:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Dec 10 15:43:03 localhost.localdomain dockerd[8145]: time="2020-12-10T15:43:03.721205064+08:00" level=info msg="parsed scheme: \"unix\"" module=grpc
Dec 10 15:43:03 localhost.localdomain dockerd[8145]: time="2020-12-10T15:43:03.721216250+08:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Dec 10 15:43:03 localhost.localdomain dockerd[8145]: time="2020-12-10T15:43:03.721244877+08:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
Dec 10 15:43:03 localhost.localdomain dockerd[8145]: time="2020-12-10T15:43:03.721252573+08:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Dec 10 15:43:04 localhost.localdomain dockerd[8145]: time="2020-12-10T15:43:04.041121324+08:00" level=info msg="[graphdriver] using prior storage driver: overlay2"
Dec 10 15:43:04 localhost.localdomain dockerd[8145]: time="2020-12-10T15:43:04.173683335+08:00" level=info msg="Loading containers: start."
Dec 10 15:43:04 localhost.localdomain dockerd[8145]: time="2020-12-10T15:43:04.479794106+08:00" level=info msg="Firewalld: docker zone already exists, returning"
Dec 10 15:43:04 localhost.localdomain dockerd[8145]: time="2020-12-10T15:43:04.931395917+08:00" level=info msg="Firewalld: interface br-59f818ed6e85 already part of docker zone, returning"
Dec 10 15:43:04 localhost.localdomain dockerd[8145]: time="2020-12-10T15:43:04.992254871+08:00" level=info msg="Firewalld: interface br-59f818ed6e85 already part of docker zone, returning"
Dec 10 15:43:05 localhost.localdomain dockerd[8145]: time="2020-12-10T15:43:05.234528678+08:00" level=warning msg="could not create bridge network for id cbb7be632610371ec18ebb588eabe7310e2bc55c8f42e6ddc05b8f725e4a43ac bridge name docker0 while booting up from persistent state: Failed to program NAT chain: ZONE_CONFLICT: 'docker0' already bound to a zone"
Dec 10 15:43:05 localhost.localdomain dockerd[8145]: time="2020-12-10T15:43:05.238647153+08:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Dec 10 15:43:05 localhost.localdomain dockerd[8145]: time="2020-12-10T15:43:05.321939937+08:00" level=info msg="stopping event stream following graceful shutdown" error="<nil>" module=libcontainerd namespace=moby
Dec 10 15:43:05 localhost.localdomain dockerd[8145]: time="2020-12-10T15:43:05.322838335+08:00" level=info msg="stopping event stream following graceful shutdown" error="context canceled" module=libcontainerd namespace=plugins.moby
Dec 10 15:43:05 localhost.localdomain dockerd[8145]: failed to start daemon: Error initializing network controller: Error creating default "bridge" network: Failed to program NAT chain: ZONE_CONFLICT: 'docker0' already bound to a zone
Dec 10 15:43:05 localhost.localdomain systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Dec 10 15:43:05 localhost.localdomain systemd[1]: docker.service: Failed with result 'exit-code'.
Dec 10 15:43:05 localhost.localdomain systemd[1]: Failed to start Docker Application Container Engine.
Dec 10 15:43:07 localhost.localdomain systemd[1]: docker.service: Scheduled restart job, restart counter is at 1.
Dec 10 15:43:07 localhost.localdomain systemd[1]: Stopped Docker Application Container Engine.
Dec 10 15:43:07 localhost.localdomain systemd[1]: Starting Docker Application Container Engine...
Dec 10 15:43:07 localhost.localdomain dockerd[8232]: time="2020-12-10T15:43:07.622050034+08:00" level=info msg="Starting up"
Dec 10 15:43:07 localhost.localdomain dockerd[8232]: time="2020-12-10T15:43:07.622693023+08:00" level=info msg="parsed scheme: \"unix\"" module=grpc
Dec 10 15:43:07 localhost.localdomain dockerd[8232]: time="2020-12-10T15:43:07.622706572+08:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Dec 10 15:43:07 localhost.localdomain dockerd[8232]: time="2020-12-10T15:43:07.622719536+08:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
Dec 10 15:43:07 localhost.localdomain dockerd[8232]: time="2020-12-10T15:43:07.622726568+08:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Dec 10 15:43:07 localhost.localdomain dockerd[8232]: time="2020-12-10T15:43:07.623244653+08:00" level=info msg="parsed scheme: \"unix\"" module=grpc
Dec 10 15:43:07 localhost.localdomain dockerd[8232]: time="2020-12-10T15:43:07.623255446+08:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Dec 10 15:43:07 localhost.localdomain dockerd[8232]: time="2020-12-10T15:43:07.623265008+08:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
Dec 10 15:43:07 localhost.localdomain dockerd[8232]: time="2020-12-10T15:43:07.623274468+08:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Dec 10 15:43:07 localhost.localdomain dockerd[8232]: time="2020-12-10T15:43:07.998064581+08:00" level=info msg="[graphdriver] using prior storage driver: overlay2"
Dec 10 15:43:08 localhost.localdomain dockerd[8232]: time="2020-12-10T15:43:08.149309884+08:00" level=info msg="Loading containers: start."
Dec 10 15:43:08 localhost.localdomain dockerd[8232]: time="2020-12-10T15:43:08.477634621+08:00" level=info msg="Firewalld: docker zone already exists, returning"
Dec 10 15:43:08 localhost.localdomain dockerd[8232]: time="2020-12-10T15:43:08.925008059+08:00" level=info msg="Firewalld: interface br-59f818ed6e85 already part of docker zone, returning"
Dec 10 15:43:08 localhost.localdomain dockerd[8232]: time="2020-12-10T15:43:08.984442545+08:00" level=info msg="Firewalld: interface br-59f818ed6e85 already part of docker zone, returning"
Dec 10 15:43:09 localhost.localdomain dockerd[8232]: time="2020-12-10T15:43:09.223296445+08:00" level=warning msg="could not create bridge network for id cbb7be632610371ec18ebb588eabe7310e2bc55c8f42e6ddc05b8f725e4a43ac bridge name docker0 while booting up from persistent state: Failed to program NAT chain: ZONE_CONFLICT: 'docker0' already bound to a zone"
Dec 10 15:43:09 localhost.localdomain dockerd[8232]: time="2020-12-10T15:43:09.227438023+08:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Dec 10 15:43:09 localhost.localdomain dockerd[8232]: time="2020-12-10T15:43:09.309909822+08:00" level=info msg="stopping event stream following graceful shutdown" error="<nil>" module=libcontainerd namespace=moby
Dec 10 15:43:09 localhost.localdomain dockerd[8232]: failed to start daemon: Error initializing network controller: Error creating default "bridge" network: Failed to program NAT chain: ZONE_CONFLICT: 'docker0' already bound to a zone
Dec 10 15:43:09 localhost.localdomain systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Dec 10 15:43:09 localhost.localdomain systemd[1]: docker.service: Failed with result 'exit-code'.
Dec 10 15:43:09 localhost.localdomain systemd[1]: Failed to start Docker Application Container Engine.
Dec 10 15:43:11 localhost.localdomain systemd[1]: docker.service: Scheduled restart job, restart counter is at 2.
Dec 10 15:43:11 localhost.localdomain systemd[1]: Stopped Docker Application Container Engine.
Dec 10 15:43:11 localhost.localdomain systemd[1]: Starting Docker Application Container Engine...
Dec 10 15:43:11 localhost.localdomain dockerd[8321]: time="2020-12-10T15:43:11.370244513+08:00" level=info msg="Starting up"
Dec 10 15:43:11 localhost.localdomain dockerd[8321]: time="2020-12-10T15:43:11.370894504+08:00" level=info msg="parsed scheme: \"unix\"" module=grpc
Dec 10 15:43:11 localhost.localdomain dockerd[8321]: time="2020-12-10T15:43:11.370905645+08:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Dec 10 15:43:11 localhost.localdomain dockerd[8321]: time="2020-12-10T15:43:11.370917921+08:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
Dec 10 15:43:11 localhost.localdomain dockerd[8321]: time="2020-12-10T15:43:11.370925652+08:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Dec 10 15:43:11 localhost.localdomain dockerd[8321]: time="2020-12-10T15:43:11.371498330+08:00" level=info msg="parsed scheme: \"unix\"" module=grpc
Dec 10 15:43:11 localhost.localdomain dockerd[8321]: time="2020-12-10T15:43:11.371509922+08:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Dec 10 15:43:11 localhost.localdomain dockerd[8321]: time="2020-12-10T15:43:11.371518741+08:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
Dec 10 15:43:11 localhost.localdomain dockerd[8321]: time="2020-12-10T15:43:11.371524301+08:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Dec 10 15:43:11 localhost.localdomain dockerd[8321]: time="2020-12-10T15:43:11.726919695+08:00" level=info msg="[graphdriver] using prior storage driver: overlay2"
Dec 10 15:43:11 localhost.localdomain dockerd[8321]: time="2020-12-10T15:43:11.848138502+08:00" level=info msg="Loading containers: start."
Dec 10 15:43:12 localhost.localdomain dockerd[8321]: time="2020-12-10T15:43:12.220735870+08:00" level=info msg="Firewalld: docker zone already exists, returning"
Dec 10 15:43:12 localhost.localdomain dockerd[8321]: time="2020-12-10T15:43:12.672860443+08:00" level=info msg="Firewalld: interface br-59f818ed6e85 already part of docker zone, returning"
Dec 10 15:43:12 localhost.localdomain dockerd[8321]: time="2020-12-10T15:43:12.734621693+08:00" level=info msg="Firewalld: interface br-59f818ed6e85 already part of docker zone, returning"
Dec 10 15:43:12 localhost.localdomain dockerd[8321]: time="2020-12-10T15:43:12.976683761+08:00" level=warning msg="could not create bridge network for id cbb7be632610371ec18ebb588eabe7310e2bc55c8f42e6ddc05b8f725e4a43ac bridge name docker0 while booting up from persistent state: Failed to program NAT chain: ZONE_CONFLICT: 'docker0' already bound to a zone"
Dec 10 15:43:12 localhost.localdomain dockerd[8321]: time="2020-12-10T15:43:12.980824071+08:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Dec 10 15:43:13 localhost.localdomain dockerd[8321]: time="2020-12-10T15:43:13.062842310+08:00" level=info msg="stopping event stream following graceful shutdown" error="<nil>" module=libcontainerd namespace=moby
Dec 10 15:43:13 localhost.localdomain dockerd[8321]: failed to start daemon: Error initializing network controller: Error creating default "bridge" network: Failed to program NAT chain: ZONE_CONFLICT: 'docker0' already bound to a zone
Dec 10 15:43:13 localhost.localdomain systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Dec 10 15:43:13 localhost.localdomain systemd[1]: docker.service: Failed with result 'exit-code'.
Dec 10 15:43:13 localhost.localdomain systemd[1]: Failed to start Docker Application Container Engine.
Dec 10 15:43:15 localhost.localdomain systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
Dec 10 15:43:15 localhost.localdomain systemd[1]: Stopped Docker Application Container Engine.
Dec 10 15:43:15 localhost.localdomain systemd[1]: docker.service: Start request repeated too quickly.
Dec 10 15:43:15 localhost.localdomain systemd[1]: docker.service: Failed with result 'exit-code'.
Dec 10 15:43:15 localhost.localdomain systemd[1]: Failed to start Docker Application Container Engine.
```

<br/>

- Settings of `firewalld` (active zones):
```
$ firewall-cmd --get-active-zones 
FedoraWorkstation
  interfaces: enp0s31f6
docker
  interfaces: br-59f818ed6e85
libvirt
  interfaces: virbr0
trusted
  interfaces: docker0
```

<br/>

- Have installed Docker 19.x successfully by using https://github.com/docker/for-linux/issues/955#issuecomment-694825085

<br/>

- Switch either `iptables` or `nftables` does not help.

**Comment by thaJeztah** [comment] 2020-12-10 14:12
This looks like a duplicate of https://github.com/moby/moby/issues/41609, and is likely because of the manual changes you mentioned

Reverting those changes should probably fix this (see https://github.com/moby/moby/issues/41609#issuecomment-725396025)

We'll have a look at adding a note about this in the release notes, but let me close this as duplicate of the other issue (feel free to continue the conversation after I closed)

**Closed by thaJeztah** 2020-12-10 14:12 UTC

**Comment by pilotman28** [comment] 2021-01-17 03:16
I had this same problem with 5:20.10.2~3-0~ubuntu-focal tonight. I was able to resolve the error by removing 'docker0' interface from one of the firewalld zones. This fix worked with no further changes required.
