### ISSUE TITLE
Please provide repo for docker-ce on Fedora 29

### ISSUE THREAD

**Issue by mattmccarty** [docker/for-linux#430] opened 2018-09-04 15:35 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
Installation on Fedora 29 should have a $releasever available.

### Actual behavior
Installation path for 29 is missing from https://download.docker.com/linux/fedora/

### Steps to reproduce the behavior
`sudo dnf config-manager \
    --add-repo \
    https://download.docker.com/linux/fedora/docker-ce.repo

sudo dnf install docker-ce`

Same issue as reported for fedora 26 originally: 
https://github.com/docker/for-linux/issues/35

**Comment by seemethere** [comment] 2018-09-04 16:08
Release schedule is currently sitting at [October 30](https://fedoraproject.org/wiki/Releases/29/Schedule)

This'll probably be added to nightly builds some point in the near future but may not get added to a stable release immediately.

Will update this comment when I have a PR ready.

**Comment by lig** [comment] 2018-10-31 06:15
The fact this is caused by the intended release policy doesn't make this less annoying for users.
A brief history of this:
* https://github.com/docker/for-linux/issues/295
* https://github.com/docker/for-linux/issues/173
* https://github.com/docker/for-linux/issues/164
* https://github.com/docker/for-linux/issues/143
* https://github.com/docker/for-linux/issues/35

Nobody except a couple of Docker devs benefits from such a policy.

**Comment by mwooller** [comment] 2018-10-31 08:01
I find the Docker position odd... Why push people to your own repo (as directed in the docs) on the understand that it will provide a better experience, and then neglect that repo?

The Fedora schedule is well publicised and well understood, why is it so hard to stay (relatively) in step?

**Comment by brumle80** [comment] 2018-10-31 10:24
also no point in enabling nightly as containerd.io is missing so install will fail anyways.

**Comment by trzecieu** [comment] 2018-10-31 13:35
@brumle80 You workaround this by installing containerd.io from F28, works fine. Might be a good alternative until stable F29 is ready.
```bash
# from F29
dnf install https://download.docker.com/linux/fedora/29/x86_64/nightly/Packages/docker-ce-cli-0.0.0.20181027050239.c7c18e3-0.fc29.x86_64.rpm
# from F28, as the docker-ce requires `containerd.io` to be installed (instead of containerd in system?)
dnf install https://download.docker.com/linux/fedora/28/x86_64/stable/Packages/containerd.io-1.2.0-2.2.rc.2.1.fc28.x86_64.rpm
# from F29
dnf install https://download.docker.com/linux/fedora/29/x86_64/nightly/Packages/docker-ce-0.0.0.20181027050239.c7c18e3-0.fc29.x86_64.rpm
```

**Comment by cpuguy83** [comment] 2018-10-31 13:51
> Nobody except a couple of Docker devs benefits from such a policy.

Keep in mind there is not unlimited resources. Packaging work is gruesome, and I suspect will require a complete overhaul of how packages are built here in order to support unreleased distro versions. This work, I'm told, is scheduled but will take some time.

Reality rarely reflects ideals.

**Comment by geerlingguy** [comment] 2018-10-31 14:00
Fedora 29 was just released yesterday... I'm willing to be patient as it's not like anyone's holding a gun to my head forcing me to stop using Fedora 27 and 28 today. As @cpuguy83 says, packaging maintenance is not trivial :)

**Comment by cpuguy83** [comment] 2018-11-01 13:19
@lig I understand your frustration and so does everyone who actually works on this.

Keep in mind that maybe there is more involved than you understand from your past experience.

If it was simple and quick it would be done.

Stability of existing and ongoing releases is of higher importance than adding more to the support matrix.

**Comment by d4rkd0s** [comment] 2018-11-01 17:46
We can chat all day about "hard" or "easy", where are we at with a date? Or is there a page we can check for support rollout? Similar to comment here: https://github.com/docker/for-linux/issues/164#issuecomment-345433291

**Comment by Corsseir** [comment] 2018-11-01 22:15
> @lig I understand your frustration and so does everyone who actually works on this.
> 
> Keep in mind that maybe there is more involved than you understand from your past experience.
> 
> If it was simple and quick it would be done.
> 
> Stability of existing and ongoing releases is of higher importance than adding more to the support matrix.

No one said that it is easy. The people are frustrated 'cause they know that it is achievable by looking on nodesource, rpmfusion or bublebee. Docker team could use Fedora 29 beta or even alpha to prepare repo for stable release. This is popular practice for those who care.

**Comment by geekow** [comment] 2018-11-07 21:01
For the moment only the nightly build are available for Fedora 29, if you type 
`sudo dnf config-manager --set-enabled docker-ce-nightly` you should be able to run sudo dnf install docker-ce after.

**Comment by seemethere** [comment] 2018-11-08 21:16
Hey guys! We're aware that packages do not yet exist for the `18.09` code line they are scheduled for our next patch release `18.09.1`, we're still tracking this issue and intend to ship.

Going to lock this topic for now and will provide updates when packages become available!

As @geekow stated above we have nightlies available for Fedora 29 using:

```bash
curl -fsSL get.docker.com | CHANNEL=nightly sh
```

**Comment by seemethere** [comment] 2018-12-03 21:45
Update for everyone here!

We just released the first beta for Fedora 29!

You can install it once again with the convenience script:

```
curl -fsSL get.docker.com | CHANNEL=test sh
```

**Comment by thaJeztah** [comment] 2022-06-05 13:54
Let me close this ticket, as this is really old now (and we have packages for current fedora versions)

**Closed by thaJeztah** 2022-06-05 13:54 UTC
