### ISSUE TITLE
Can not install  docker-ce on CentOS 8?

### ISSUE THREAD

**Issue by edoger** [docker/for-linux#965] opened 2020-03-30 07:52 UTC
* [ ] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Steps to reproduce the behavior

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

```
package docker-ce-3:19.03.8-3.el7.x86_64 requires containerd.io >= 1.2.2-3, but none of the providers can be installed
  - cannot install the best candidate for the job
  - package containerd.io-1.2.10-3.2.el7.x86_64 is excluded
  - package containerd.io-1.2.13-3.1.el7.x86_64 is excluded
  - package containerd.io-1.2.2-3.3.el7.x86_64 is excluded
  - package containerd.io-1.2.2-3.el7.x86_64 is excluded
  - package containerd.io-1.2.4-3.1.el7.x86_64 is excluded
  - package containerd.io-1.2.5-3.1.el7.x86_64 is excluded
  - package containerd.io-1.2.6-3.3.el7.x86_64 is excluded
```

**Comment by edoger** [comment] 2020-03-30 07:53
Is CenOS8 not supported yet?

**Comment by tomsnuvv** [comment] 2020-03-30 14:58
This is duplicate of #873

**Comment by thaJeztah** [comment] 2020-03-30 20:40
closing as duplicate of https://github.com/docker/for-linux/issues/873

**Closed by thaJeztah** 2020-03-30 20:40 UTC
