### ISSUE TITLE
Fedora container new files are root

### ISSUE THREAD

**Issue by jrock2004** [docker/for-linux#145] opened 2017-10-29 21:27 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
When running a container with a mounted volume and in the container I create a new file, on the host OS I am expecting the new file to be owned by the logged in user

### Actual behavior
New files are being created as root

### Steps to reproduce the behavior
- Create a new directory and enter it
- Type the following command

```
$ docker run -it -v $(pwd):/app jrock2004/emberjs:2.16.0-alpine sh 
```
- Create a new file like `touch index.html`
- On the host OS, open the file that was created in the container and it should be editable

**Output of `docker version`:**

```
Docker version 17.09.0-ce, build afdb6d4
```

**Output of `docker info`:**

```
Containers: 5
 Running: 1
 Paused: 0
 Stopped: 4
Images: 2
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.13.9-200.fc26.x86_64
Operating System: Fedora 26 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.66GiB
Name: devbox
ID: ZBYO:YRTL:K7FX:6RMT:CE36:LAPH:AMIO:CLVT:HN4R:46WS:AXLL:DUXM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

```
NAME=Fedora
VERSION="26 (Workstation Edition)"
ID=fedora
VERSION_ID=26
PRETTY_NAME="Fedora 26 (Workstation Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:26"
HOME_URL="https://fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=26
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=26
PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

I have run this container on a mac and windows machine and it works just fine. So I do not think it has to do with the image

**Comment by thaJeztah** [comment] 2017-10-29 21:45
This is not a bug; those files are created by the process running inside the container, and will get ownership and permissions of the container's process (in this case `root`). Docker for Mac/Docker for Windows run the docker daemon (and containers) in a thin VM, and use some "magic" to translate permissions, but on a Linux system, host directories  are directly mounted inside the container, so files/permissions inside the container are exactly the same on the host.

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-10-29 21:45 UTC

**Comment by jrock2004** [comment] 2017-10-29 22:02
@thaJeztah so how would I create files than?

**Comment by jrock2004** [comment] 2017-10-29 22:09
@thaJeztah you said `but on a Linux system, host directories are directly mounted inside the container, so files/permissions inside the container are exactly the same on the host.`, but if that was the case, then why did the container mount it as root? The folder that is mounted is not owned by root. So unless I am misunderstanding you, then this is an issue

**Comment by thaJeztah** [comment] 2017-10-29 22:35
Inside the container, the process runs as root; try running `whoami` inside the container, and youll see it prints `root`

**Comment by jrock2004** [comment] 2017-10-31 03:48
I am sorry if I am missing the point, so with a Linux host, there is no way that I can have the container create a file in the mounted location? If I can, how would I do that? @thaJeztah

**Comment by thaJeztah** [comment] 2017-10-31 06:52
> So with a Linux host, there is no way that I can have the container create a file in the mounted location?

Yes you can, but it will be owned by the user/group that the container's process runs as (which may be `root`).
