### ISSUE TITLE
docker version get different value

### ISSUE THREAD

**Issue by phxism** [docker/for-linux#1251] opened 2021-06-01 09:19 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
```
docker version
docker -H tcp://0.0.0.0:2375 version
docker -H unix:///var/run/docker.sock version
docker -H fd:// version

docker info
docker -H tcp://0.0.0.0:2375 info
docker -H unix:///var/run/docker.sock info
docker -H fd:// info
```
four types of docker version/info commands above should print same result

1. Both Client: Docker Engine and Server: Docker Engine are 1.40 according to `docker version` but **docker -H fd://** get different one:1.41
2. engine version is at least 1.40+, error message **error during connect: Get http:///v1.24/version: http: no Host in request URL** where does **v1.24**  come from?

### Actual behavior

> [root@node2 ~]# docker -H fd:// version
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:45:33 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
error during connect: Get http:///v1.24/version: http: no Host in request URL

>  [root@node2 ~]# docker version
> Client: Docker Engine - Community
>  Version:           20.10.6
>  API version:       1.40
>  Go version:        go1.13.15
>  Git commit:        370c289
>  Built:             Fri Apr  9 22:45:33 2021
>  OS/Arch:           linux/amd64
>  Context:           default
>  Experimental:      true
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          19.03.15
>   API version:      1.40 (minimum version 1.12)
>   Go version:       go1.13.15
>   Git commit:       99e3ed8919
>   Built:            Sat Jan 30 03:16:33 2021
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.4.6
>   GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
>  runc:
>   Version:          1.0.0-rc95
>   GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
>  docker-init:
>   Version:          0.18.0
>   GitCommit:        fec3683

### Steps to reproduce the behavior

**Output of `docker version`:**

```
[root@node2 ~]# clear
[root@node2 ~]# docker version
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:45:33 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.15
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       99e3ed8919
  Built:            Sat Jan 30 03:16:33 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
[root@node2 ~]# docker -H tcp://0.0.0.0:2375 version
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:45:33 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.15
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       99e3ed8919
  Built:            Sat Jan 30 03:16:33 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
[root@node2 ~]# docker -H unix:///var/run/docker.sock version
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:45:33 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.15
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       99e3ed8919
  Built:            Sat Jan 30 03:16:33 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
[root@node2 ~]# docker -H fd:// version
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:45:33 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
error during connect: Get http:///v1.24/version: http: no Host in request URL
[root@node2 ~]#

```

**Output of `docker info`:**

```
[root@node3 ~]# docker -H fd:// info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc.)

Server:
ERROR: error during connect: Get http:///v1.24/info: http: no Host in request URL
errors pretty printing info
[root@node3 ~]# docker -H fd:// version
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:45:33 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
error during connect: Get http:///v1.24/version: http: no Host in request URL
[root@node3 ~]# docker -H unix:///var/run/docker.sock info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc.)

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 19
 Server Version: 19.03.15
 Storage Driver: devicemapper
  Pool Name: docker-253:0-144801460-pool
  Pool Blocksize: 65.54kB
  Base Device Size: 10.74GB
  Backing Filesystem: xfs
  Udev Sync Supported: true
  Data file: /dev/loop0
  Metadata file: /dev/loop1
  Data loop file: /var/lib/docker/devicemapper/devicemapper/data
  Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
  Data Space Used: 3.368GB
  Data Space Total: 107.4GB
  Data Space Available: 27.53GB
  Metadata Space Used: 20.23MB
  Metadata Space Total: 2.147GB
  Metadata Space Available: 2.127GB
  Thin Pool Minimum Free Space: 10.74GB
  Deferred Removal Enabled: true
  Deferred Deletion Enabled: true
  Deferred Deleted Device Count: 0
  Library Version: 1.02.170-RHEL7 (2020-03-24)
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.25.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.934GiB
 Name: node3
 ID: LR67:NPKA:7C3L:GGVO:UC6I:ETHW:H6XU:CZJV:O35B:NKX5:X4B4:7SJK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  registry.baison.net:9443
  127.0.0.0/8
 Registry Mirrors:
  https://k3e9zvnu.mirror.aliyuncs.com/
  https://docker.mirrors.ustc.edu.cn/
  https://registry.docker-cn.com/
 Live Restore Enabled: false

WARNING: API is accessible on http://0.0.0.0:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
WARNING: the devicemapper storage-driver is deprecated, and will be removed in a future release.
WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
[root@node3 ~]# docker -H tcp://0.0.0.0:2375 info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc.)

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 19
 Server Version: 19.03.15
 Storage Driver: devicemapper
  Pool Name: docker-253:0-144801460-pool
  Pool Blocksize: 65.54kB
  Base Device Size: 10.74GB
  Backing Filesystem: xfs
  Udev Sync Supported: true
  Data file: /dev/loop0
  Metadata file: /dev/loop1
  Data loop file: /var/lib/docker/devicemapper/devicemapper/data
  Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
  Data Space Used: 3.368GB
  Data Space Total: 107.4GB
  Data Space Available: 27.53GB
  Metadata Space Used: 20.23MB
  Metadata Space Total: 2.147GB
  Metadata Space Available: 2.127GB
  Thin Pool Minimum Free Space: 10.74GB
  Deferred Removal Enabled: true
  Deferred Deletion Enabled: true
  Deferred Deleted Device Count: 0
  Library Version: 1.02.170-RHEL7 (2020-03-24)
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.25.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.934GiB
 Name: node3
 ID: LR67:NPKA:7C3L:GGVO:UC6I:ETHW:H6XU:CZJV:O35B:NKX5:X4B4:7SJK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  registry.baison.net:9443
  127.0.0.0/8
 Registry Mirrors:
  https://k3e9zvnu.mirror.aliyuncs.com/
  https://docker.mirrors.ustc.edu.cn/
  https://registry.docker-cn.com/
 Live Restore Enabled: false

WARNING: API is accessible on http://0.0.0.0:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
WARNING: the devicemapper storage-driver is deprecated, and will be removed in a future release.
WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
[root@node3 ~]# docker  info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc.)

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 19
 Server Version: 19.03.15
 Storage Driver: devicemapper
  Pool Name: docker-253:0-144801460-pool
  Pool Blocksize: 65.54kB
  Base Device Size: 10.74GB
  Backing Filesystem: xfs
  Udev Sync Supported: true
  Data file: /dev/loop0
  Metadata file: /dev/loop1
  Data loop file: /var/lib/docker/devicemapper/devicemapper/data
  Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
  Data Space Used: 3.368GB
  Data Space Total: 107.4GB
  Data Space Available: 27.53GB
  Metadata Space Used: 20.23MB
  Metadata Space Total: 2.147GB
  Metadata Space Available: 2.127GB
  Thin Pool Minimum Free Space: 10.74GB
  Deferred Removal Enabled: true
  Deferred Deletion Enabled: true
  Deferred Deleted Device Count: 0
  Library Version: 1.02.170-RHEL7 (2020-03-24)
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.25.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.934GiB
 Name: node3
 ID: LR67:NPKA:7C3L:GGVO:UC6I:ETHW:H6XU:CZJV:O35B:NKX5:X4B4:7SJK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  registry.baison.net:9443
  127.0.0.0/8
 Registry Mirrors:
  https://k3e9zvnu.mirror.aliyuncs.com/
  https://docker.mirrors.ustc.edu.cn/
  https://registry.docker-cn.com/
 Live Restore Enabled: false

WARNING: API is accessible on http://0.0.0.0:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
WARNING: the devicemapper storage-driver is deprecated, and will be removed in a future release.
WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
[root@node3 ~]#

```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
VMware 
```
[rancher@node3 ~]$ cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
[rancher@node3 ~]$ uname -r
3.10.0-1160.25.1.el7.x86_64
[root@node3 ~]# yum list installed | grep docker
containerd.io.x86_64                        1.4.6-3.1.el7              @docker-ce-stable
docker-ce.x86_64                            3:19.03.15-3.el7           @docker-ce-stable
docker-ce-cli.x86_64                        1:20.10.6-3.el7            @docker-ce-stable
docker-scan-plugin.x86_64                   0.7.0-3.el7                @docker-ce-stable
[root@node3 ~]#

```

**Comment by thaJeztah** [comment] 2021-06-15 10:22
This is the expected behavior; the `docker` cli performs API version negotiation with the Docker Engine it's connecting to. If the engine it's connected to only supports an older version of the Docker API, then the cli will downgrade the API version it uses to the older API. With that feature, it's possible for (e.g.) a `docker 20.10` CLI to connect to a `docker 19.03` (or older) engine.

Note: I do see there's a regression in the current version of the CLI, where it doesn't show that it downgraded; here's for example a docker 18.09 CLI connection to a (very old) docker 17.06 engine; the docker 18.09 CLI supports up until API version 1.39, but the engine supports up until API version 1.30, so the CLI prints that it downgraded to that older version (` (downgraded from 1.39)`).

```
Client: Docker Engine - Community
 Version:           18.09.9
 API version:       1.30 (downgraded from 1.39)
 Go version:        go1.11.13
 Git commit:        039a7df9ba
 Built:             Wed Sep  4 16:50:02 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          17.06.2-ce
  API version:      1.30 (minimum version 1.12)
  Go version:       go1.8.3
  Git commit:       cec0b72
  Built:            Tue Sep  5 19:59:19 2017
  OS/Arch:          linux/amd64
  Experimental:     false
```


From a quick search, I _think_ that regression may have been in https://github.com/docker/cli/pull/2095, but perhaps you could open a ticket for that in the docker cli repository (https://github.com/docker/cli) ?


I'm closing this ticket, because the behavior in itself is working as expected, but feel free to continue the conversation.

**Closed by thaJeztah** 2021-06-15 10:22 UTC
