### ISSUE TITLE
Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:297: copying bootstrap data to pipe caused \"write init-p: broken pipe\"": unknow

### ISSUE THREAD

**Issue by TidyHuang** [docker/for-linux#834] opened 2019-10-22 10:31 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior
start docker failed 

### Actual behavior
start docker successful

### Steps to reproduce the behavior
1. install open network linux system which is pulled from debian with the following version
Linux  3.16.56-OpenNetworkLinux #1 SMP Tue Sep 17 02:05:47 UTC 2019 x86_64 GNU/Linux
2. start docker container 

**Output of `docker version`:**

```
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:28:55 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:27:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:28:55 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:27:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
root@SMARTTSW-SQA-226:~# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 18.06.3-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: a592beb5bc4c4092b1b1bac971afed27687340c5
init version: fec3683
Kernel Version: 3.16.56-OpenNetworkLinux
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 31.26GiB
Name: xyz
ID: C6RO:WNDM:J4KV:MU7A:6L2O:W6KS:7VYY:4XE4:K2HC:OB6I:6SVZ:W37T
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by thaJeztah** [comment] 2019-10-23 18:49
Are you still able to reproduce on a current version of Docker (19.03 at time of writing)? Note that Docker 18.06 reached EOL a long time ago, and that current versions no longer support Debian Jessie; I know there's been several issues with the 3.16 kernel that Jessie uses, so that might be related as well

**Comment by thaJeztah** [comment] 2019-10-23 18:50
I'll close this issue, because this version of docker is no longer supported, but feel free to open a new ticket if you're still able to reproduce on a current version

**Closed by thaJeztah** 2019-10-23 18:50 UTC

**Comment by fcgravalos** [comment] 2019-12-18 16:25
We're hitting this issue too with Docker CE 18.09, Debian Stretch and kernel 4.19:

```
Server: Docker Engine - Community
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       2d0083d
  Built:            Thu Jun 27 17:23:02 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

```
cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```
 uname -r
4.19.0-0.bpo.4-amd64
```
