### ISSUE TITLE
Unable to install on Fedora 29

### ISSUE THREAD

**Issue by manishtomar** [docker/for-linux#472] opened 2018-11-05 18:52 UTC
@jg110 commented on [Mon Nov 05 2018](https://github.com/docker/distribution/issues/2751)

I'm not sure if this is the right place to file this issue, so if there's a better place, please direct me there.

Currently [the only repository available for Fedora 29](https://download.docker.com/linux/fedora/29/x86_64/nightly/Packages/) consists of nightly builds of docker-ce. When attempting to install any of these packages, dnf returns an error: `nothing provides containerd.io needed by docker-ce-3:0.0.0.20181104010403.904d4fe-0.fc29.x86_64`. The error is repeated for each package available in the repository. It seems that at least one build of containerd.io needs to be present in the repository for docker-ce to install correctly, unless an older version is already present on the system.

**Comment by thaJeztah** [comment] 2018-11-08 20:57
this is a duplicate of https://github.com/docker/for-linux/issues/430

**Closed by thaJeztah** 2018-11-08 20:57 UTC

**Comment by lig** [comment] 2018-11-14 07:53
@thaJeztah as the #430 issue is locked now for "nonobvious" reasons I would like to mention my comment on the `docker-compose` project's issue tracker here as it is applicable to this subject in the same way as to that one.

https://github.com/docker/compose/issues/6316#issuecomment-438564025

**Comment by vinayakshnd** [comment] 2019-01-22 09:22
@thaJeztah I see now on [docker-ce installation page ](https://docs.docker.com/install/linux/docker-ce/fedora/) that Fedora 29 is the supported platform. When installed docker-ce  using
```
dnf -y install dnf-plugins-core
dnf config-manager \
    --add-repo \
    https://download.docker.com/linux/fedora/docker-ce.repo
dnf install docker-ce
```
Bellow Docker version is installed
```
docker -v
Docker version 18.09.1, build 4c52b90  
```
If I run busybox container, I get bellow error:

```
docker run --rm -it busybox
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
57c14dd66db0: Pull complete 
Digest: sha256:7964ad52e396a6e045c39b5a44438424ac52e12e4d5a25d94895f2058cb863a0
Status: Downloaded newer image for busybox:latest
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"sh\": executable file not found in $PATH": unknown.

```
