### ISSUE TITLE
Docker-ce's container lost network connection after a while

### ISSUE THREAD

**Issue by wonleing** [docker/for-linux#999] opened 2020-05-14 03:08 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Actual behavior
After running a while (without any action), all docker containers lost network connection
restart dockerd can fix this.

**Output of `docker version`:**

```
Version: docker-ce 
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        627a883112
Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       627a883
```

**Output of `docker info`:**

```
Containers: 14
 Running: 0
 Paused: 0
 Stopped: 14
Images: 61
Server Version: 18.09.5
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 44f0a1311a4e687b2f1bca5cb7cd27c2b9e4fbbc.m
runc version: ceabc6b382d8d31d585bef3588f3ca5387d3b2f2
init version: fec3683
Kernel Version: 4.19.90-3-server-sw64-aere
Operating System: uos 20 SP1
OSType: linux
Architecture: sw_64
CPUs: 16
Total Memory: 125.4GiB
Name: uos-pc
ID: VBEO:26BZ:D4KI:QP25:YU74:P7VF:KN2Z:VFUP:HNJ2:OG7A:ACT7:QHTK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

I checked system journal about docker,  only find this warning:
level=warning msg="Seccomp is not enabled in your kernel, running container without default profile."
level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"

Anyway to find out what is broken? anyway to fix it except upgrade docker version?

**Comment by thaJeztah** [comment] 2020-05-27 14:44
Hard to tell. Did the machine switch network connections? Are you able to reproduce this on a current version of Docker (Docker 18.09 reached EOL, so a current 19.03.x version).

I see you're running on `uos`, which is not a Linux distribution that's supported by our official packages, and not something we test for, so it might be best to report this issue with them first (to do the initial triage)

I'm closing this ticket because both the docker version, and the distribution are not something we support, but feel free to continue the conversation

**Closed by thaJeztah** 2020-05-27 14:44 UTC
