### ISSUE TITLE
grpc: addrConn.createTransport failed to connect to {unix:///run/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = \"transport

### ISSUE THREAD

**Issue by ajandlsxpro** [docker/for-linux#1438] opened 2022-10-17 09:24 UTC
![image](https://user-images.githubusercontent.com/65056862/196141232-2bf99c2b-cc19-4bff-955f-68b51310b599.png)

**Comment by AGI-chandler** [comment] 2022-12-13 04:13
Any progress/updates with this?  I'm seeing similar messages on our cluster trying to troubleshoot problems with docker there.  The strange thing is that, on our head node and compute node n010, `dockerd-rootless.sh` runs fine, but when it comes to the remaining compute nodes n011-n013, the warnings are like the following, after which dockerd terminates.
```
WARN[] waiting for response from boltdb open         plugin=bolt
WARN[] grpc: addrConn.createTransport failed to connect to {unix:///run/user/10063/docker/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = "transport: error while dialing: dial unix:///run/user/10063/docker/containerd/containerd.sock: timeout". Reconnecting...  module=grpc
failed to start containerd: timeout waiting for containerd to start
[rootlesskit:child ] error: command [/usr/bin/dockerd-rootless.sh] exited: exit status 1
[rootlesskit:parent] error: child exited: exit status 1
```

**Comment by thaJeztah** [comment] 2022-12-28 17:27
The error indicates that containerd is not running, or the containerd socket is not accessible/ listening.

What version of docker are you running? What Linux distribution? And how did you install docker (using packages from download.docker.com, or using packages from your Linux distribution)?

**Comment by JoaoOtavioS** [comment] 2022-12-28 18:23
Just giving my context to help with this issue, this happened to me a few days ago, I found it very strange, it started to happen in the new versions of the docker engine.

Docker Engine: 20.10.22
OS: Ubuntu 20.04 
All system updated.

**Comment by spwpun** [comment] 2023-02-10 12:09
I met the same error, the docker can start when I deleting the `/var/lib/docker/` and `/var/lib/containerd/`, but at the time, I lost my all containers. Is there some other solutions for this error?

**Comment by AGI-chandler** [comment] 2023-02-13 18:56
Well, in our case, in a clustered environment, it must have had something to do with shared resources between the nodes.  Fortunately the software we were trying to run had alternative options besides docker, so we got that particular software running.  For clustered usage of docker maybe something like `swarm` is more appropriate, but when I looked into it I don't think it supports rootless mode.  Anyway, for now, we just use docker in rootless mode on a single computer, the head node, and that is working fine.

**Comment by spwpun** [comment] 2023-02-16 02:05
So, this error might be caused by running the container with "--priveleged=True"?

**Comment by perlun** [comment] 2023-05-02 07:22
We are also seeing this with `--privileged` containers sometimes. More details: https://github.com/docker/for-linux/issues/517#issuecomment-1530997673

**Comment by thaJeztah** [comment] 2023-06-29 09:14
I don't think there's anything actionable in this ticket; as mentioned above (https://github.com/docker/for-linux/issues/1438#issuecomment-1366810209), this error indicates containerd is not running, for which there may be many reasons.


I'll close this ticket because of the above.

**Closed as not planned by thaJeztah** 2023-06-29 09:14 UTC
Labels: status/more-info-needed
