### ISSUE TITLE
Error using NFS for a volume defined on a parent image

### ISSUE THREAD

**Issue by ecsousa** [docker/for-linux#17] opened 2017-06-15 03:51 UTC
### Expected behavior
Docker should use the NFS shared volume

### Actual behavior
I'm getting an error like this: 

```
docker: Error response from daemon: chown /var/lib/docker/volumes/nfstest/_data: operation not permitted.
```

### Information

  - Linux distro: Ubuntu 16.04.2 LTS
  - Docker CE version: 17.05.0-ce

### Steps to reproduce the behavior

Using the following `Dockerfile`

``` Dockerfile
FROM linuxserver/sickrage

RUN /bin/true
```

Steps:

1. Build image: `docker build . -t test`
2. Create a NFS volume: `docker volume create --driver local --opt type=nfs --opt o=addr=192.168.1.1,rw --opt device=:/nfsshare nfstest`
3. Try to use NFS share on built image: `docker run -v nfstest:/tv test`

This was the most simple case I was able to reproduce the issue. If I remove the `RUN /bin/true`, everything works fine.

**Comment by cpuguy83** [comment] 2017-06-15 12:31
This is because when a container is spun up, if the volume is empty and the image has data at the defined volume path, Docker will copy and chown the data to the volume before starting the container up.
To avoid this behavior, you need to specify the volume like so: `-v nfstest:/tv:nocopy`
Alternatively you'd have to setup the nfs export to allow chowning.

**Comment by cpuguy83** [comment] 2017-06-15 12:32
Closing since this is working as intended.

**Closed by cpuguy83** 2017-06-15 12:32 UTC

**Comment by ecsousa** [comment] 2017-06-15 13:35
Thanks, the `nocopy` flag fixed my issue.

However I'm experiencing the issue using a non-empty NFS share, and the image volume is empty. So it seems to me that Docker is trying to copy data when it shouldn't.

Also it's very strange that Docker is not trying to copy data when using the original base image, `linuxserver/sickrage`.

It seems that when you do any command during build, Docker is marking untouched volumes as dirty.

**Comment by cpuguy83** [comment] 2017-06-15 14:09
The chown happens regardless of if there is any data in the image path.
We could probably improve this by only chowning if the UID/GID doesn't match.

**Comment by cpuguy83** [comment] 2017-06-15 14:36
opened moby/moby#33695
