### ISSUE TITLE
Build stopped to work after upgrade to docker 17.6.0-ce

### ISSUE THREAD

**Issue by phinfonet** [docker/for-linux#66] opened 2017-07-21 13:52 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Actual behavior
failed to build: shim error: json: cannot unmarshal array into Go struct field processState.capabilities of type specs.LinuxCapabilities

### Steps to reproduce the behavior
Build stopped to work after upgrade to 17.6.0-ce. Fixed downgrading to docker 17.5.0-ce

**Output of `docker version`:**

```
Docker version 17.05.0-ce, build 89658bed64
```

**Output of `docker info`:**

```
Containers: 11
 Running: 0
 Paused: 0
 Stopped: 11
Images: 34
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 66
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.37-1-MANJARO
Operating System: Manjaro Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.51GiB
Name: phinfonet
ID: MUT2:VATG:PNPS:US23:W4IG:GII6:KZCD:6X6H:XLCF:WJRH:YDWA:GEB3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment] 2017-07-21 14:03
duplicate of https://github.com/docker/for-linux/issues/61

There are no official packages for Arch Linux; the version of Docker you're running on Arch linux is not maintained here.

The problem here is that the Arch 17.06 package ships the wrong version of RunC, which is incompatible with Docker 17.06; see the output of `docker info` with 17.06 installed (Possibly other changes on configuration that may affect docker);

```
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4 (expected: 9c2d8d184e5da67c95d601382adf14862e4f2228)
```

I recommend opening an issue with the Arch linux packagers

I'm closing this issue because there's nothing that can be done here, but feel free to continue the conversation

**Closed by thaJeztah** 2017-07-21 14:03 UTC

**Comment by mimoralea** [comment] 2017-07-24 03:40
I had the same issue. A `sudo systemctl daemon-reload && sudo systemctl restart docker` fixed it.
