### ISSUE TITLE
multi-stage builds fail with userns-remap

### ISSUE THREAD

**Issue by sosnik** [docker/for-linux#1167] opened 2020-12-15 04:38 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

This is similar to #1040 (with a bit more details thrown in).

See also: https://github.com/moby/moby/issues/34645

### Expected behavior

Build should succeed :) 

### Actual behavior

Build (more specifically, `COPY`) fails with the following error:

```
Step 12/15 : COPY --from=build-env /app /app
failed to copy files: failed to copy directory: Error processing tar file(exit status 1): Container ID 268869 cannot be mapped to a host ID
```

### Steps to reproduce the behavior

Try any multi-stage build (for instance, with Google's `distroless` images) or the previously-mentioned moby issue.

I've seen similar issues filed all over the internet, but not with Docker itself. #1040 is the closest to the topic at hand. 

**Output of `docker version`:**

```
Client:
 Version:           19.03.14
 API version:       1.40
 Go version:        go1.15.6
 Git commit:        5eb3275d40
 Built:             Sat Dec  5 16:35:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.14
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.15.6
  Git commit:       5eb3275d40
  Built:            Sat Dec  5 16:35:26 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b.m
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 10
  Running: 0
  Paused: 0
  Stopped: 10
 Images: 84
 Server Version: 19.03.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b.m
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
  userns
 Kernel Version: 5.9.14-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.6GiB
 Name: REDACTE
 ID: REDACTED
 Docker Root Dir: /var/lib/docker/265536.265536
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

Physical archlinux.

I have tried with and without ` DOCKER_BUILDKIT=1` as suggested in #1040 but the result is still the same (which is why I thought this merited an issue of its own). 

### My Thoughts
What I believe is happening is that docker is trying to map the re-mapped uid to the final stage of the build, which is obviously failing because the final container doesn't have that UID range.  What it should be doing is preserving internal uid (if uid is 3000 in build stage, it should copy with 3000, not 268869 or whatever the host remap is)

**Comment by thaJeztah** [comment] 2020-12-23 14:17
Does the issue still reproduce with docker 20.10 ?

**Comment by haizz** [comment] 2021-03-29 15:26
@thaJeztah I'm having the same issue with docker 20.10.5, but DOCKER_BUILDKIT=1 seems to be working.

**Comment by thaJeztah** [comment] 2021-03-29 15:58
Thanks for testing; so looks like it's only in the classic builder; if possible I'd recommend using BuildKit (which will be the default builder in an upcoming release).

Let me close this ticket in favor of https://github.com/moby/moby/issues/34645, which is tracking the issue for the classic builder, so that the conversation doesn't diverge 👍

**Closed by thaJeztah** 2021-03-29 15:58 UTC
