### ISSUE TITLE
docker exit with code 139

### ISSUE THREAD

**Issue by GitSoftwareNow** [docker/for-linux#1013] opened 2020-05-21 00:39 UTC
when I run "docker run -it -d android:latest",but the console says
 root@ubuntu#docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                      PORTS               NAMES
7b606d820b89        android             "/anbox-init.sh"    15 hours ago        Exited (139) 15 hours ago                       condescending_jackson

root@test11:/home# docker logs 7b606d820b89
root@test11:/home# 

why?

**Comment by thaJeztah** [comment] 2020-05-27 12:45
There's some information in this comment: https://github.com/docker/for-linux/issues/1019#issuecomment-633410195

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/docker/for-linux/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2020-05-27 12:45 UTC
