### ISSUE TITLE
 Could not configure 'libc6:amd64'

### ISSUE THREAD

**Issue by subhash1997mandal** [docker/for-linux#1131] opened 2020-10-16 12:41 UTC
The following command
```RUN apt-get install libfontconfig --yes```
The following command gives the following error ```E: Could not configure 'libc6:amd64'. 
E: Could not perform immediate configuration on 'libcrypt1:amd64'. Please see man 5 apt.conf under APT::Immediate-Configure for details. (2)```
Tried on node version 14.11.0 docker version 19.03.13 os version 20.04 LTS

* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Steps to reproduce the behavior

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by ryan-williams** [comment] 2020-10-20 17:44
Here's a minimal Dockerfile that reproduces this for me:
```Dockerfile
FROM debian
RUN echo "deb http://ftp.us.debian.org/debian testing main" >> /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y curl
```
```bash
docker build .
```
<details>
  <summary>Full output</summary>
  
```
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM debian
 ---> 1510e8501783
Step 2/4 : RUN echo "deb http://ftp.us.debian.org/debian testing main" >> /etc/apt/sources.list
 ---> Using cache
 ---> 5700907e0153
Step 3/4 : RUN apt-get update
 ---> Using cache
 ---> c1d6523e9d53
Step 4/4 : RUN apt-get install -y curl
 ---> Running in d1262bf915c8
Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  libffi6 libhogweed4
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  ca-certificates gcc-10-base krb5-locales libbrotli1 libc-bin libc6 libcrypt1
  libcurl4 libffi7 libgcc-s1 libgnutls30 libgssapi-krb5-2 libhogweed6
  libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 libldap-2.4-2
  libldap-common libnettle8 libnghttp2-14 libnss-nis libnss-nisplus
  libp11-kit0 libpsl5 librtmp1 libsasl2-2 libsasl2-modules libsasl2-modules-db
  libssh2-1 libssl1.1 libtasn1-6 openssl publicsuffix
Suggested packages:
  glibc-doc libc-l10n locales gnutls-bin krb5-doc krb5-user
  libsasl2-modules-gssapi-mit | libsasl2-modules-gssapi-heimdal
  libsasl2-modules-ldap libsasl2-modules-otp libsasl2-modules-sql
Recommended packages:
  manpages
The following NEW packages will be installed:
  ca-certificates curl gcc-10-base krb5-locales libbrotli1 libcrypt1 libcurl4
  libffi7 libgcc-s1 libgssapi-krb5-2 libhogweed6 libk5crypto3 libkeyutils1
  libkrb5-3 libkrb5support0 libldap-2.4-2 libldap-common libnettle8
  libnghttp2-14 libnss-nis libnss-nisplus libpsl5 librtmp1 libsasl2-2
  libsasl2-modules libsasl2-modules-db libssh2-1 libssl1.1 openssl
  publicsuffix
The following packages will be upgraded:
  libc-bin libc6 libgnutls30 libp11-kit0 libtasn1-6
5 upgraded, 30 newly installed, 0 to remove and 73 not upgraded.
Need to get 11.4 MB of archives.
After this operation, 15.3 MB of additional disk space will be used.
Get:1 http://ftp.us.debian.org/debian testing/main amd64 gcc-10-base amd64 10.2.0-15 [199 kB]
Get:2 http://deb.debian.org/debian buster/main amd64 libssh2-1 amd64 1.8.0-2.1 [140 kB]
Get:3 http://ftp.us.debian.org/debian testing/main amd64 libgcc-s1 amd64 10.2.0-15 [41.4 kB]
Get:4 http://ftp.us.debian.org/debian testing/main amd64 libcrypt1 amd64 1:4.4.17-1 [86.9 kB]
Get:5 http://ftp.us.debian.org/debian testing/main amd64 libnss-nis amd64 3.1-3 [25.6 kB]
Get:6 http://ftp.us.debian.org/debian testing/main amd64 libc6 amd64 2.31-4 [2804 kB]
Get:7 http://ftp.us.debian.org/debian testing/main amd64 libnss-nisplus amd64 1.3-3 [21.6 kB]
Get:8 http://ftp.us.debian.org/debian testing/main amd64 libc-bin amd64 2.31-4 [804 kB]
Get:9 http://ftp.us.debian.org/debian testing/main amd64 libffi7 amd64 3.3-4 [22.9 kB]
Get:10 http://ftp.us.debian.org/debian testing/main amd64 libnettle8 amd64 3.6-2 [240 kB]
Get:11 http://ftp.us.debian.org/debian testing/main amd64 libhogweed6 amd64 3.6-2 [314 kB]
Get:12 http://ftp.us.debian.org/debian testing/main amd64 libp11-kit0 amd64 0.23.21-2 [335 kB]
Get:13 http://ftp.us.debian.org/debian testing/main amd64 libtasn1-6 amd64 4.16.0-2 [55.0 kB]
Get:14 http://ftp.us.debian.org/debian testing/main amd64 libgnutls30 amd64 3.6.15-4 [1189 kB]
Get:15 http://ftp.us.debian.org/debian testing/main amd64 krb5-locales all 1.17-10 [94.6 kB]
Get:16 http://ftp.us.debian.org/debian testing/main amd64 libssl1.1 amd64 1.1.1g-1 [1543 kB]
Get:17 http://ftp.us.debian.org/debian testing/main amd64 openssl amd64 1.1.1g-1 [846 kB]
Get:18 http://ftp.us.debian.org/debian testing/main amd64 ca-certificates all 20200601 [158 kB]
Get:19 http://ftp.us.debian.org/debian testing/main amd64 libbrotli1 amd64 1.0.9-2+b1 [282 kB]
Get:20 http://ftp.us.debian.org/debian testing/main amd64 libkrb5support0 amd64 1.17-10 [64.6 kB]
Get:21 http://ftp.us.debian.org/debian testing/main amd64 libk5crypto3 amd64 1.17-10 [115 kB]
Get:22 http://ftp.us.debian.org/debian testing/main amd64 libkeyutils1 amd64 1.6.1-2 [15.4 kB]
Get:23 http://ftp.us.debian.org/debian testing/main amd64 libkrb5-3 amd64 1.17-10 [366 kB]
Get:24 http://ftp.us.debian.org/debian testing/main amd64 libgssapi-krb5-2 amd64 1.17-10 [156 kB]
Get:25 http://ftp.us.debian.org/debian testing/main amd64 libsasl2-modules-db amd64 2.1.27+dfsg-2 [69.0 kB]
Get:26 http://ftp.us.debian.org/debian testing/main amd64 libsasl2-2 amd64 2.1.27+dfsg-2 [106 kB]
Get:27 http://ftp.us.debian.org/debian testing/main amd64 libldap-2.4-2 amd64 2.4.53+dfsg-1 [231 kB]
Get:28 http://ftp.us.debian.org/debian testing/main amd64 libnghttp2-14 amd64 1.41.0-3 [74.0 kB]
Get:29 http://ftp.us.debian.org/debian testing/main amd64 libpsl5 amd64 0.21.0-1.1 [55.3 kB]
Get:30 http://ftp.us.debian.org/debian testing/main amd64 librtmp1 amd64 2.4+20151223.gitfa8646d.1-2+b2 [60.8 kB]
Get:31 http://ftp.us.debian.org/debian testing/main amd64 libcurl4 amd64 7.72.0-1 [336 kB]
Get:32 http://ftp.us.debian.org/debian testing/main amd64 curl amd64 7.72.0-1 [264 kB]
Get:33 http://ftp.us.debian.org/debian testing/main amd64 libldap-common all 2.4.53+dfsg-1 [94.6 kB]
Get:34 http://ftp.us.debian.org/debian testing/main amd64 libsasl2-modules amd64 2.1.27+dfsg-2 [104 kB]
Get:35 http://ftp.us.debian.org/debian testing/main amd64 publicsuffix all 20200729.1725-1 [118 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 11.4 MB in 1s (13.1 MB/s)
Selecting previously unselected package gcc-10-base:amd64.
(Reading database ... 6677 files and directories currently installed.)
Preparing to unpack .../gcc-10-base_10.2.0-15_amd64.deb ...
Unpacking gcc-10-base:amd64 (10.2.0-15) ...
Setting up gcc-10-base:amd64 (10.2.0-15) ...
Selecting previously unselected package libgcc-s1:amd64.
(Reading database ... 6682 files and directories currently installed.)
Preparing to unpack .../libgcc-s1_10.2.0-15_amd64.deb ...
Unpacking libgcc-s1:amd64 (10.2.0-15) ...
Replacing files in old package libgcc1:amd64 (1:8.3.0-6) ...
Setting up libgcc-s1:amd64 (10.2.0-15) ...
(Reading database ... 6684 files and directories currently installed.)
Preparing to unpack .../libc6_2.31-4_amd64.deb ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Checking for services that may need to be restarted...
Checking init scripts...
Unpacking libc6:amd64 (2.31-4) over (2.28-10) ...
Selecting previously unselected package libcrypt1:amd64.
Preparing to unpack .../libcrypt1_1%3a4.4.17-1_amd64.deb ...
Unpacking libcrypt1:amd64 (1:4.4.17-1) ...
Selecting previously unselected package libnss-nis:amd64.
Preparing to unpack .../libnss-nis_3.1-3_amd64.deb ...
Unpacking libnss-nis:amd64 (3.1-3) ...
Selecting previously unselected package libnss-nisplus:amd64.
Preparing to unpack .../libnss-nisplus_1.3-3_amd64.deb ...
Unpacking libnss-nisplus:amd64 (1.3-3) ...
Setting up libcrypt1:amd64 (1:4.4.17-1) ...
Setting up libnss-nis:amd64 (3.1-3) ...
Setting up libnss-nisplus:amd64 (1.3-3) ...
Setting up libc6:amd64 (2.31-4) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Checking for services that may need to be restarted...
Checking init scripts...
Nothing to restart.
(Reading database ... 6698 files and directories currently installed.)
Preparing to unpack .../libc-bin_2.31-4_amd64.deb ...
Unpacking libc-bin (2.31-4) over (2.28-10) ...
Setting up libc-bin (2.31-4) ...
Selecting previously unselected package libffi7:amd64.
(Reading database ... 6698 files and directories currently installed.)
Preparing to unpack .../libffi7_3.3-4_amd64.deb ...
Unpacking libffi7:amd64 (3.3-4) ...
Setting up libffi7:amd64 (3.3-4) ...
Selecting previously unselected package libnettle8:amd64.
(Reading database ... 6703 files and directories currently installed.)
Preparing to unpack .../libnettle8_3.6-2_amd64.deb ...
Unpacking libnettle8:amd64 (3.6-2) ...
Setting up libnettle8:amd64 (3.6-2) ...
Selecting previously unselected package libhogweed6:amd64.
(Reading database ... 6711 files and directories currently installed.)
Preparing to unpack .../libhogweed6_3.6-2_amd64.deb ...
Unpacking libhogweed6:amd64 (3.6-2) ...
Setting up libhogweed6:amd64 (3.6-2) ...
(Reading database ... 6717 files and directories currently installed.)
Preparing to unpack .../libp11-kit0_0.23.21-2_amd64.deb ...
Unpacking libp11-kit0:amd64 (0.23.21-2) over (0.23.15-2) ...
Setting up libp11-kit0:amd64 (0.23.21-2) ...
(Reading database ... 6717 files and directories currently installed.)
Preparing to unpack .../libtasn1-6_4.16.0-2_amd64.deb ...
Unpacking libtasn1-6:amd64 (4.16.0-2) over (4.13-3) ...
Setting up libtasn1-6:amd64 (4.16.0-2) ...
(Reading database ... 6717 files and directories currently installed.)
Preparing to unpack .../libgnutls30_3.6.15-4_amd64.deb ...
Unpacking libgnutls30:amd64 (3.6.15-4) over (3.6.7-4+deb10u5) ...
Setting up libgnutls30:amd64 (3.6.15-4) ...
Selecting previously unselected package krb5-locales.
(Reading database ... 6716 files and directories currently installed.)
Preparing to unpack .../00-krb5-locales_1.17-10_all.deb ...
Unpacking krb5-locales (1.17-10) ...
Selecting previously unselected package libssl1.1:amd64.
Preparing to unpack .../01-libssl1.1_1.1.1g-1_amd64.deb ...
Unpacking libssl1.1:amd64 (1.1.1g-1) ...
Selecting previously unselected package openssl.
Preparing to unpack .../02-openssl_1.1.1g-1_amd64.deb ...
Unpacking openssl (1.1.1g-1) ...
Selecting previously unselected package ca-certificates.
Preparing to unpack .../03-ca-certificates_20200601_all.deb ...
Unpacking ca-certificates (20200601) ...
Selecting previously unselected package libbrotli1:amd64.
Preparing to unpack .../04-libbrotli1_1.0.9-2+b1_amd64.deb ...
Unpacking libbrotli1:amd64 (1.0.9-2+b1) ...
Selecting previously unselected package libkrb5support0:amd64.
Preparing to unpack .../05-libkrb5support0_1.17-10_amd64.deb ...
Unpacking libkrb5support0:amd64 (1.17-10) ...
Selecting previously unselected package libk5crypto3:amd64.
Preparing to unpack .../06-libk5crypto3_1.17-10_amd64.deb ...
Unpacking libk5crypto3:amd64 (1.17-10) ...
Selecting previously unselected package libkeyutils1:amd64.
Preparing to unpack .../07-libkeyutils1_1.6.1-2_amd64.deb ...
Unpacking libkeyutils1:amd64 (1.6.1-2) ...
Selecting previously unselected package libkrb5-3:amd64.
Preparing to unpack .../08-libkrb5-3_1.17-10_amd64.deb ...
Unpacking libkrb5-3:amd64 (1.17-10) ...
Selecting previously unselected package libgssapi-krb5-2:amd64.
Preparing to unpack .../09-libgssapi-krb5-2_1.17-10_amd64.deb ...
Unpacking libgssapi-krb5-2:amd64 (1.17-10) ...
Selecting previously unselected package libsasl2-modules-db:amd64.
Preparing to unpack .../10-libsasl2-modules-db_2.1.27+dfsg-2_amd64.deb ...
Unpacking libsasl2-modules-db:amd64 (2.1.27+dfsg-2) ...
Selecting previously unselected package libsasl2-2:amd64.
Preparing to unpack .../11-libsasl2-2_2.1.27+dfsg-2_amd64.deb ...
Unpacking libsasl2-2:amd64 (2.1.27+dfsg-2) ...
Selecting previously unselected package libldap-2.4-2:amd64.
Preparing to unpack .../12-libldap-2.4-2_2.4.53+dfsg-1_amd64.deb ...
Unpacking libldap-2.4-2:amd64 (2.4.53+dfsg-1) ...
Selecting previously unselected package libnghttp2-14:amd64.
Preparing to unpack .../13-libnghttp2-14_1.41.0-3_amd64.deb ...
Unpacking libnghttp2-14:amd64 (1.41.0-3) ...
Selecting previously unselected package libpsl5:amd64.
Preparing to unpack .../14-libpsl5_0.21.0-1.1_amd64.deb ...
Unpacking libpsl5:amd64 (0.21.0-1.1) ...
Selecting previously unselected package librtmp1:amd64.
Preparing to unpack .../15-librtmp1_2.4+20151223.gitfa8646d.1-2+b2_amd64.deb ...
Unpacking librtmp1:amd64 (2.4+20151223.gitfa8646d.1-2+b2) ...
Selecting previously unselected package libssh2-1:amd64.
Preparing to unpack .../16-libssh2-1_1.8.0-2.1_amd64.deb ...
Unpacking libssh2-1:amd64 (1.8.0-2.1) ...
Selecting previously unselected package libcurl4:amd64.
Preparing to unpack .../17-libcurl4_7.72.0-1_amd64.deb ...
Unpacking libcurl4:amd64 (7.72.0-1) ...
Selecting previously unselected package curl.
Preparing to unpack .../18-curl_7.72.0-1_amd64.deb ...
Unpacking curl (7.72.0-1) ...
Selecting previously unselected package libldap-common.
Preparing to unpack .../19-libldap-common_2.4.53+dfsg-1_all.deb ...
Unpacking libldap-common (2.4.53+dfsg-1) ...
Selecting previously unselected package libsasl2-modules:amd64.
Preparing to unpack .../20-libsasl2-modules_2.1.27+dfsg-2_amd64.deb ...
Unpacking libsasl2-modules:amd64 (2.1.27+dfsg-2) ...
Selecting previously unselected package publicsuffix.
Preparing to unpack .../21-publicsuffix_20200729.1725-1_all.deb ...
Unpacking publicsuffix (20200729.1725-1) ...
Setting up libkeyutils1:amd64 (1.6.1-2) ...
Setting up libpsl5:amd64 (0.21.0-1.1) ...
Setting up libssl1.1:amd64 (1.1.1g-1) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Setting up libbrotli1:amd64 (1.0.9-2+b1) ...
Setting up libsasl2-modules:amd64 (2.1.27+dfsg-2) ...
Setting up libnghttp2-14:amd64 (1.41.0-3) ...
Setting up krb5-locales (1.17-10) ...
Setting up libldap-common (2.4.53+dfsg-1) ...
Setting up libkrb5support0:amd64 (1.17-10) ...
Setting up libsasl2-modules-db:amd64 (2.1.27+dfsg-2) ...
Setting up librtmp1:amd64 (2.4+20151223.gitfa8646d.1-2+b2) ...
Setting up libk5crypto3:amd64 (1.17-10) ...
Setting up libsasl2-2:amd64 (2.1.27+dfsg-2) ...
Setting up libssh2-1:amd64 (1.8.0-2.1) ...
Setting up libkrb5-3:amd64 (1.17-10) ...
Setting up openssl (1.1.1g-1) ...
Setting up publicsuffix (20200729.1725-1) ...
Setting up libldap-2.4-2:amd64 (2.4.53+dfsg-1) ...
Setting up ca-certificates (20200601) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Updating certificates in /etc/ssl/certs...
126 added, 0 removed; done.
Setting up libgssapi-krb5-2:amd64 (1.17-10) ...
Setting up libcurl4:amd64 (7.72.0-1) ...
Setting up curl (7.72.0-1) ...
Processing triggers for libc-bin (2.31-4) ...
Processing triggers for ca-certificates (20200601) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
E: Could not configure 'libc6:amd64'.
E: Could not perform immediate configuration on 'libnss-nis:amd64'. Please see man 5 apt.conf under APT::Immediate-Configure for details. (2)
The command '/bin/sh -c apt-get install -y curl' returned a non-zero code: 100
```
</details>

One workaround ([xref](https://supportcenter.devexpress.com/ticket/details/t940631/could-not-configure-libc6-amd64-in-docker-build)) is to disable "immediate configuration" in the apt-get install:
```Dockerfile
FROM debian
RUN echo "deb http://ftp.us.debian.org/debian testing main" >> /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y curl -o APT::Immediate-Configure=0
```

Removing the `/etc/apt/sources.list` addition also works around it (though in my use case I need it in order to get more recent versions of e.g. `git`, iirc).

**Comment by subhash1997mandal** [comment] 2020-10-21 04:06
Thanks, this worked for me. Will be closing it now.

**Comment by marco-c** [comment] 2020-10-21 09:17
I wouldn't close it, the bug is still reproducible, the workaround is not a fix.

**Comment by ksbhaskar** [comment] 2020-10-21 19:51
Since the system is a chimera of Stable and Testing, would a more appropriate fix not be `apt-get install -t testing libc6`?

**Comment by genshen** [comment] 2020-10-22 07:41
> I wouldn't close it, the bug is still reproducible, the workaround is not a fix.

I agree. Please reopen it if possible.

**Comment by theSekyi** [comment] 2020-10-23 18:08
I have a similar issue and the workaround doesn't fix it. This is my code and error

```
FROM debian
# RUN echo "deb http://ftp.us.debian.org/debian testing main" >> /etc/apt/sources.list
# RUN apt-get update
# RUN apt-get install -y curl -o APT::Immediate-Configure=0
RUN echo deb http://deb.debian.org/debian testing main contrib non-free >> /etc/apt/sources.list && \
    apt-get update && \
    apt-get remove -y binutils && \
    apt-get autoremove -y

RUN apt-get install -y libgdal-dev g++ --no-install-recommends && \
    pip install pipenv && \
    pip install whitenoise && \
    pip install gunicorn && \
    apt-get clean -y -o APT::Immediate-Configure=0
```
**Error**
```
E: Could not configure 'libc6:amd64'. 
E: Could not perform immediate configuration on 'libnss-nis:amd64'. Please see man 5 apt.conf under APT::Immediate-Configure for details. (2)
The command '/bin/sh -c apt-get install -y libgdal-dev g++ --no-install-recommends &&     pip install pipenv &&     pip install whitenoise &&     pip install gunicorn &&     apt-get clean -y -o APT::Immediate-Configure=0' returned a non-zero code: 100
```

**Comment by hilsenrat** [comment] 2020-10-23 18:30
> I have a similar issue and the workaround doesn't fix it. This is my code and error
> 
> 
> 
> ```
> 
> FROM debian
> 
> RUN echo deb http://deb.debian.org/debian testing main contrib non-free >> /etc/apt/sources.list && \
> 
>     apt-get update && \
> 
>     apt-get remove -y binutils && \
> 
>     apt-get autoremove -y
> 
> 
> 
> RUN apt-get install -y libgdal-dev g++ --no-install-recommends && \
> 
>     pip install pipenv && \
> 
>     pip install whitenoise && \
> 
>     pip install gunicorn && \
> 
>     apt-get clean -y -o APT::Immediate-Configure=0
> 
> ```
> 
> **Error**
> 
> ```
> 
> E: Could not configure 'libc6:amd64'. 
> 
> E: Could not perform immediate configuration on 'libnss-nis:amd64'. Please see man 5 apt.conf under APT::Immediate-Configure for details. (2)
> 
> The command '/bin/sh -c apt-get install -y libgdal-dev g++ --no-install-recommends &&     pip install pipenv &&     pip install whitenoise &&     pip install gunicorn &&     apt-get clean -y -o APT::Immediate-Configure=0' returned a non-zero code: 100
> 
> ```
> 
> 

You should imply the workaround while running `apt-get install`, and not while running `apt-get clean`.  
This should do the trick for you: 
```
RUN apt-get install -y libgdal-dev g++ -o APT::Immediate-Configure=0 --no-install-recommends && \
 
     pip install pipenv && \
 
     pip install whitenoise && \
 
     pip install gunicorn && \
 
     apt-get clean -y
 
 ```

**Comment by theSekyi** [comment] 2020-10-24 09:02
> > I have a similar issue and the workaround doesn't fix it. This is my code and error
> > ```
> > 
> > FROM debian
> > 
> > RUN echo deb http://deb.debian.org/debian testing main contrib non-free >> /etc/apt/sources.list && \
> > 
> >     apt-get update && \
> > 
> >     apt-get remove -y binutils && \
> > 
> >     apt-get autoremove -y
> > 
> > 
> > 
> > RUN apt-get install -y libgdal-dev g++ --no-install-recommends && \
> > 
> >     pip install pipenv && \
> > 
> >     pip install whitenoise && \
> > 
> >     pip install gunicorn && \
> > 
> >     apt-get clean -y -o APT::Immediate-Configure=0
> > ```
> > 
> > 
> > **Error**
> > ```
> > 
> > E: Could not configure 'libc6:amd64'. 
> > 
> > E: Could not perform immediate configuration on 'libnss-nis:amd64'. Please see man 5 apt.conf under APT::Immediate-Configure for details. (2)
> > 
> > The command '/bin/sh -c apt-get install -y libgdal-dev g++ --no-install-recommends &&     pip install pipenv &&     pip install whitenoise &&     pip install gunicorn &&     apt-get clean -y -o APT::Immediate-Configure=0' returned a non-zero code: 100
> > ```
> 
> You should imply the workaround while running `apt-get install`, and not while running `apt-get clean`.
> This should do the trick for you:
> 
> ```
> RUN apt-get install -y libgdal-dev g++ -o APT::Immediate-Configure=0 --no-install-recommends && \
>  
>      pip install pipenv && \
>  
>      pip install whitenoise && \
>  
>      pip install gunicorn && \
>  
>      apt-get clean -y
>  
> ```

That worked! Thanks

**Comment by johnmarkwayve** [comment] 2020-12-03 16:50
This is still an issue please re-open (if not I will open a mirroring issue)

**Comment by solenark** [comment] 2021-02-05 18:27
> Here's a minimal Dockerfile that reproduces this for me:
> 
> ```dockerfile
> FROM debian
> RUN echo "deb http://ftp.us.debian.org/debian testing main" >> /etc/apt/sources.list
> RUN apt-get update
> RUN apt-get install -y curl
> ```
> 
> ```shell
> docker build .
> ```
> 
> Full output
> One workaround ([xref](https://supportcenter.devexpress.com/ticket/details/t940631/could-not-configure-libc6-amd64-in-docker-build)) is to disable "immediate configuration" in the apt-get install:
> 
> ```dockerfile
> FROM debian
> RUN echo "deb http://ftp.us.debian.org/debian testing main" >> /etc/apt/sources.list
> RUN apt-get update
> RUN apt-get install -y curl -o APT::Immediate-Configure=0
> ```
> 
> Removing the `/etc/apt/sources.list` addition also works around it (though in my use case I need it in order to get more recent versions of e.g. `git`, iirc).

If you are comming here from googling something like "/lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.28 not found' or even "Docker GLIBC_2.28 not found", heres your solution.

Also, if you are using a Dotnet Core docker container, heres some example code (for the base image of the Dockerfile):

```
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim AS base
WORKDIR /app
RUN apt-get update -qq && apt-get -y install libgdiplus libc6-dev
RUN echo "deb http://ftp.us.debian.org/debian testing main" >> /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y curl
EXPOSE 80
```

**Comment by rambozzang** [comment] 2021-07-13 08:29
sudo yum intsall gcc make

**Comment by ksbhaskar** [comment] 2021-07-13 13:25
> sudo yum intsall gcc make

That should be: `sudo yum install gcc make` (there is a small typo in the command as posted)

**Comment by cpuguy83** [comment] 2021-07-13 14:22
This is not a a Docker bug it is a packaging issue with the distro.
https://bugs.launchpad.net/ubuntu-cdimage/+bug/1871268

There is nothing we can change in Docker to resolve this.
Ubuntu and Debian images on hub come from the upstream releases.
/cc @tianon

Closing because there does not appear to be anything actionable here. Please track this issue upstream.

Thanks😇

**Closed by cpuguy83** 2021-07-13 14:22 UTC
