### ISSUE TITLE
RHEL 7 installations broken where $releasever is '7Workstation'

### ISSUE THREAD

**Issue by LongerHV** [docker/for-linux#1118] opened 2020-10-01 10:38 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one
Seems to be related to issue #1111 

### Expected behavior
Running get-docker.sh, or manually adding repository allows to install docker.

### Actual behavior
yum fails to install returning following error message:
https://download.docker.com/linux/centos/7Workstation/x86_64/stable/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

### Steps to reproduce the behavior
Follow steps available on: https://docs.docker.com/engine/install/centos/

**Additional environment details:**
- VMWare Cloud Director

**Comment by thaJeztah** [comment] 2020-10-01 22:49
Looks like a duplicate of https://github.com/docker/for-linux/issues/1111, which has some workarounds. Let me close this

**Closed by thaJeztah** 2020-10-01 22:49 UTC
