### ISSUE TITLE
Error when use docker cp. open : permission denied

### ISSUE THREAD

**Issue by chopin2712** [docker/for-linux#564] opened 2019-01-18 21:44 UTC
Dear developers

I recently installed a Mediawiki app with this command

`sudo docker run -d -p 12345:80 --name andrewiki mediawiki`

That works perfectly but I loose my `LocalSettings.php` file (nessessary to change basic variables)
So I run this : 
`cd /home/gene/DBak/Andrew Bennett/`
`sudo docker cp andrewiki:/var/www/html/LocalSettings.php .`
 And there is the output : 
`open /home/gene/DBak/Andrew Bennett/LocalSettings.php: permission denied`

I search elsewhere to find other issue like this one, but I didn't found anything pertinent. So I try : 
`sudo chown 777 daemon:daemon .`
But nothing. The issue continue.

Please help me, if you find other way to have `LocalSettings.php` I will be very thanks.

Thanks in advance.

_SudoBash_

**Comment by mannharleen** [comment] 2019-03-13 01:05
same issue. anyone has any thoughts

**Comment by edward-agarwala** [comment] 2019-04-25 19:27
I also have the same problem when the user is not root and `sudo docker cp container:path/to/copy dest` also works for me.

**Comment by FranzHuebner** [comment] 2019-07-01 13:35
Same issue as @edward-agarwala and @mannharleen -> Temp. workaround for anyone stumbling upon this, is to copy the file to /tmp/ and move it from there.

**Comment by cpuguy83** [comment] 2019-07-01 14:27
Seems like a straight forward problem with permissions.
If your user doesn't have access to the directory then docker can't copy to it.

**Comment by FranzHuebner** [comment] 2019-07-01 16:00
Hey @cpuguy83 I use copy in a dockerfile for the same folder and this works flawless. Nevertheless after executing the container and pulling the result with docker cp from bash,  the error appears. Every command is done without root permissions.

**Comment by cpuguy83** [comment] 2019-07-01 16:04
The issue is not the container but the location you are copying to on the client side.

**Comment by cpuguy83** [comment] 2019-07-01 19:45
Closing since this doesn't really look like a docker issue.

**Closed by cpuguy83** 2019-07-01 19:45 UTC

**Comment by MohamadHFallah** [comment] 2019-08-21 10:27
Use sudo, ex : sudo docker cp 0e543d3f05:/home/crossTest /home

**Comment by sim31** [comment] 2020-02-12 08:25
I use sudo to execute this command and still get this error.

**Comment by rstoji** [comment] 2020-07-30 09:56
Same here. Even using sudo does not slove the problem

**Comment by kurema** [comment] 2020-10-25 19:18
Same. ``sudo`` doesn't work. I can copy to /tmp but I can't see the result.
I think it's because I am using snap version.

```
$ which docker
/snap/bin/docker
```

**Comment by DanielYWoo** [comment] 2021-03-31 02:24
this is NOT an issue of docker, this is an issue of snap. please report this problem to snap. @chopin2712

**Comment by robert-vonahi** [comment] 2022-12-16 13:19
for me it ended up in `/tmp/snap-private-tmp/snap.docker/tmp`

**Comment by tzy0002088** [comment] 2024-03-07 08:32
> for me it ended up in `/tmp/snap-private-tmp/snap.docker/tmp`

I'm the same, brother. Have you solved it on your end.

**Comment by StarsEnd33A2D17** [comment] 2024-05-14 15:52
> > for me it ended up in `/tmp/snap-private-tmp/snap.docker/tmp`
> 
> I'm the same, brother. Have you solved it on your end.

It seems to be an issue with snap. I added the current user to the docker group and restarted docker using snap (disable, then enable), and everything was fine.  (Prior to this, I had been using sudo docker)

Reference: [snapcraft.io/docker](https://snapcraft.io/docker#:~:text=By%20default%2C%20Docker%20is%20only%20accessible%20with%20root,sudo%20snap%20disable%20docker%20sudo%20snap%20enable%20docker)
``` shell
sudo snap disable docker
sudo snap enable docker
```

**Comment by satya-bodapati** [comment] 2024-09-06 14:29
> > > for me it ended up in `/tmp/snap-private-tmp/snap.docker/tmp`
> > 
> > 
> > I'm the same, brother. Have you solved it on your end.
> 
> It seems to be an issue with snap. I added the current user to the docker group and restarted docker using snap (disable, then enable), and everything was fine. (Prior to this, I had been using sudo docker)
> 
> Reference: [snapcraft.io/docker](https://snapcraft.io/docker#:~:text=By%20default%2C%20Docker%20is%20only%20accessible%20with%20root,sudo%20snap%20disable%20docker%20sudo%20snap%20enable%20docker)
> 
> ```shell
> sudo snap disable docker
> sudo snap enable docker
> ```

This worked for me. the URL steps are (ensure $USER is your username. So dont do after logging as sudo, then $USER becomes root) :

 sudo addgroup --system docker
 sudo adduser $USER docker
 newgrp docker
 sudo snap disable docker
 sudo snap enable docker

**Comment by maxm4** [comment] 2024-10-02 17:20
For me, only the following worked:
``sudo docker cp [container]:[docker_path]/output.txt - > output.txt``
And then I removed the binary gibberish that comes with redirecting stdout
There was nothing in my `/tmp/snap-private-tmp/snap.docker/tmp`

**Comment by cgarrod** [comment] 2025-07-10 13:54
I had this same problem, and the underlying issue was that the shell was set to `/usr/sbin/nologin` for the host account managing the docker container.  The implementation of docker copy apparently attempts to open a subshell on the host when it writes the files, which was failing.

(In my case, the copy would fail regardless of the file/directory permissions.)
