### ISSUE TITLE
Docker fails to obtain aws-sdk libraries on npm install cmd.

### ISSUE THREAD

**Issue by 123srikanth** [docker/for-linux#1335] opened 2021-12-21 09:33 UTC
Hi there, I have an node js application using which I'm moving the local data to my amazon s3 bucket due to space issues and now I want to dockerize the application but while building the container it throws this error 

Docker fails to obtain aws-sdk libraries on npm install cmd.

**Comment by thaJeztah** [comment] 2021-12-21 20:14
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the [Docker community Slack channel](http://dockr.ly/slack)
- the Docker Support Forums - https://forums.docker.com
- the `docker` tags on [StackOverflow](https://stackoverflow.com/questions/tagged/docker*)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2021-12-21 20:14 UTC
