### ISSUE TITLE
ubuntu image error: cannot see libraries anymore

### ISSUE THREAD

**Issue by SergiyIvanovAtGTI** [docker/for-linux#301] opened 2018-05-04 17:25 UTC
in out Dockerfile:

```Dockerfile
FROM ubuntu

RUN apt-get -y update && apt-get install -y libboost-thread1.58.0
```

fails with output:

```
Couldn't find any package by glob 'libboost-thread1.58.0'
E: Couldn't find any package by regex 'libboost-thread1.58.0'
```

Just worked yesterday.

**Output of `docker version`:**

docker version

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

docker info
```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-39-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 7.79GiB
Name: ice-vm
ID: KU2L:OPPO:RM43:AKDY:7J2K:JPRY:CKDU:W353:OAWI:ORZY:DXJ7:372X
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: sergiyivanovatgti
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
Ubuntu virtual image

**Comment by thaJeztah** [comment] 2018-05-07 17:00
This is because you're using `ubuntu:latest` as your base image; for Ubuntu images on Docker Hub, the `:latest` tag is always pointing to the current "LTS" release of Ubuntu. Up until recently, the current LTS release was Ubuntu 16.04, but this is now Ubuntu 18.04. The `libboost-thread1.58.0` appears to be no longer available for that version of Ubuntu.

You can see this by specifying which version of Ubuntu you want to use for your base image; using `ubuntu:16.04` as base image, and the build will succeed:

```Dockerfile
FROM ubuntu:16.04

RUN apt-get -y update && apt-get install -y libboost-thread1.58.0
```

produces:

```
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM ubuntu:16.04
16.04: Pulling from library/ubuntu
297061f60c36: Pull complete 
e9ccef17b516: Pull complete 
dbc33716854d: Pull complete 
8fe36b178d25: Pull complete 
686596545a94: Pull complete 
Digest: sha256:1dfb94f13f5c181756b2ed7f174825029aca902c78d0490590b1aaa203abc052
Status: Downloaded newer image for ubuntu:16.04
 ---> 0b1edfbffd27
Step 2/2 : RUN apt-get -y update && apt-get install -y libboost-thread1.58.0
 ---> Running in e458013eef98
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [107 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
Get:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Get:4 http://security.ubuntu.com/ubuntu xenial-security/universe Sources [80.4 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
Get:6 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [615 kB]
Get:7 http://archive.ubuntu.com/ubuntu xenial/universe Sources [9802 kB]
Get:8 http://security.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages [12.7 kB]
Get:9 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [436 kB]
Get:10 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [3755 B]
Get:11 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages [1558 kB]
Get:12 http://archive.ubuntu.com/ubuntu xenial/restricted amd64 Packages [14.1 kB]
Get:13 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [9827 kB]
Get:14 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages [176 kB]
Get:15 http://archive.ubuntu.com/ubuntu xenial-updates/universe Sources [255 kB]
Get:16 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [994 kB]
Get:17 http://archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages [13.1 kB]
Get:18 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [804 kB]
Get:19 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [18.8 kB]
Get:20 http://archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages [5157 B]
Get:21 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [8075 B]
Fetched 25.2 MB in 4s (5417 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libboost-system1.58.0
The following NEW packages will be installed:
  libboost-system1.58.0 libboost-thread1.58.0
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 56.2 kB of archives.
After this operation, 258 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libboost-system1.58.0 amd64 1.58.0+dfsg-5ubuntu3.1 [9146 B]
Get:2 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libboost-thread1.58.0 amd64 1.58.0+dfsg-5ubuntu3.1 [47.0 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 56.2 kB in 0s (786 kB/s)
Selecting previously unselected package libboost-system1.58.0:amd64.
(Reading database ... 4768 files and directories currently installed.)
Preparing to unpack .../libboost-system1.58.0_1.58.0+dfsg-5ubuntu3.1_amd64.deb ...
Unpacking libboost-system1.58.0:amd64 (1.58.0+dfsg-5ubuntu3.1) ...
Selecting previously unselected package libboost-thread1.58.0:amd64.
Preparing to unpack .../libboost-thread1.58.0_1.58.0+dfsg-5ubuntu3.1_amd64.deb ...
Unpacking libboost-thread1.58.0:amd64 (1.58.0+dfsg-5ubuntu3.1) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Setting up libboost-system1.58.0:amd64 (1.58.0+dfsg-5ubuntu3.1) ...
Setting up libboost-thread1.58.0:amd64 (1.58.0+dfsg-5ubuntu3.1) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Removing intermediate container e458013eef98
 ---> db767c8c7d32
Successfully built db767c8c7d32
Successfully tagged test:latest
```

But when using `ubuntu:18.04` (or `ubuntu:latest`), the build fails:

```Dockerfile
FROM ubuntu:18.04

RUN apt-get -y update && apt-get install -y libboost-thread1.58.0
```

```
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM ubuntu:18.04
18.04: Pulling from library/ubuntu
a48c500ed24e: Pull complete 
1e1de00ff7e1: Pull complete 
0330ca45a200: Pull complete 
471db38bcfbf: Pull complete 
0b4aba487617: Pull complete 
Digest: sha256:c8c275751219dadad8fa56b3ac41ca6cb22219ff117ca98fe82b42f24e1ba64e
Status: Downloaded newer image for ubuntu:18.04
 ---> 452a96d81c30
Step 2/2 : RUN apt-get -y update && apt-get install -y libboost-thread1.58.0
 ---> Running in 98f28f257fdd
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [69.9 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [65.4 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [65.5 kB]
Get:5 http://security.ubuntu.com/ubuntu bionic-security/universe Sources [1408 B]
Get:6 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [2853 B]
Get:7 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [9454 B]
Get:8 http://archive.ubuntu.com/ubuntu bionic/universe Sources [11.5 MB]
Get:9 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:13 http://archive.ubuntu.com/ubuntu bionic-updates/universe Sources [2126 B]
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [3631 B]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [9454 B]
Fetched 24.9 MB in 5s (5027 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libboost-thread1.58.0
E: Couldn't find any package by glob 'libboost-thread1.58.0'
E: Couldn't find any package by regex 'libboost-thread1.58.0'
The command '/bin/sh -c apt-get -y update && apt-get install -y libboost-thread1.58.0' returned a non-zero code: 100
```


To make sure your builds are reproducible, it is recommended to use a specific tag, instead of `:latest`, for reasons above.

I'll close this issue, because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2018-05-07 17:00 UTC
