### ISSUE TITLE
Failed to start containerd: exec: "containerd": executable file not found in $PATH

### ISSUE THREAD

**Issue by improvethings** [docker/for-linux#705] opened 2019-06-21 05:32 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior

dockerd to drop into daemon mode

### Actual behavior

$ sudo bin/dockerd
[sudo] password for improvethings: 
Failed to start containerd: exec: "containerd": executable file not found in $PATH

### Steps to reproduce the behavior

$ sudo bin/dockerd
[sudo] password for improvethings: 
Failed to start containerd: exec: "containerd": executable file not found in $PATH
which containerd
/home/improvethings/bin/containerd
$ pwd
/home/improvethings
$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/home/improvethings/bin

**Output of `docker version`:**

```
$ bin/docker version
Client: Docker Engine - Community
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:33:34 2019
 OS/Arch:           linux/amd64
 Experimental:      false
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/version: dial unix /var/run/docker.sock: connect: permission denied
```

**Output of `docker info`:**

```
$ bin/docker info
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/info: dial unix /var/run/docker.sock: connect: permission denied
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

$ uname -srm
Linux 4.19.0-1-amd64 x86_64
$ lsb_release -a
No LSB modules are available.
Distributor ID:	MX
Description:	MX 18.3 Continuum
Release:	18.3
Codename:	Continuum

**Comment by wtchhb** [comment] 2021-01-04 15:48
I have also encountered this problem

**Comment by alakesh** [comment] 2021-01-20 22:09
This does not seem like a bug in containerd. Its probably you are running as root and PATH doesn't include containerd. One option is to run sudo with -E option. But that won't work either if /etc/sudoers file has secure_path option and path to containerd binary is not listed. In such cases run it like this:

sudo PATH=$PATH:/usr/local/bin <your command>

e.g 

sudo PATH=$PATH:/usr/local/bin make integration

One more way to permanently fix it is to edit /etc/sudoers file and edit the secure_path option. if containerd is installed in /usr/local/bin/ then change it to something like this

Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin

**Comment by cpuguy83** [comment] 2021-01-21 17:41
Yes, this is because dockerd is not able to find the containerd bin, which it looks up in `$PATH` as @alakesh mentioned.

Closing since this looks like a user env error not a bug.

**Closed by cpuguy83** 2021-01-21 17:41 UTC
