### ISSUE TITLE
Need to a create file in /dev path in non-root container on startup

### ISSUE THREAD

**Issue by nelsonpraveen** [docker/for-linux#838] opened 2019-10-25 08:08 UTC
* [ ] This is a bug report
* [x] This is a feature request
* [x] I searched existing issues before opening this one

### Steps to reproduce the behavior
Hi,
I am trying to bring up a container which would have a socket file created in /dev partition. 

Now I understand that /dev directory in a container is mounted on tmpfs mount and is dynamically created. So I cannot create this socket file as part of my build. (Even if I create this in build, the directory would be removed anyways post the build).

The container I bring up is with non-root user (testrun) and also has no-new-priveleges option passed in run as shown below.

docker run \
    --rm \
	-it -d \
    --name cont_testdev_1 \
    --security-opt no-new-privileges \
    --cap-drop all \
    --user testrun:test \
    testdev

I have tried or considered following options:

1) Creating this socket file in my entrypoint script. This is not possible in my case as /dev by default has only read permission for non-root users. Also I cannot perform a sudo as no-new-priveleges is provided.
   
   Any way to create /dev with 777 permissions in the containers ?

2) Try and manually create the /dev partition with enough permissions by using --tmpfs option during run as shown below.
   
   --mount type=tmpfs,destination=/dev,tmpfs-mode=0777
   
   But this causes following failure in container init.
   
   docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:114: reopening /dev/null inside container caused \\\"Failed to open /dev/null - open /dev/null: permission denied\\\"\"": unknown.

   Not sure how to overcome this.

3) Create this socket file in host and mount it into the container during run. But I need this socket file as tmpfs mount because there would be multiple instances of the container and I dont want to create multiple socket files in the host's filesystem.

Is there any option where such custom files can be created with enough permissions (mainly in dynamically created folders like /dev) when the container comes up ?

I would be really thankful for any help or suggestions.

**Output of `docker version`:**

Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056
 Built:             Thu Apr 11 04:43:34 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:13:40 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Output of `docker info`:**

Containers: 145
 Running: 3
 Paused: 0
 Stopped: 142
Images: 587
Server Version: 18.09.5
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: false
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.5.2.el7.x86_64
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 31.22GiB
Name: emt03-eirfe3
ID: 4272:X2Z6:5JLQ:FV36:WLPT:FMKI:GICM:FOBR:QVBR:KEJ2:2LNT:ROSO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

**Additional environment details (AWS, VirtualBox, physical, etc.)**

**Comment by thaJeztah** [comment] 2019-10-29 17:42
Thanks for reporting; permissions inside a container apply the same as if you would be running on the host; if the main user doesn't have permissions on `/dev`, this won't work.


Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2019-10-29 17:42 UTC
