### ISSUE TITLE
docker-ce package is missing for Ubuntu "Disco Dingo" 19.04 x86_64

### ISSUE THREAD

**Issue by denji** [docker/for-linux#533] opened 2018-12-25 01:06 UTC
Ubuntu 19.04 (Disco Dingo) released https://lists.ubuntu.com/archives/ubuntu-announce/2019-April/000243.html

* Desktop http://cdimage.ubuntu.com/daily-live/current/
* Server http://cdimage.ubuntu.com/ubuntu-server/daily/current/

#### 18.10 (Cosmic) problem tags edge/nightly:

> https://docs.docker.com/install/linux/docker-ce/ubuntu/#set-up-the-repository
> builds from the **edge** or **test** repositories as well
> > https://download.docker.com/linux/ubuntu/dists/cosmic/pool/
> > **nightly**
> > **test**

```
$ lsb_release -rdc
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco
```

**Comment by DeeDeeG** [comment] 2019-03-17 16:29
There are now nightly build for disco: https://download.docker.com/linux/ubuntu/dists/disco/pool/
And there are stable builds for cosmic: https://download.docker.com/linux/ubuntu/dists/cosmic/pool/

I personally am using the cosmic stable builds on disco, and they are working for me.

**Comment by edno** [comment] 2019-04-23 17:45
`docker-ce` and `docker-ce-cli` packages are still missing for Disco stable builds

**Comment by seemethere** [comment] 2019-04-23 18:10
@edno Stable builds for Disco will be added with the release of Docker CE 19.03.0,

If you'd like to try out the builds you can install them through our test channel:

```
curl -fsSL get.docker.com | CHANNEL=test sh
```

**Comment by gabrielcalderon** [comment] 2019-04-23 23:20
@seemethere Thanks for the news!

**Comment by brylie** [comment] 2019-05-22 16:28
I see this issue was closed, but am experiencing it with 19.04. I have followed the official installation instructions as well as a Medium article, but I see no installation candidate:

```
apt-cache policy docker-ce
docker-ce:
  Installed: (none)
  Candidate: (none)
  Version table:
```

**Comment by brylie** [comment] 2019-05-22 17:01
I.e. this issue should probably closed once the official packages are released.

**Comment by bdecarne** [comment] 2019-05-22 17:12
I used :  
```
sudo apt install docker.io
```

**Comment by brylie** [comment] 2019-05-22 19:09
The docker.io Ubuntu package looks fairly recent, at 18.09: 
https://packages.ubuntu.com/disco/docker.io

However, the official install instructions for Docker CE say to uninstall docker.io:

https://docs.docker.com/install/linux/docker-ce/ubuntu/

Running the `curl -fsSL get.docker.com | CHANNEL=test sh` command installs Docker 19.03 for me.

**Comment by gitowiec** [comment] 2019-06-11 13:07
On Disco Dingo I did (as manual says)
> sudo add-apt-repository \
>    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
>    $(lsb_release -cs) \
>    stable"
Then
> sudo apt-get install docker-ce docker-ce-cli containerd.io

And all I got is these errors:

> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Package docker-ce is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Package 'docker-ce' has no installation candidate
> E: Unable to locate package docker-ce-cli

What to do?

**Comment by gabrielcalderon** [comment] 2019-06-11 13:11
@gitowiec As state a few comments before:

"Stable builds for Disco will be added with the release of Docker CE 19.03.0."

This release isn't out yet. Ubuntu did publish 18.09 with package "docker.io", I used that one and works fine so far. If you are looking for a long-term solution I would wait for the 19.03 Docker-CE release.

**Comment by gitowiec** [comment] 2019-06-11 13:19
I edited the entry in `/etc/apt/sources.list` and switched from 
`deb [arch=amd64] https://download.docker.com/linux/ubuntu disco stable`
to
`deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable`
and I got error:

> groupadd: cannot lock /etc/group; try again later.
> dpkg: error processing package docker-ce (--configure):
>  installed docker-ce package post-installation script subprocess returned error exit status 10
> Processing triggers for systemd (240-6ubuntu5) ...
> Processing triggers for man-db (2.8.5-2) ...
> Processing triggers for libc-bin (2.29-0ubuntu2) ...
> Errors were encountered while processing:
>  docker-ce
> E: Sub-process /usr/bin/dpkg returned an error code (1)

What should I do?

**Comment by gabrielcalderon** [comment] 2019-06-11 13:22
@gitowiec You can't install the Bionic package in a Disco Dingo release... Revert that change you just did and do this:

```
apt update && apt install docker.io
```

This will install Docker 18.09.

**Comment by gitowiec** [comment] 2019-06-11 13:25
Unfortunately I got another problem


> 
> sudo apt install docker.io
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> The following additional packages will be installed:
>   bridge-utils ubuntu-fan
> Suggested packages:
>   ifupdown debootstrap docker-doc rinse zfs-fuse | zfsutils
> The following packages will be REMOVED:
>   docker-ce-cli
> The following NEW packages will be installed:
>   bridge-utils docker.io ubuntu-fan
> 0 upgraded, 3 newly installed, 1 to remove and 40 not upgraded.
> Need to get 30.8 MB of archives.
> After this operation, 85.9 MB of additional disk space will be used.
> Do you want to continue? [Y/n] 
> Get:1 http://archive.ubuntu.com/ubuntu disco/main amd64 bridge-utils amd64 1.6-2ubuntu1 [30.5 kB]
> Get:2 http://archive.ubuntu.com/ubuntu disco/universe amd64 docker.io amd64 18.09.5-0ubuntu1 [30.7 MB]
> Get:3 http://archive.ubuntu.com/ubuntu disco/main amd64 ubuntu-fan all 0.12.12 [34.6 kB]
> Fetched 30.8 MB in 3s (8930 kB/s)      
> Preconfiguring packages ...
> (Reading database ... 200640 files and directories currently installed.)
> Removing docker-ce-cli (5:18.09.6~3-0~ubuntu-bionic) ...
> Selecting previously unselected package bridge-utils.
> (Reading database ... 200452 files and directories currently installed.)
> Preparing to unpack .../bridge-utils_1.6-2ubuntu1_amd64.deb ...
> Unpacking bridge-utils (1.6-2ubuntu1) ...
> Selecting previously unselected package docker.io.
> Preparing to unpack .../docker.io_18.09.5-0ubuntu1_amd64.deb ...
> Unpacking docker.io (18.09.5-0ubuntu1) ...
> Selecting previously unselected package ubuntu-fan.
> Preparing to unpack .../ubuntu-fan_0.12.12_all.deb ...
> Unpacking ubuntu-fan (0.12.12) ...
> Setting up docker.io (18.09.5-0ubuntu1) ...
> Installing new version of config file /etc/init.d/docker ...
> Installing new version of config file /etc/init/docker.conf ...
> Adding group `docker' (GID 132) ...
> groupadd: cannot lock /etc/group; try again later.
> addgroup: `/sbin/groupadd -g 132 docker' returned error code 10. Exiting.
> dpkg: error processing package docker.io (--configure):
>  installed docker.io package post-installation script subprocess returned error exit status 1
> Setting up bridge-utils (1.6-2ubuntu1) ...
> Setting up ubuntu-fan (0.12.12) ...
> Created symlink /etc/systemd/system/multi-user.target.wants/ubuntu-fan.service → /lib/systemd/system/ubuntu-fan.service.
> Processing triggers for man-db (2.8.5-2) ...
> Processing triggers for systemd (240-6ubuntu5) ...
> Errors were encountered while processing:
>  docker.io
> E: Sub-process /usr/bin/dpkg returned an error code (1)
>

**Comment by DeeDeeG** [comment] 2019-06-11 13:46
Sorry everyone if this is a bit off-topic.

@gitowiec This appears to be the problem:
> Adding group docker' (GID 132) ... groupadd: cannot lock /etc/group; try again later. addgroup: /sbin/groupadd -g 132 docker' returned error code 10. Exiting.

Specifically: 
> groupadd: cannot lock /etc/group

You _should_ have permission to edit that file, since you are using sudo (`sudo apt install`). Maybe you can run this to get some clues as to what is going on?: `sudo lsof +D /etc` (lsof lists open files and tells you details of why they are open. Should show you why `/etc/group` is open and in-use.)

Also, you might try simply rebooting your computer and trying again, since this may close the program tying up `/etc/group`.

There is also a stackoverflow answer suggesting to do this: `sudo mount -o remount,rw /`
source: https://superuser.com/a/820189

You can try that if none of the other things work.

**Comment by gitowiec** [comment] 2019-06-11 13:51
Thanks for fast response. I think the problem is my Ubuntu installation which is not quite full fledged installation. I made it on usb from live cd with mkusb... I think it just binds `/etc` from the "cdrom" partition which is read only... I wanted go shortcut but instead I ended with double work to do because now I have to begin from the start and make full install...

**Comment by mcandre** [comment] 2019-06-30 17:14
Please keep this issue open until the commands documented in https://docs.docker.com/install/linux/docker-ce/ubuntu/ actually work without modification.

**Comment by NineSwordsMonster** [comment] 2019-07-03 01:45
may be change to 
![image](https://user-images.githubusercontent.com/10054584/60557218-38bb9f80-9d77-11e9-919f-7ef424cb50c5.png)

and I use
```
apt install docker.io
``

**Comment by NedkoHristov** [comment] 2019-07-10 14:06
> @gitowiec You can't install the Bionic package in a Disco Dingo release... Revert that change you just did and do this:
> 
> ```
> apt update && apt install docker.io
> ```
> 
> This will install Docker 18.09.

This fixed my issues on disco. Thanks a lot!

**Comment by TomBaxter** [comment] 2019-07-12 18:15
I switched disco to cosmic and "Hellow World" ran fine. Fingers crossed.

**Comment by TomBaxter** [comment] 2019-07-22 23:07
19.03 just came out. I switched my source back to disco and got the update. Can close this now I imagine.

**Closed** 2019-07-23 01:09 UTC

**Comment by asaarnak** [comment] 2019-09-06 07:56
Soon Ubuntu 19.10 will be released, any plans to support it on nightly?
http://cdimage.ubuntu.com/daily-live/current/
https://download.docker.com/linux/ubuntu/dists/

**Comment by khairmuhammad** [comment] 2019-10-10 04:30
Hit:1 https://deb.nodesource.com/node_10.x disco InRelease
Hit:2 http://ppa.launchpad.net/ethereum/ethereum/ubuntu disco InRelease      
Get:3 https://download.docker.com/linux/ubuntu disco InRelease [44.4 kB]     
Hit:4 http://ppa.launchpad.net/plushuang-tw/uget-stable/ubuntu disco InRelease
Get:5 https://download.docker.com/linux/ubuntu xenial InRelease [74.4 kB]    
Hit:6 http://archive.ubuntu.com/ubuntu disco InRelease                       
Hit:7 http://ppa.launchpad.net/uget-team/ppa/ubuntu disco InRelease          
Get:8 https://download.docker.com/linux/ubuntu xenial/stable amd64 Packages [11.2 kB]
Ign:9 http://ppa.launchpad.net/webupd8team/atom/ubuntu disco InRelease       
Hit:10 http://archive.ubuntu.com/ubuntu disco-updates InRelease     
Err:12 http://ppa.launchpad.net/webupd8team/atom/ubuntu disco Release     
  404  Not Found [IP: 91.189.95.83 80]
Hit:13 http://archive.ubuntu.com/ubuntu disco-backports InRelease            
Hit:14 http://archive.ubuntu.com/ubuntu disco-security InRelease             
Hit:11 https://packagecloud.io/AtomEditor/atom/any any InRelease          
Reading package lists... Done
E: Repository 'https://download.docker.com/linux/ubuntu disco InRelease' changed its 'Label' value from 'Docker CE' to 'Docker EE'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
E: The repository 'http://ppa.launchpad.net/webupd8team/atom/ubuntu disco Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

I got this issue can anybody help me.... its urgent!

**Comment by alanfranz** [comment] 2019-10-10 07:31
@khairmuhammad please don't hijack unrelated threads. And just use apt.
