### ISSUE TITLE
docker update/install stuck on ubuntu 16.04

### ISSUE THREAD

**Issue by XzenTorXz** [docker/for-linux#656] opened 2019-04-29 10:38 UTC
* [x] This is a bug report

### Expected behavior

docker starts

### Actual behavior

docker doesnt start

### Steps to reproduce the behavior

I'm trying to update my docker from `17.03.2` to `18.09`. So my naiv approach was trough apt upgrade. The install script stopped after the line:

    update-alternatives: using /usr/bin/dockerd-ce to provide /usr/bin/dockerd (dockerd) in auto mode

i rebooted afte a couple of hours. The docker logs:

    systemctl status docker.service
    ● docker.service - Docker Application Container Engine
       Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
       Active: deactivating (stop-sigterm)
         Docs: https://docs.docker.com
     Main PID: 14396 (dockerd)
        Tasks: 240
       Memory: 45.0M
          CPU: 2.484s
       CGroup: /system.slice/docker.service
               └─14396 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
    
    Apr 27 15:32:27 node2 dockerd[14396]: time="2019-04-27T15:32:27.297882474+02:00" level=info msg="blockingPicker: the picked transport is not ready, loop back to repick" module=grpc
    Apr 27 15:32:27 node2 dockerd[14396]: time="2019-04-27T15:32:27.298075314+02:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc4202198b0, READY" module=grpc
    Apr 27 15:32:27 node2 dockerd[14396]: time="2019-04-27T15:32:27.298124392+02:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc42075d0b0, READY" module=grpc
    Apr 27 15:32:27 node2 dockerd[14396]: time="2019-04-27T15:32:27.316694119+02:00" level=info msg="[graphdriver] using prior storage driver: aufs"
    Apr 27 15:32:27 node2 dockerd[14396]: time="2019-04-27T15:32:27.676142571+02:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
    Apr 27 15:32:27 node2 dockerd[14396]: time="2019-04-27T15:32:27.676495158+02:00" level=warning msg="Your kernel does not support swap memory limit"
    Apr 27 15:32:27 node2 dockerd[14396]: time="2019-04-27T15:32:27.676558831+02:00" level=warning msg="Your kernel does not support cgroup rt period"
    Apr 27 15:32:27 node2 dockerd[14396]: time="2019-04-27T15:32:27.676577390+02:00" level=warning msg="Your kernel does not support cgroup rt runtime"
    Apr 27 15:32:27 node2 dockerd[14396]: time="2019-04-27T15:32:27.677162977+02:00" level=info msg="Loading containers: start."

I tried reinstalling a couple of times but it just get stuck.

When i kill some process `/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock` the install-/deinstall-process stops.

I also tried to install the old version, buth the installation also gets stuck:

[![docker stuck][1]][1]

the journalctl logs look simular:

    journalctl -u docker.service -f
    -- Logs begin at Sat 2019-04-27 11:07:56 CEST. --
    Apr 27 16:13:25 node2 systemd[1]: docker.service: Unit entered failed state.
    Apr 27 16:13:25 node2 systemd[1]: docker.service: Failed with result 'exit-code'.
    Apr 27 16:17:07 node2 systemd[1]: Starting Docker Application Container Engine...
    Apr 27 16:17:07 node2 dockerd[21868]: time="2019-04-27T16:17:07.477006764+02:00" level=info msg="libcontainerd: new containerd process, pid: 21877"
    Apr 27 16:17:08 node2 dockerd[21868]: time="2019-04-27T16:17:08.483652560+02:00" level=info msg="[graphdriver] using prior storage driver: aufs"
    Apr 27 16:17:08 node2 dockerd[21868]: time="2019-04-27T16:17:08.856918737+02:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
    Apr 27 16:17:08 node2 dockerd[21868]: time="2019-04-27T16:17:08.857136416+02:00" level=warning msg="Your kernel does not support swap memory limit"
    Apr 27 16:17:08 node2 dockerd[21868]: time="2019-04-27T16:17:08.857183671+02:00" level=warning msg="Your kernel does not support cgroup rt period"
    Apr 27 16:17:08 node2 dockerd[21868]: time="2019-04-27T16:17:08.857198127+02:00" level=warning msg="Your kernel does not support cgroup rt runtime"
    Apr 27 16:17:08 node2 dockerd[21868]: time="2019-04-27T16:17:08.857589176+02:00" level=info msg="Loading containers: start."

I tried installing docker via offical [docs][2]

  [1]: https://i.stack.imgur.com/oZqxa.png
  [2]: https://docs.docker.com/install/linux/docker-ce/ubuntu/

**Output of `docker version`:**

stuck

```

```

**Output of `docker info`:**

stuck
```

```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

OS: ubuntu 16.04.6
All the installed docker container are from kubernetes.

**Comment by XzenTorXz** [comment] 2019-04-29 13:10
if i move the `/var/lib/docker/containers` the installation is successful. Now I copied all containers and figured out that it didnt start because of a single container directory.

I'm not sure if it helps but here is the content of the container dir `/var/lib/docker/containers/39e9963f8ac97a68cc6d82e69f0c88609555d1761cb1b16d2f65cafdfe291655`, that stops docker to start. It seems like a rancher container.

`config.v2.json`
```
{
    "StreamConfig": {},
    "State": {
        "Running": false,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "RemovalInProgress": false,
        "Dead": false,
        "Pid": 0,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "0001-01-01T00:00:00Z",
        "FinishedAt": "0001-01-01T00:00:00Z",
        "Health": null
    },
    "ID": "39e9963f8ac97a68cc6d82e69f0c88609555d1761cb1b16d2f65cafdfe291655",
    "Created": "2019-04-24T12:02:07.416323348Z",
    "Managed": false,
    "Path": "entrypoint.sh",
    "Args": [],
    "Config": {
        "Hostname": "39e9963f8ac9",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": true,
        "AttachStderr": true,
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "CATTLE_HELM_VERSION=v2.10.0-rancher5",
            "CATTLE_MACHINE_VERSION=v0.15.0-rancher1-1",
            "LOGLEVEL_VERSION=v0.1",
            "TINI_VERSION=v0.18.0",
            "TELEMETRY_VERSION=v0.5.1",
            "CATTLE_UI_PATH=/usr/share/rancher/ui",
            "CATTLE_UI_VERSION=2.1.21",
            "CATTLE_CLI_VERSION=v2.0.6",
            "CATTLE_API_UI_VERSION=1.1.6",
            "AUDIT_LOG_PATH=/var/log/auditlog/rancher-api-audit.log",
            "AUDIT_LOG_MAXAGE=10",
            "AUDIT_LOG_MAXBACKUP=10",
            "AUDIT_LOG_MAXSIZE=100",
            "AUDIT_LEVEL=0",
            "CATTLE_CLI_URL_DARWIN=https://releases.rancher.com/cli2/v2.0.6/rancher-darwin-amd64-v2.0.6.tar.gz",
            "CATTLE_CLI_URL_LINUX=https://releases.rancher.com/cli2/v2.0.6/rancher-linux-amd64-v2.0.6.tar.gz",
            "CATTLE_CLI_URL_WINDOWS=https://releases.rancher.com/cli2/v2.0.6/rancher-windows-386-v2.0.6.zip",
            "CATTLE_SERVER_VERSION=v2.1.8",
            "CATTLE_AGENT_IMAGE=rancher/rancher-agent:v2.1.8",
            "CATTLE_WINDOWS_AGENT_IMAGE=rancher/rancher-agent:v2.1.8-nanoserver-1803",
            "CATTLE_SERVER_IMAGE=rancher/rancher",
            "SSL_CERT_DIR=/etc/rancher/ssl"
        ],
        "Cmd": null,
        "ArgsEscaped": true,
        "Image": "rancher/rancher:stable",
        "Volumes": {
            "/var/lib/rancher": {},
            "/var/log/auditlog": {}
        },
        "WorkingDir": "/var/lib/rancher",
        "Entrypoint": [
            "entrypoint.sh"
        ],
        "OnBuild": null,
        "Labels": {
            "org.label-schema.build-date": "2019-03-28T18:00:39Z",
            "org.label-schema.schema-version": "1.0",
            "org.label-schema.vcs-ref": "fe5d8dc66e6e36e8a56211bcf5c073b1d416c11f",
            "org.label-schema.vcs-url": "https://github.com/rancher/rancher.git"
        }
    },
    "Image": "sha256:5a4ec3cb837f8028cb0b1f56bf22f35b4e4c8904c2c7ca4365fea9857d8093ee",
    "NetworkSettings": {
        "Bridge": "",
        "SandboxID": "",
        "HairpinMode": false,
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "Networks": {
            "bridge": {
                "IPAMConfig": null,
                "Links": null,
                "Aliases": null,
                "NetworkID": "",
                "EndpointID": "",
                "Gateway": "",
                "IPAddress": "",
                "IPPrefixLen": 0,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": "",
                "DriverOpts": null,
                "IPAMOperational": false
            }
        },
        "Service": null,
        "Ports": null,
        "SandboxKey": "",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null,
        "IsAnonymousEndpoint": false,
        "HasSwarmEndpoint": false
    },
    "LogPath": "",
    "Name": "/rancher-data-2019-04-24",
    "Driver": "aufs",
    "OS": "linux",
    "MountLabel": "",
    "ProcessLabel": "",
    "RestartCount": 0,
    "HasBeenStartedBefore": false,
    "HasBeenManuallyStopped": false,
    "MountPoints": {
        "/var/lib/rancher": {
            "Source": "",
            "Destination": "/var/lib/rancher",
            "RW": true,
            "Name": "d77f772848ba476939d08936e9bc3d48795e64182cba954a6aebac1401e20a31",
            "Driver": "local",
            "Type": "volume",
            "Spec": {},
            "SkipMountpointCreation": false
        },
        "/var/log/auditlog": {
            "Source": "",
            "Destination": "/var/log/auditlog",
            "RW": true,
            "Name": "16e339e2ca382577bf68e14c0896e04ff875c384d608d948e8324e9ce818727d",
            "Driver": "local",
            "Type": "volume",
            "Spec": {},
            "SkipMountpointCreation": false
        }
    },
    "SecretReferences": null,
    "ConfigReferences": null,
    "AppArmorProfile": "",
    "HostnamePath": "",
    "HostsPath": "",
    "ShmPath": "",
    "ResolvConfPath": "",
    "SeccompProfile": "",
    "NoNewPrivileges": false
}
```

`hostconfig.json`

```
{
    "Binds": null,
    "ContainerIDFile": "",
    "LogConfig": {
        "Type": "json-file",
        "Config": {}
    },
    "NetworkMode": "default",
    "PortBindings": {},
    "RestartPolicy": {
        "Name": "no",
        "MaximumRetryCount": 0
    },
    "AutoRemove": false,
    "VolumeDriver": "",
    "VolumesFrom": [
        "rancher"
    ],
    "CapAdd": null,
    "CapDrop": null,
    "Dns": [],
    "DnsOptions": [],
    "DnsSearch": [],
    "ExtraHosts": null,
    "GroupAdd": null,
    "IpcMode": "",
    "Cgroup": "",
    "Links": [],
    "OomScoreAdj": 0,
    "PidMode": "",
    "Privileged": false,
    "PublishAllPorts": false,
    "ReadonlyRootfs": false,
    "SecurityOpt": null,
    "UTSMode": "",
    "UsernsMode": "",
    "ShmSize": 67108864,
    "Runtime": "runc",
    "ConsoleSize": [
        0,
        0
    ],
    "Isolation": "",
    "CpuShares": 0,
    "Memory": 0,
    "NanoCpus": 0,
    "CgroupParent": "",
    "BlkioWeight": 0,
    "BlkioWeightDevice": null,
    "BlkioDeviceReadBps": null,
    "BlkioDeviceWriteBps": null,
    "BlkioDeviceReadIOps": null,
    "BlkioDeviceWriteIOps": null,
    "CpuPeriod": 0,
    "CpuQuota": 0,
    "CpuRealtimePeriod": 0,
    "CpuRealtimeRuntime": 0,
    "CpusetCpus": "",
    "CpusetMems": "",
    "Devices": [],
    "DeviceCgroupRules": null,
    "DiskQuota": 0,
    "KernelMemory": 0,
    "MemoryReservation": 0,
    "MemorySwap": 0,
    "MemorySwappiness": -1,
    "OomKillDisable": false,
    "PidsLimit": 0,
    "Ulimits": null,
    "CpuCount": 0,
    "CpuPercent": 0,
    "IOMaximumIOps": 0,
    "IOMaximumBandwidth": 0,
    "MaskedPaths": null,
    "ReadonlyPaths": null
}
```

**Comment by arykalin** [comment] 2019-05-24 15:40
Have same problem

**Comment by shaozi** [comment] 2019-09-06 13:48
Same problem. What is the solution?

**Comment by BoJIbFbI4** [comment] 2020-05-11 17:47
same problem on 20.04, stuck at 33%

**Comment by XzenTorXz** [comment] 2020-05-29 08:14
in my case there was a problem with multiple container using the same container using the "VolumesFrom"-config. A current workaround would be to manual move the containers from `/var/lib/docker/containers` and figure out which container causing trouble.

**Comment by thaJeztah** [comment] 2020-06-11 08:23
Looking at the comments above, I think there's different causes/situations here, and I don't see anything actionable at this moment.

> I'm trying to update my docker from 17.03.2 to 18.09. 

The overall recommendation is to not skip major releases; we test upgrades between major releases (e.g. "stable" 17.03 to 17.06), but skipping many releases can potentially cause problems (some releases in the past required a migration step), so it's better to do updates granularly. Also, if this is a production setup, always test your upgrade scenarios in a staging/test environment first (and make sure to have a backup plan).


> Have same problem
> Same problem on two of my 4 Ubuntu 18.04 nodes. What is the solution?
> same problem on 20.04, stuck at 33%

These don't provide details, so could have any reason (perhaps a networking issue, firewall, vpn, ??)

> in my case there was a problem with multiple container using the same container using the "VolumesFrom"-config. A current workaround would be to manual move the containers from /var/lib/docker/containers and figure out which container causing trouble.

That's interesting. It's _possible_ there's some kind of race-condition ("dependent containers" being recreated before the "original" container? "nameless" / "ephemeral" volumes being used?). If you would have steps to reproduce that situation, feel free to open a new ticket (probably best in the https://github.com/moby/moby/issues issue tracker) that would be something that could be looked into if it's reproducible.


I'm closing this ticket because of the above

**Closed by thaJeztah** 2020-06-11 08:23 UTC
