### ISSUE TITLE
docker multistage cache invalidation bug

### ISSUE THREAD

**Issue by RodolpheGohard** [docker/for-linux#273] opened 2018-04-05 10:14 UTC
* [x] This is a bug report

###  behavior
Hi, I have a two-stage dockerfile like this:

```Dockerfile 
    FROM dtr.acme/orga/condat:latest as artifactoryStage
    
    # Create a directory where our app will be placed
    RUN mkdir -p /usr/src/srf-server
    WORKDIR /usr/src/srf-server
    
    # Copy stuff
    COPY srf /usr/src/srf-server/srf
    COPY setup.py /usr/src/srf-server/setup.py
    COPY VERSION /usr/src/srf-server/VERSION
    
    RUN python setup.py bdist_wheel
    RUN twine upload dist/*.whl --cert /etc/cacerts.pem --repository local
    
    
    FROM dtr.acme/orga/miniconda:3-4.3.31 as runStage
    
    ENV PORT=5000
    
    COPY --from=0 /usr/src/srf-server/VERSION /usr/src/srf-server/VERSION
    # Install dependecies
    RUN yes | pip install srf==`cat /usr/src/srf-server/VERSION`
    
    # Expose the port the app runs in
    EXPOSE 5000
    
    RUN mkdir /home/user
    
    # Serve the app
    CMD ["python", "-m", "srf.app"]
 ```
 
I have made some edits on my source code, which should impacts the new build starting the instruction `COPY srf /usr/src/srf-server/srf` and tried to build a new image.
 
The problem is Docker incorrectly invalidate the cache from the copy instruction. The problem is that is doesn't in the second stage, especially this line : `COPY --from=0 /usr/src/srf-server/VERSION /usr/src/srf-server/VERSION` which should not be cached since the file is copied from stage 1 which has been invalidated also.
 
Below is the edited build log:
 
    + docker build -t dtr.acme/orga/srf-server:1.0.1-docker -f Dockerfile .
    Sending build context to Docker daemon 52.74 kB
    
    dockernode01: Step 1/19 : FROM dtr.acme/orga/condat:latest as artifactoryStage
    dockernode01:  ---> 49c12b315f5c
    dockernode01: Step 2/19 : RUN mkdir -p /usr/src/srf-server
    dockernode01:  ---> Using cache
    dockernode01:  ---> d93fb1e8225b
    dockernode01: Step 3/19 : WORKDIR /usr/src/srf-server
    dockernode01:  ---> Using cache
    dockernode01:  ---> caa4b11cec4b
    dockernode01: Step 4/19 : COPY srf /usr/src/srf-server/srf
    dockernode01:  ---> 4201c9fb914a
    dockernode01: Removing intermediate container b4300d3d5ed0
    dockernode01: Step 5/19 : COPY setup.py /usr/src/srf-server/setup.py
    dockernode01:  ---> eef664c795f5
    dockernode01: Removing intermediate container 4eced7b9710b
    ...
    dockernode01: Step 8/19 : COPY VERSION /usr/src/srf-server/VERSION
    dockernode01:  ---> 0ef2576d027f
    dockernode01: Removing intermediate container ec6c34e50c42
    ...
    dockernode01: Step 10/19 : RUN python setup.py bdist_wheel
    dockernode01:  ---> Running in ce1e90bda17f
    dockernode01: running bdist_wheel
    dockernode01: running build
    running build_py
    ...
    100%|##########| 13.8k/13.8k [00:00<00:00, 30.6kB/s]dockernode01: 
    dockernode01:  ---> ac535de9421e
    dockernode01: Removing intermediate container 89c4d26059d3
    
    
    dockernode01: Step 12/19 : FROM dtr.acme/orga/miniconda:3-4.3.31 as runStage
    dockernode01:  ---> 140e32ed5b85
    dockernode01: Step 13/19 : ENV PORT 5000
    dockernode01:  ---> Using cache
    dockernode01:  ---> 2845b5000a1e
    dockernode01: Step 14/19 : COPY --from=0 /usr/src/srf-server/VERSION /usr/src/srf-server/VERSION
    dockernode01:  ---> Using cache
 
    !!!!!!!!! Docker should really not have use cache here above !!!!!!
 
    dockernode01:  ---> 4281eb62b06c
    ...
    dockernode01: Step 19/19 : CMD python -m srf.app
    dockernode01:  ---> Using cache
    dockernode01:  ---> 8271c43bc71c
    dockernode01: Successfully built 8271c43bc71c
 
 
Why Docker uses cache in the second stage and not the first ?

### Steps to reproduce the behavior

**Output of `docker version`:**

```
Client:
 Version: 1.13.1
 API version: 1.26
 OS/Arch: linux/amd64
```

**Output of `docker info`:**

```
Server version: ucp/2.2.4
linux/amd64
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
Docker UCP 17.06

I am in a corporate environment with restrictives IT policies on outside, so I had to change some détails and can't provide samples/images to demonstrate and play with.

**Comment by thaJeztah** [comment] 2018-06-12 04:18
ping @tonistiigi

**Comment by Bidthedog** [comment] 2018-07-20 10:07
I'm getting this exact problem. I develop on Docker for Windows, but deploy to Docker for Linux. I put a SO post together with all the details:

https://stackoverflow.com/questions/51439321/docker-cache-invalidation

**Comment by aesyondu** [comment] 2021-02-16 10:56
Hi, I have the same issue, have you guys found any workaround?

I'm using macOS Catalina@10.15.7
Docker version 20.10.2, build 2291f61
docker-compose version 1.27.4, build 40524192

The thing is I'm not sure if this is a bug. If cache was invalidated on line 8, then everything below it should immediately be invalidated as well. It WOULD be nice however, if there was a smarter handling of builder images, where cache is not invalidated until the `COPY --from` instruction. Not sure what the implication of that is, however.

**Comment by aesyondu** [comment] 2021-02-16 11:03
Nvm the cache works fine as I described. Not sure why I thought it didn't. I must be tired.

**Comment by thaJeztah** [comment] 2021-02-16 13:09
Looking at the conversation above, I don't think there's a bug here, so let me close this ticket.

**Closed by thaJeztah** 2021-02-16 13:09 UTC

**Comment by mieubrisse** [comment] 2021-02-20 21:42
@thaJeztah  I don't think this should be closed, as I'm getting the same thing. My Dockerfile:
```
FROM ekidd/rust-musl-builder:1.50.0 AS builder
WORKDIR /home/rust

# Rust doesn't yet have a way to cache build dependencies as Docker layers, so we use this hack so 
# that building doesn't take 5 minutes every time
# The 'chown' is necessary due to https://github.com/emk/rust-musl-builder/issues/26
COPY --chown=rust:rust Cargo.toml ./
COPY --chown=rust:rust Cargo.lock ./
COPY --chown=rust:rust lib/Cargo.toml lib/
COPY --chown=rust:rust lib/dummy_lib_for_build_cache.rs lib/src/lib.rs
COPY --chown=rust:rust testsuite/Cargo.toml testsuite/
COPY --chown=rust:rust testsuite/dummy_main_for_build_cache.rs testsuite/src/main.rs
RUN cargo build --release

# Copy & build real lib code first, so Docker can do caching
COPY --chown=rust:rust lib lib
RUN cargo test --release --lib
RUN cargo build --release --lib

# Next copy the example testsuite code, so that if we make changes there we don't need to rebuild the lib
COPY --chown=rust:rust testsuite testsuite
RUN cargo test --release --bin testsuite
RUN cargo build --release --bin testsuite

# ============= Execution Stage ================
FROM alpine:3.12 AS execution

# Copy the code into the container
COPY --from=builder /home/rust/target/x86_64-unknown-linux-musl/release/testsuite ./

# TODO Switch to exec command form, wrapping arguments with double-quote
CMD RUST_BACKTRACE=1 ./testsuite \
    --custom-params-json="${CUSTOM_PARAMS_JSON}" \
    --kurtosis-api-socket="${KURTOSIS_API_SOCKET}" \
    --log-level="${LOG_LEVEL}"
```

and the output of a Docker build after I change Cargo.toml:

```
Sending build context to Docker daemon  124.9kB
Step 1/13 : FROM ekidd/rust-musl-builder:1.50.0 AS builder
 ---> bb5784ce5f63
Step 2/13 : WORKDIR /home/rust
 ---> Using cache
 ---> 21a5237453d9
Step 3/13 : COPY --chown=rust:rust Cargo.toml ./
 ---> Using cache
 ---> cc9180669e70
Step 4/13 : COPY --chown=rust:rust Cargo.lock ./
 ---> Using cache
 ---> 197c83040957
Step 5/13 : COPY --chown=rust:rust testsuite/Cargo.toml testsuite/
 ---> e5127cb28eaf
Step 6/13 : COPY --chown=rust:rust testsuite/dummy_main_for_build_cache.rs testsuite/src/main.rs
 ---> 51ad244787c5
Step 7/13 : RUN cargo build --release
 ---> Running in c5f67d4536e7
    Updating crates.io index
.....bunch of Rust compilation stuff.....
Removing intermediate container c5f67d4536e7
 ---> 946faf5f4b38
Step 8/13 : COPY --chown=rust:rust testsuite testsuite
 ---> c74c560932ae
Step 9/13 : RUN cargo test --release --bin testsuite
 ---> Running in 7c2856da744a
   Compiling kurtosis-rust-example v1.10.3 (/home/rust/testsuite)
....more Rust compilation stuff.....
Removing intermediate container 7c2856da744a
 ---> 20b153b11bfa
Step 10/13 : RUN cargo build --release --bin testsuite
 ---> Running in 924e159a70e2
    Finished release [optimized] target(s) in 0.16s
Removing intermediate container 924e159a70e2
 ---> 7e5e11e1fb14
Step 11/13 : FROM alpine:3.12 AS execution
 ---> 389fef711851
Step 12/13 : COPY --from=builder /home/rust/target/x86_64-unknown-linux-musl/release/testsuite ./
 ---> Using cache
 ---> 30836d3efa9a
Step 13/13 : CMD RUST_BACKTRACE=1 ./testsuite     --custom-params-json="${CUSTOM_PARAMS_JSON}"     --kurtosis-api-socket="${KURTOSIS_API_SOCKET}"     --log-level="${LOG_LEVEL}"
 ---> Using cache
 ---> 350db1d50724
Successfully built 350db1d50724
Successfully tagged solana-testsuite:master
```
The incorrect step is:
```
Step 12/13 : COPY --from=builder /home/rust/target/x86_64-unknown-linux-musl/release/testsuite ./
 ---> Using cache
 ---> 30836d3efa9a
 ```
 This shouldn't be cached, as this binary was rebuilt in the builder. No matter how many times I repeated the Docker build, the same thing happened. The output of this build is a Docker image that exits with 0 error code, but doesn't actually do anything.

If I modify the source code in any way, the cache gets invalidated and things compile correctly as expected until I modify the Cargo.toml again, at which point the `builder` stage needs to run again and things get broken.

**Comment by thaJeztah** [comment] 2021-02-22 10:22
@mieubrisse does the problem reproduce if you enable BuildKit? (`export DOCKER_BUILDKIT=1` before running `docker build`)?

**Comment by mieubrisse** [comment] 2021-02-24 19:18
Hey @thaJeztah , I just tried with `DOCKER_BUILDKIT=1 and thought the output looks significantly different (indicating that it did indeed pick up the buildkit flag), the same problem persists.

```
[+] Building 200.9s (18/18) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                       0.1s
 => => transferring dockerfile: 1.50kB                                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                                          0.1s
 => => transferring context: 140B                                                                                                                                          0.0s
 => [internal] load metadata for docker.io/ekidd/rust-musl-builder:1.50.0                                                                                                  0.0s
 => [internal] load metadata for docker.io/library/alpine:3.12                                                                                                             0.0s
 => [execution 1/2] FROM docker.io/library/alpine:3.12                                                                                                                     0.0s
 => => resolve docker.io/library/alpine:3.12                                                                                                                               0.0s
 => [builder  1/10] FROM docker.io/ekidd/rust-musl-builder:1.50.0                                                                                                          0.3s
 => => resolve docker.io/ekidd/rust-musl-builder:1.50.0                                                                                                                    0.0s
 => [internal] load build context                                                                                                                                          0.1s
 => => transferring context: 100.94kB                                                                                                                                      0.0s
 => [builder  2/10] WORKDIR /home/rust                                                                                                                                     0.1s
 => [builder  3/10] COPY --chown=rust:rust Cargo.toml ./                                                                                                                   0.1s
 => [builder  4/10] COPY --chown=rust:rust Cargo.lock ./                                                                                                                   0.1s
 => [builder  5/10] COPY --chown=rust:rust testsuite/Cargo.toml testsuite/                                                                                                 0.1s
 => [builder  6/10] COPY --chown=rust:rust testsuite/dummy_main_for_build_cache.rs testsuite/src/main.rs                                                                   0.1s
 => [builder  7/10] RUN cargo build --release                                                                                                                            197.0s
 => [builder  8/10] COPY --chown=rust:rust testsuite testsuite                                                                                                             0.1s
 => [builder  9/10] RUN cargo test --release --bin testsuite                                                                                                               2.1s
 => [builder 10/10] RUN cargo build --release --bin testsuite                                                                                                              0.6s
 => [execution 2/2] COPY --from=builder /home/rust/target/x86_64-unknown-linux-musl/release/testsuite ./                                                                   0.1s
 => exporting to image                                                                                                                                                     0.1s
 => => exporting layers                                                                                                                                                    0.0s
 => => writing image sha256:2ff79b23345c11d6e8b082bfef1ccce9bc0c1a3f09031153cd088c89b992244d                                                                               0.0s
 => => naming to docker.io/library/solana-testsuite:mieubrisse_localnet-sanit
 ```
Like before, making any modification to the sourcecode at all (even adding a comment) kicks Docker back into behaving-as-it-should mode.

**Comment by thaJeztah** [comment] 2021-02-25 12:56
Thanks for testing with BuildKIt; yes the output with BuildKIt enabled will be significantly different 😅. When enabled, the default output (if a terminal is attached) is as you showed in your example (that output is mostly targeting "interactive" sessions, and shows (e.g.) progress or `RUN` stapes _while they're running_, but "collapses" them after they completed successfully, so that your terminal session isn't polluted with information that isn't useful (in most cases) after the build completed.
If you want more "detailed" logs (and more structured to allow processing the logs), you can use `--progress=plain`, which can be quite verbose, but shows all output that's happening during the build. The default is `--progress=plain`, which automatically switches between `--progress=tty` (if a TTY is attached) and `--progress=plain` (without a TTY attached, e.g. in a non-interactive session running in CI).

If possible in your environment, I would _highly_ recommend using BuildKit for your builds (we haven't made it the default yet, but are planning to), as it can bring significant improvements to your build-time (executing build stages in parallel, among others).

### Back to your issue. Some thoughts;


- if the last step is using the cache (`Using cache` in the "classic builder" output, or `CACHED ....` with BuildKit), it means no new image was generated.
- You mention "The output of this build is a Docker image that exits with 0 error code, but doesn't actually do anything.". Can you ellaborate a bit on this? Because if the final image was "cached", it means no image was built, and thus it should be exactly the same as the image as the "first" build (if the first built image "worked", it should still work)
- You mention that the problem happens "after I change testsuite/Cargo.toml".

I'm not a Rust developer, and not familiar with its behavior when re-compiling, but reading [Cargo.toml vs Cargo.lock](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html), it mentions that `cargo update` must be run _after_ updating `Cargo.toml` (to regenerate `Cargo.lock`).
Did the new build actually produce a new binary (with a different checksum)?

Further reading [in the Rust FAQs](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries);

> The purpose of a Cargo.lock lockfile is to describe the state of the world at the time of a successful build. **Cargo uses the lockfile to provide deterministic builds on different times and different systems**, by ensuring that the exact same dependencies and versions are used as when the Cargo.lock file was originally generated.

Which makes me think what you're hitting is actually a feature of Rust / Cargo; providing _reproducible builds_ (further Googling led me to [Testing out reproducible builds](https://users.rust-lang.org/t/testing-out-reproducible-builds/9758), which describes this feature).

So what I think happens, is:

1. You edit `Cargo.toml`
2. Docker / BuildKit detects changes in the `COPY Cargo.toml` step, which invalidates the _Docker_ build-cache for steps after that
3. The `Cargo.lock` file is copied from the host to the image (`COPY ... Cargo.lock`), however if it was not modified, will have the same content as the first build
4. The Dockerfile runs the Rust / Cargo "compile" steps again (because the Docker build cache for those steps were invalidated)
5. However:
    - `cargo update` wasn't run, and thus
    - `Cargo.lock` was not modified, and
    - no code-changes were made in the sourcecode, and
    - Now, because of the "reproducible builds" feature of Cargo (which makes sure to ignore file-changes that don't affect compilation, and ignores metadata, such as timestamps on files), even though the binary was re-compiled, it produced the _exact_ same binary (same checksum, and probably same metadata / timestamp of the file)
6. Docker / BuildKit detects that no changes were found in the files that are copied to the final stage (`COPY --from=builder /home/rust/target/`) (there may be changes in other files, but does are not copied, so are not looked at)
7. Because no changes were found, the `COPY --from=builder` can use the Docker/BuildKit build-cache, and no new image is created.


In the case where you _did_ make changes to the source code, step `5.` produces a new binary with a new checksum (and different metadata). In that case, the Build-cache is invalidated for steps 6. and 7., and a new image is created.

**Comment by mieubrisse** [comment] 2021-02-26 02:01
Thanks for such a detailed response @thaJeztah ; I really appreciate it!  I've switched to `--progress=plain` to get more detailed output.

Re. the image that doesn't do anything - this is what I get in Docker desktop when I run the image produced:

<img width="1063" alt="Screen Shot 2021-02-25 at 8 35 06 PM" src="https://user-images.githubusercontent.com/1142185/109242383-0448f280-77a9-11eb-9ccc-84342eb12f54.png">

It exits immediately, with a success code, and prints no logs no matter what I do (even if the first line of `main.rs` is `println!(...)`).

Re. the hypothesis about Rust builds - I think this is a good hypothesis, but I don't think Rust reproducible builds are at the heart of it; AFAIK `cargo build` is a superset of the `cargo update` step (I'm also a very new Rust developer though). Just to verify, I added an extra step to get the MD5 of the binary that's being copied from the builder -> execution stage. Here's the results:

1. "Stuck" build (produces that weird image that exits with 0 immediately with no logs): binary has md5 of c5555d6fa72cd5bd84e40ca1892abfd0 in Step #17:
```
Building 'solana-testsuite' Docker image...
#1 [internal] load build definition from Dockerfile
#1 sha256:6ff3df86e9140dfecb825c239c20ba800f891badd0ec39b7cf154cfc9c46aff9
#1 transferring dockerfile: 1.57kB done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:197057808bdfd366be9a22b3286d8b9b9e752d2c1390cbf9849da70baf851244
#2 transferring context: 34B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/alpine:3.12
#3 sha256:dcbe6445faecb6a0adf28cc54a74893ed6f37ff445088ba92e20e9178ed92ea3
#3 DONE 0.0s

#4 [internal] load metadata for docker.io/ekidd/rust-musl-builder:1.50.0
#4 sha256:8cdb6d40eb50c8198a6c97fc38b7031f6bbda2f214c2469525c2e6a17853588b
#4 DONE 0.0s

#6 [builder  1/11] FROM docker.io/ekidd/rust-musl-builder:1.50.0
#6 sha256:f2f7fa3e5c15f2fde11baf8f28d28999b3cbb1c777d844ecdf147cdcde2eb8b9
#6 DONE 0.0s

#5 [execution 1/2] FROM docker.io/library/alpine:3.12
#5 sha256:bc0eb6cbe74f6c349104d22f689b973972c20362f3acba87a270406f51c8478a
#5 DONE 0.0s

#8 [internal] load build context
#8 sha256:de94348fa0d9314c0443b394d14905f559ad0f0e2f6edee120be59947f8c4d0e
#8 transferring context: 2.04kB done
#8 DONE 0.0s

#11 [builder  5/11] COPY --chown=rust:rust testsuite/Cargo.toml testsuite/
#11 sha256:53adfab18377b14babf4b5a040b13c3244050f70fbfc40a49532b74c84882c9a
#11 CACHED

#15 [builder  9/11] RUN cargo test --release --bin testsuite
#15 sha256:43190b81cbb946209b22ad473bec8d37c6f99e3fbb3499700dd38e67f1157729
#15 CACHED

#10 [builder  4/11] COPY --chown=rust:rust Cargo.lock ./
#10 sha256:108f3b10b04ed3b2d909cc4ccae0ba75e50e3aca4fa06ac6a7e952bf9bc804e3
#10 CACHED

#7 [builder  2/11] WORKDIR /home/rust
#7 sha256:f4bfad37f17ce03743e8d13a53aab9c85efbd64d30685aeb35f4ef4def1ee91a
#7 CACHED

#14 [builder  8/11] COPY --chown=rust:rust testsuite testsuite
#14 sha256:f1de854b67d5eb821ea4e66729295ff7d05aaa48a9d4ae0d9534116224edec6e
#14 CACHED

#13 [builder  7/11] RUN cargo build --release
#13 sha256:c56f572024dc70d760baa40692553f7557eab43c75d803f58a96f6f67e212ac6
#13 CACHED

#9 [builder  3/11] COPY --chown=rust:rust Cargo.toml ./
#9 sha256:cd7f1c68ac6d8e83fbfc7ed368281094b9ad2f84904697b5576838a5fb181d14
#9 CACHED

#12 [builder  6/11] COPY --chown=rust:rust testsuite/dummy_main_for_build_cache.rs testsuite/src/main.rs
#12 sha256:cec40c929e9dd3d7c304e04e11dce22de0a3b5731143f8c83ca4c20000a86c14
#12 CACHED

#16 [builder 10/11] RUN cargo build --release --bin testsuite
#16 sha256:70bcaf55d423d72af1fff6ae3eec77e6c3b8bb10f84d76219e5045503570e181
#16 CACHED

#17 [builder 11/11] RUN md5sum /home/rust/target/x86_64-unknown-linux-musl/release/testsuite
#17 sha256:8d82fc67cca9c855afd696df26472df4fb9dcaddbe31e9c91a60412d578e75a9
#17 0.341 c5555d6fa72cd5bd84e40ca1892abfd0  /home/rust/target/x86_64-unknown-linux-musl/release/testsuite
#17 DONE 0.4s

#18 [execution 2/2] COPY --from=builder /home/rust/target/x86_64-unknown-linux-musl/release/testsuite ./
#18 sha256:76e443ddd226443836fae87bc10d9fcfd96336afc696f86e5d62d0b2a5b3f322
#18 CACHED     <---- THIS IS WHAT'S CAUSING THE ERROR

#19 exporting to image
#19 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#19 exporting layers done
#19 writing image sha256:9e8ed6cafa603055342989fb321c0bcd9b6e526c873425520352676aa6fc8853 done
#19 naming to docker.io/library/solana-testsuite:mieubrisse_localnet-sanity done
#19 DONE 0.0s
```

2. I unstick the build by adding the comment `// TODO DEBUGGING` to the `main.rs`: binary gets a new md5 of b6d8e8d0dad23cc0da63990e076aebd8 in Step #17:
```
Building 'solana-testsuite' Docker image...
#1 [internal] load build definition from Dockerfile
#1 sha256:fd102c56a66b7e5a9f80241a6731961356a4b1542d186240e40a649dc1707ac6
#1 transferring dockerfile: 37B 0.0s done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:9b89ffc5009012111fc8bd5b9da55f72268e38214d938b22cfab24709336d378
#2 transferring context: 34B done
#2 DONE 0.0s

#4 [internal] load metadata for docker.io/ekidd/rust-musl-builder:1.50.0
#4 sha256:8cdb6d40eb50c8198a6c97fc38b7031f6bbda2f214c2469525c2e6a17853588b
#4 DONE 0.0s

#3 [internal] load metadata for docker.io/library/alpine:3.12
#3 sha256:dcbe6445faecb6a0adf28cc54a74893ed6f37ff445088ba92e20e9178ed92ea3
#3 DONE 0.0s

#5 [execution 1/2] FROM docker.io/library/alpine:3.12
#5 sha256:bc0eb6cbe74f6c349104d22f689b973972c20362f3acba87a270406f51c8478a
#5 DONE 0.0s

#6 [builder  1/11] FROM docker.io/ekidd/rust-musl-builder:1.50.0
#6 sha256:f2f7fa3e5c15f2fde11baf8f28d28999b3cbb1c777d844ecdf147cdcde2eb8b9
#6 DONE 0.0s

#8 [internal] load build context
#8 sha256:8a10fb97fface328b243db05e3252012cd88cfaec8908844ccfb45ccde981ac1
#8 transferring context: 4.55kB 0.0s done
#8 DONE 0.0s

#7 [builder  2/11] WORKDIR /home/rust
#7 sha256:f4bfad37f17ce03743e8d13a53aab9c85efbd64d30685aeb35f4ef4def1ee91a
#7 CACHED

#9 [builder  3/11] COPY --chown=rust:rust Cargo.toml ./
#9 sha256:c60e0acdd1e51d886becb5cefcd79e1603b86eb647c1097620172fa176102eaf
#9 CACHED

#11 [builder  5/11] COPY --chown=rust:rust testsuite/Cargo.toml testsuite/
#11 sha256:ab17ed79a90714ede2d8a316c9ab35c1eacce344aa951fba6652f203d0c1d2f1
#11 CACHED

#12 [builder  6/11] COPY --chown=rust:rust testsuite/dummy_main_for_build_cache.rs testsuite/src/main.rs
#12 sha256:a412e7c84b101d3a488baae822e6d2dbf89c22a95edbb42ee99c838ad21a6ec2
#12 CACHED

#10 [builder  4/11] COPY --chown=rust:rust Cargo.lock ./
#10 sha256:dde42af3857c76aa47303d0fc1e2b8afd2d382069f600da1cd66f9c7943be5f8
#10 CACHED

#13 [builder  7/11] RUN cargo build --release
#13 sha256:4a83544ca6d2176a877513017b2d210e2d9ec53db2975dc3e5e373798d65f2b6
#13 CACHED

#14 [builder  8/11] COPY --chown=rust:rust testsuite testsuite
#14 sha256:d2868cb2fd35cd3661813acccf855062936641718fd6b4d2e3fbed3a5db2a5d8
#14 DONE 0.1s

#15 [builder  9/11] RUN cargo test --release --bin testsuite
#15 sha256:bd78f9e916a3a04fb2270cd00d903efa77f1342f4a560a0352c49807094b013c
#15 0.630    Compiling kurtosis-rust-example v1.10.5 (/home/rust/testsuite)
..... bunch of Rust compile output....
#15 DONE 1.6s

#16 [builder 10/11] RUN cargo build --release --bin testsuite
#16 sha256:5a064e19d07666102086f30714b7ccb543aada8468673063dd9716ccd5cbc5f7
#16 0.595    Compiling kurtosis-rust-example v1.10.5 (/home/rust/testsuite)
..... bunch of Rust compile....
#16 DONE 14.8s

#17 [builder 11/11] RUN md5sum /home/rust/target/x86_64-unknown-linux-musl/release/testsuite
#17 sha256:dc4bc59a0d4fc0f61dc45750fdbac2c7d9067d8d2c2722c412ef3669da15e180
#17 0.513 b6d8e8d0dad23cc0da63990e076aebd8  /home/rust/target/x86_64-unknown-linux-musl/release/testsuite
#17 DONE 0.6s

#5 [execution 1/2] FROM docker.io/library/alpine:3.12
#5 sha256:bc0eb6cbe74f6c349104d22f689b973972c20362f3acba87a270406f51c8478a
#5 CACHED

#18 [execution 2/2] COPY --from=builder /home/rust/target/x86_64-unknown-linux-musl/release/testsuite ./
#18 sha256:292e334b40c922640311edaa07f46213f3c946ef671101f18699aec4c2600f84
#18 DONE 0.1s        <---- NO LONGER CACHED, WHICH MAKES THINGS WORK

#19 exporting to image
#19 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
    1 [package]
#19 exporting layers 0.1s done
#19 writing image sha256:6e6547b8f1c7fdb8d5d6e3c9aae9938bd310d67f7603f0cff22d4e66244af97d
#19 writing image sha256:6e6547b8f1c7fdb8d5d6e3c9aae9938bd310d67f7603f0cff22d4e66244af97d done
#19 naming to docker.io/library/solana-testsuite:mieubrisse_localnet-sanity done
#19 DONE 0.1s
```

3. I modify the Cargo.toml to trigger the stuck state again: binary gets yet another new md5 of 6e8664ccc75dd49597ae2af76c2620a4 , but caching is still happening (causing the stuck state):
```
Building 'solana-testsuite' Docker image...
#1 [internal] load build definition from Dockerfile
#1 sha256:1e1070f90a85de034c64f2ba5009f183583a0fee274ba41719c71e8d820b17f5
#1 transferring dockerfile: 37B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:460703bfc6c8e1d3fc3bacedbddb2ef162ffa8c075ff6d47880ef1ce86ed605b
#2 transferring context: 34B done
#2 DONE 0.0s

#4 [internal] load metadata for docker.io/library/alpine:3.12
#4 sha256:dcbe6445faecb6a0adf28cc54a74893ed6f37ff445088ba92e20e9178ed92ea3
#4 DONE 0.0s

#3 [internal] load metadata for docker.io/ekidd/rust-musl-builder:1.50.0
#3 sha256:8cdb6d40eb50c8198a6c97fc38b7031f6bbda2f214c2469525c2e6a17853588b
#3 DONE 0.0s

#5 [execution 1/2] FROM docker.io/library/alpine:3.12
#5 sha256:bc0eb6cbe74f6c349104d22f689b973972c20362f3acba87a270406f51c8478a
#5 DONE 0.0s

#6 [builder  1/11] FROM docker.io/ekidd/rust-musl-builder:1.50.0
#6 sha256:f2f7fa3e5c15f2fde11baf8f28d28999b3cbb1c777d844ecdf147cdcde2eb8b9
#6 DONE 0.0s

#8 [internal] load build context
#8 sha256:8d3a8339dbdf8e8e01942b19a6930455b91a3003e70399cf8c51867f7cb8c859
#8 transferring context: 2.98kB 0.0s done
#8 DONE 0.0s

#9 [builder  3/11] COPY --chown=rust:rust Cargo.toml ./
#9 sha256:01d7fe6865bcf9531cffa4fc2ed6c6fe5ea0c23ad4e81fc94a209f43fae23fb2
#9 CACHED

#7 [builder  2/11] WORKDIR /home/rust
#7 sha256:f4bfad37f17ce03743e8d13a53aab9c85efbd64d30685aeb35f4ef4def1ee91a
#7 CACHED

#10 [builder  4/11] COPY --chown=rust:rust Cargo.lock ./
#10 sha256:2079b1bee55e35a5c5ac5319b2e2f50fa334f837d0a5744158c462133ee0e4f5
#10 CACHED

#11 [builder  5/11] COPY --chown=rust:rust testsuite/Cargo.toml testsuite/
#11 sha256:6b0ea54102b0255fae629f56b65fcf3847718a31bbc45a0a9e1cd91988ab2fb8
#11 DONE 0.1s

#12 [builder  6/11] COPY --chown=rust:rust testsuite/dummy_main_for_build_cache.rs testsuite/src/main.rs
#12 sha256:6e1c83b39c953820d76e60255da418ef299d98ebacd1c7facd02af39b41854bc
#12 DONE 0.1s

#13 [builder  7/11] RUN cargo build --release
#13 sha256:fb2209956b7c1c0515d8be13519c46ee90614580189d380d01f8abc2c8a36b81
...downloading Rust dependencies....
#13 DONE 371.8s

#14 [builder  8/11] COPY --chown=rust:rust testsuite testsuite
#14 sha256:4be017f7a89167e8cd0abce52f21ba485ecf5b0240a48c4642526bc055e0dac8
#14 DONE 0.1s

#15 [builder  9/11] RUN cargo test --release --bin testsuite
#15 sha256:43f492e508d9289f0583dffc7b74905738f446321cdc385e8fe72b9d7f5cb3d6
#15 1.305    Compiling kurtosis-rust-example v1.10.3 (/home/rust/testsuite)
....bunch of Rust compile output.....
#15 DONE 2.4s

#16 [builder 10/11] RUN cargo build --release --bin testsuite
#16 sha256:7ead02b27e040538a177389c5a4f9719d288f031dce5414b26fbd10a4fe6333c
#16 0.588     Finished release [optimized] target(s) in 0.14s
#16 DONE 0.7s

#17 [builder 11/11] RUN md5sum /home/rust/target/x86_64-unknown-linux-musl/release/testsuite
#17 sha256:12dfadae64ec2b7bee7f45144156705932cc39b9eaae3a8e27f3d7a575d7cb53
#17 0.328 6e8664ccc75dd49597ae2af76c2620a4  /home/rust/target/x86_64-unknown-linux-musl/release/testsuite
#17 DONE 0.4s

#18 [execution 2/2] COPY --from=builder /home/rust/target/x86_64-unknown-linux-musl/release/testsuite ./
#18 sha256:4762ead50cfcd6861c2f1ada1de12b2d400307ea9ecefa0c37f9e4e11fdff143
#18 CACHED

#19 exporting to image
#19 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#19 exporting layers done
#19 writing image sha256:2ff79b23345c11d6e8b082bfef1ccce9bc0c1a3f09031153cd088c89b992244d done
#19 naming to docker.io/library/solana-testsuite:mieubrisse_localnet-sanity done
#19 DONE 0.0s
```

So I think using that, we can determine that the binary is indeed changing every time, and the COPY of the binary from builder -> execution stage should never be cached.

**Comment by mieubrisse** [comment] 2021-02-26 02:14
Also, just confirmed that `cargo build` is indeed how the `Cargo.lock` gets updated; `cargo update` is for updating all dependencies to a new version. So def don't want to be running that after every `Cargo.toml` modification

**Comment by mieubrisse** [comment] 2021-03-05 22:15
Hey @thaJeztah , just wanted to ping back on this - does this look like something from the Docker build system side?

**Comment by mieubrisse** [comment] 2021-03-12 23:42
Hey @thaJeztah pinging again - AFAICT I'm not doing anything strange; is there any more debugging or metrics that you'd like me to grab?

**Comment by mieubrisse** [comment] 2021-03-13 05:28
Hokay, finally solved this - your hunch was correct @thaJeztah ; Rust won't rebuild the output binary _unless the main.rs mtime is newer than the output binary mtime_ ( https://github.com/emk/rust-musl-builder/issues/101 ). Adding a `touch` on the main.rs finally solved it. Thanks for all the help, and here's hoping we get https://github.com/rust-lang/cargo/issues/2644 soon so that all these hacks can be obviated soon!

**Comment by thaJeztah** [comment] 2021-03-22 14:14
oh, wah! Sorry, for the delay, this one slipped down my list. Good to hear you managed to resolve the issue; tbh, still a bit confused why the md5sum returns a different result in your case, but possibly it's taking metadata into account that is (on purpose) ignored by BuildKit when calculating the checksum 🤔

**Comment by tonistiigi** [comment] 2021-03-22 16:25
@mieubrisse @thaJeztah fyi https://github.com/docker/buildx/issues/554
