### ISSUE TITLE
Docker Pull Fails in Rootless "failed to register layer: failed to Lchown "/dev/console" for UID 0, GID 0: lchown /dev/console: no such file or directory"

### ISSUE THREAD

**Issue by TryAnixx** [docker/for-linux#1497] opened 2024-06-26 09:52 UTC
Hey folks!

I am trying to pull the mysql:8.2.0 / mysql:latest image in rootless docker

Expected behavior:
- Pull goes through

actual behavior:
```failed to register layer: failed to Lchown "/dev/console" for UID 0, GID 0: lchown /dev/console: no such file or directory```

subuid:
docker-admin:100000:65536

subgid:
docker-admin:100000:65536

Outpout of Docker Version:
```
Client: Docker Engine - Community
 Version:           27.0.1
 API version:       1.46
 Go version:        go1.21.11
 Git commit:        7fafd33
 Built:             Mon Jun 24 14:58:03 2024
 OS/Arch:           linux/amd64
 Context:           rootless

Server: Docker Engine - Community
 Engine:
  Version:          27.0.1
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       ff1e2c0
  Built:            Mon Jun 24 14:58:03 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.33
  GitCommit:        d2d58213f83a351ca8f528a95fbd145f5654e957
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
 rootlesskit:
  Version:          2.0.2
  ApiVersion:       1.1.1
  NetworkDriver:    slirp4netns
  PortDriver:       builtin
  StateDir:         /run/user/1000/dockerd-rootless
 slirp4netns:
  Version:          1.2.1
  GitCommit:        09e31e92fa3d2a1d3ca261adaeb012c8d75a8194
  
```

Output of docker info:
```
Client: Docker Engine - Community
 Version:    27.0.1
 Context:    rootless
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.15.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.28.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 8
 Server Version: 27.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d2d58213f83a351ca8f528a95fbd145f5654e957
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  rootless
  cgroupns
 Kernel Version: 6.8.0-35-generic
 Operating System: Ubuntu 24.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.731GiB
 Name: sf-docker1
 ID: 002f2b39-30a0-4a59-b858-68615345db5d
 Docker Root Dir: /home/docker-admin/.local/share/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No cpuset support
WARNING: No io.weight support
WARNING: No io.weight (per device) support
WARNING: No io.max (rbps) support
WARNING: No io.max (wbps) support
WARNING: No io.max (riops) support
WARNING: No io.max (wiops) support
```

**Comment by TryAnixx** [comment] 2024-06-26 09:53
pull of other images work

**Comment by strickes** [comment] 2024-06-26 10:19
I have the exact same problem. Running Proxmox with Unprivileged LXC and Docker inside

**Comment by TryAnixx** [comment] 2024-06-26 10:27
> I have the exact same problem. Running Proxmox with Privileged LXC and Docker inside

can you show your subuid and subgid?

**Comment by strickes** [comment] 2024-06-26 10:31
> > I have the exact same problem. Running Proxmox with Privileged LXC and Docker inside
> 
> can you show your subuid and subgid?

cat /etc/subuid
root:100000:65536
cat /etc/subgid
root:100000:65536

**Comment by TryAnixx** [comment] 2024-06-26 10:41
these are my groups: 

uid=1000(docker-admin) gid=1000(docker-admin) groups=1000(docker-admin),27(sudo),100(users),988(docker)

**Comment by TryAnixx** [comment] 2024-06-26 10:41
> > > I have the exact same problem. Running Proxmox with Privileged LXC and Docker inside
> > 
> > 
> > can you show your subuid and subgid?
> 
> cat /etc/subuid root:100000:65536 cat /etc/subgid root:100000:65536

Are you pulling the mysql image too? or any other image

**Comment by strickes** [comment] 2024-06-26 10:45
> > > > I have the exact same problem. Running Proxmox with Privileged LXC and Docker inside
> > > 
> > > 
> > > can you show your subuid and subgid?
> > 
> > 
> > cat /etc/subuid root:100000:65536 cat /etc/subgid root:100000:65536
> 
> Are you pulling the mysql image too? or any other image

yes I only have this problem with the mysql image. Yesterday everything worked and today I it doesn't even pull, I get the exact same error message as you. Existing LXCs with Docker inside aren't affected, but I'm also afraid on running updates on them now :D 
I'm using TTecks Docker Script to setup the LXCs and they were working fine until now and I don't see any changes on them since a few days ago, so I'm currently at a loss why it suddenly stopped working

**Comment by strickes** [comment] 2024-06-26 10:58
MariaDB images are working, well maybe it's time to finally switch :)

**Comment by TryAnixx** [comment] 2024-06-26 11:21
> MariaDB images are working, well maybe it's time to finally switch :)

my other image only supports mysql...

**Comment by strickes** [comment] 2024-06-26 11:23
well nevermind I found another image too with the same problem
image: opensearchproject/opensearch:1

**Comment by TryAnixx** [comment] 2024-06-26 11:26
> well nevermind I found another image too with the same problem image: opensearchproject/opensearch:1

same problem on this image for me too

**Comment by TryAnixx** [comment] 2024-06-26 11:34
found this: https://docs.docker.com/engine/security/rootless/#docker-pull-errors

but doesnt help me..

**Comment by aarandag** [comment] 2024-06-26 15:13
We are getting the same issue when pulling amazonlinux:2 and other images. Rolling back to docker 26.1.4 solves the issue. It seems related to the new 27.0.1 release.

**Comment by TryAnixx** [comment] 2024-06-26 15:38
> We are getting the same issue when pulling amazonlinux:2 and other images. Rolling back to docker 26.1.4 solves the issue. It seems related to the new 27.0.1 release.

have you tried rolling back to 27.0? why 26.1.4???

**Comment by aarandag** [comment] 2024-06-26 15:48
> > We are getting the same issue when pulling amazonlinux:2 and other images. Rolling back to docker 26.1.4 solves the issue. It seems related to the new 27.0.1 release.
> 
> have you tried rolling back to 27.0? why 26.1.4???

`There's no 27.0.0 release due to a mistake during the pre-release of 27.0.0-rc.1 on GitHub which resulted in the v27.0.0 tag being created.`

https://docs.docker.com/engine/release-notes/27.0/#2700

**Comment by TryAnixx** [comment] 2024-06-26 16:28
> We are getting the same issue when pulling amazonlinux:2 and other images. Rolling back to docker 26.1.4 solves the issue. It seems related to the new 27.0.1 release.

This fixed my issues

**Comment by jonpaul** [comment] 2024-06-26 18:56
We have also run into this behavior using a base image of ubuntu Jammy (AMI=`ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*`)and installing rootless via `get.docker.com/rootless`, using engine v27.0.1 with root resolved the issue.

**Comment by ZeroInputCtrl** [comment] 2024-06-26 19:07
Looks like this is only breaking for the oraclelinux images. I switched to the `-debian` tag and no more issues as far as i can tell.

**Comment by TryAnixx** [comment] 2024-06-26 19:09
i am still using rootless now with the mysql image but on the older version, i think its a docker issue.

**Comment by Jdogzz** [comment] 2024-06-26 19:15
For anyone getting here in a debian based environment (I'm in the same position as mentioned earlier in this issue with an LXC), to roll back to the last good version I followed the steps here:

https://unix.stackexchange.com/questions/79050/can-i-rollback-an-apt-get-upgrade-if-something-goes-wrong

This boiled down to verifying if this command was going to roll back the correct set of packages (I did the update yesterday on 2024-06-26) :
```
apt-get -s install $(awk '$1 == "2024-06-26" && $3 == "upgrade" {print $4"="$5}' /var/log/dpkg.log | tr '\n' ' ')
```

and if so (for me it did), then remove the `-s` and run the command to do the rollback.

**Comment by ZeroInputCtrl** [comment] 2024-06-26 19:19
> i am still using rootless now with the mysql image but on the older version, i think its a docker issue.

yes for sure, just saying that the debian image on rootless seems to be working just fine. It seems to be a conflict with oraclelinux and the latest version of docker.

**Comment by aarandag** [comment] 2024-06-26 19:34
We also got this issue when trying to pull an image based on Alpine Linux.

**Comment by demslam** [comment] 2024-06-26 19:40
seemed to have solve this w/ 
`apt install docker-compose`
after i did that install things seemed to work for me.

**Comment by TryAnixx** [comment] 2024-06-26 19:46
> seemed to have solve this w/ `apt install docker-compose` after i did that install things seemed to work for me.

probably because docker-compose is older than docker compose

**Comment by strickes** [comment] 2024-06-26 20:34
```bash
apt-get install docker-ce=5:26.1.4-1~debian.12~bookworm docker-ce-cli=5:26.1.4-1~debian.12~bookworm containerd.io
```
fixed it on my side

**Comment by zek** [comment] 2024-06-27 04:19
Pulling image with "sudo" also works.

**Comment by andzejsp** [comment] 2024-06-27 20:32
> ```shell
> apt-get install docker-ce=5:26.1.4-1~debian.12~bookworm docker-ce-cli=5:26.1.4-1~debian.12~bookworm containerd.io
> ```
> 
> fixed it on my side

this saved my life, thank you and be King Terry with you

**Comment by SimpleHomelab** [comment] 2024-06-27 21:16
> ```shell
> apt-get install docker-ce=5:26.1.4-1~debian.12~bookworm docker-ce-cli=5:26.1.4-1~debian.12~bookworm containerd.io
> ```
> 
> fixed it on my side

Fixed it for me on Ubuntu 22.04

```
apt-get install docker-ce=5:26.1.4-1~ubuntu.22.04~jammy docker-ce-cli=5:26.1.4-1~ubuntu.22.04~jammy containerd.io
```

**Comment by pablos1rvent** [comment] 2024-06-27 21:23
Same error here pulling: https://hub.docker.com/r/linuxserver/wireguard

If you download proxmox, all default, CT with debian, and portainer -> it fails on pulling with dev console

_What's wrong with the folks telling to downgrande and reinstall lol, that's crazy af_

**Comment by pablos1rvent** [comment] 2024-06-27 21:28
> ```shell
> apt-get install docker-ce=5:26.1.4-1~debian.12~bookworm docker-ce-cli=5:26.1.4-1~debian.12~bookworm containerd.io
> ```
> 
> fixed it on my side

fixed 100%. Thanks!!

**Comment by notten13** [comment] 2024-06-28 08:14
Hi, I'm seeing the same issue pulling mysql 8.0.35 images on AWS Ubuntu machines.

Do we know why this is happening? And whether it's a bug in Docker itself, which we can expect to be fixed soon, or if it's something else entirely?

Basically, I appreciate that this can be fixed by downgrading Docker, but in the context of a project for the company I work for I'm not comfortable having it stuck on Docker 26

**Comment by andzejsp** [comment] 2024-06-28 08:21
> Hi, I'm seeing the same issue pulling mysql 8.0.35 images on AWS Ubuntu machines.
> 
> Do we know why this is happening? And whether it's a bug in Docker itself, which we can expect to be fixed soon, or if it's something else entirely?
> 
> Basically, I appreciate that this can be fixed by downgrading Docker, but in the context of a project for the company I work for I'm not comfortable having it stuck on Docker 26

dont care, just regress to lower version:

replace the `debian.12~bookworm` with your os. I did that for ubuntu and it worked... 
```
apt-get install docker-ce=5:26.1.4-1~debian.12~bookworm docker-ce-cli=5:26.1.4-1~debian.12~bookworm containerd.io
```

**Comment by thaJeztah** [comment] 2024-06-28 08:55
The upstream ticket tracking this;

- https://github.com/moby/moby/issues/48064

We discussed that regression in Yesterday's maintainers call, and (to be confirmed) we may have found the cause, which I just wrote down in a summary on that ticket; https://github.com/moby/moby/issues/48064#issuecomment-2196436894

**Comment by thaJeztah** [comment] 2024-06-28 08:55
I'm closing this ticket as a duplicate of https://github.com/moby/moby/issues/48064, and I'll lock the conversation on this ticket, as at this point we have a good understanding of the problem and don't need more "I have the same issue" report, but if you're having this issue, you can use the "subscribe" button on the upstream ticket to stay informed on updates.

**Closed as completed by thaJeztah** 2024-06-28 08:55 UTC
Labels: kind/bug, area/rootless
