### ISSUE TITLE
privileged container which is running init process inside a container kills all TTY sessions on host

### ISSUE THREAD

**Issue by artyom-bilun** [docker/for-linux#106] opened 2017-09-17 09:50 UTC
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

systemd init process is working inside a container by running the following command:
`docker run --privileged centos:7 /usr/sbin/init`

### Actual behavior

It works as expected, container is running, systemd is working inside a container, but with a curious side effect, it kills all tty sessions on the host and I get the login prompt inside the container which is blocking all ways to communicate with host.

### Steps to reproduce the behavior

`docker run --privileged centos:7 /usr/sbin/init`
There can be any container, which is supporting service management 

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   3dfb8343
 Built:        Wed Jul 26 18:03:33 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87617
 Built:        Wed Jul 26 20:03:39 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 12
 Running: 0
 Paused: 0
 Stopped: 12
Images: 8
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.12.8-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.754GiB
Name: morda-home
ID: 55W4:VXU5:F655:PWBP:YMVO:A2V3:RNN5:O5I6:WX7F:5TE6:THRO:4P5S
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
OS: Arch Linux x86_64 
Kernel: 4.12.8-1-ARCH

**Comment by thaJeztah** [comment] 2017-09-19 12:06
What's happening, is that you start a container in "attached" mode (it's running in the foreground), but there is no TTY or stdIn attached to the container. Therefore, any key you type is not forwarded to the container, making it look like it "hangs".

To resolve this, either:

Run the container in the background ("detached") by adding the `-d` / `--detach` flag on `docker run`:

```bash
docker run -d --privileged centos:7 /usr/sbin/init
```

Or run the container interactively by adding the `-i`  and `-t` flags (which can be combined to `-it`):

```bash
docker run -it --privileged centos:7 /usr/sbin/init
```

Running systemd interactively is unlikely what you want (more likely you want a shell), so the second option is probably not what you're looking for in this particular case.

I should add a big warning here: running a container with `--privileged` is _highly_ insecure; basically you give the container full root access to the host. 

First of all, consider if you really need systemd to be running in your container. Overall we discourage doing so; [containers are not VMs](https://blog.docker.com/2016/03/containers-are-not-vms/), they're a system to run processes in isolation. Instead of running multiple processes in your container, consider creating a separate container for each.

For containers, no init process is generally needed if the container's main process is properly developed. Some processes unfortunately are not, which can lead to child processes not being properly "reaped" if the container exits. If you want to run systemd for that reason, consider using the `--init` flag on `docker run`. Setting that flag inserts a very minimal init process ([`tini`](https://github.com/krallin/tini)) into the container. That init process runs as "pid 1" inside the container and it's only task is to make sure all processes are cleaned up if the container exits.

If you absolutely _must_ run systemd, **don't** use `--privileged`; instead use `--cap-add` to specify the exact permissions you want to give your container. For systemd, you'll also need to set an environment variable (`container=docker`) to let systemd know its running in a container, and give it access to your host's cgroups (also see the discussion here: https://github.com/moby/moby/issues/2296#issuecomment-238530205). Something like below:

```bash
docker run -ti --cap-add=SYS_ADMIN -e "container=docker" -v /sys/fs/cgroup:/sys/fs/cgroup centos:7 /usr/sbin/init
```

I'm closing this issue because this is not a bug, but feel free to continue the conversation :+1:

**Closed by thaJeztah** 2017-09-19 12:06 UTC

**Comment by artyom-bilun** [comment] 2017-09-23 10:02
Thank you for replying and sorry for the long absence.

Continuing the conversation. I understand that my case is incorrect usage of containers, I use it to test my environment using Chef CM, which gives me a _considerable_ advantage in speed of preparing the environment.
Actually, 
`docker run -ti --cap-add=SYS_ADMIN -e "container=docker" -v /sys/fs/cgroup:/sys/fs/cgroup centos:7 /usr/sbin/init`
is exactly what I need.

I just want to notice that
`docker run -d --privileged centos:7 /usr/sbin/init`
and
`docker run -it --privileged centos:7 /usr/sbin/init`
commands are still destroying all my tty sessions and I haven't been able to reproduce it on Centos, Debian and Ubuntu systems.

**Comment by IronhandedLayman** [comment] 2018-02-13 21:01
This isn't an isolated incident. Seems that the gluster/gluster-centos docker container also runs privileged and starts /usr/sbin/init, screwing with more than just TTY... it will also change sysctl settings to whatever the CentOS defaults are, breaking any custom settings on the host node. And I can only imagine a number of other issues, since it's essentially simulating a system boot.

This has to be a bad practice. I have no good way of assessing the damage done with when running a container in this way.

**Comment by thaJeztah** [comment] 2018-02-13 21:23
Yes; as mentioned; running `—privileged` is dangerous, and should not be taken lightly; especially not on untrusted images
